### PR TITLE
Add an implementation of Swift

### PR DESCRIPTION
**Pull request by CikeQiu**
I used Swift to achieve the BIP39, currently supports Chinese and English. Reference to [NYMnemonic](https://github.com/nybex/NYMnemonic), the third party encryption algorithm library  [CryptoSwift](https://github.com/krzyzanowskim/CryptoSwift) .

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by CikeQiu** [comment]
This is the first time I've tried to implement BIP39, your advice is very important to me. And you can get more information at [CKMnemonic](https://github.com/CikeQiu/CKMnemonic) .

**Comment by prusnak** [comment]
ACK

**Comment by CikeQiu** [comment]
Hi, would you merge this request?

**Pull request merged**
