### PR TITLE
BIP0039 Adding dutch wordlist

### PR DESCRIPTION
**Pull request by StijnVA**

### CODE REVIEW

**Comment by AbelLykens** [comment]
NACK - most of these are rarely used words. Would be better to do some freq analysis and use only well-known/often used words.

**Comment by frodojansen** [comment]
As a Dutch native, I have never seen or heard many of the words proposed. Seeds words should be clear and easy to remember. 

Do we really need or want a wordlist for each and every language? I prefer the KISS principle instead.

**Comment by pretyflaco** [comment]
NACK 

Every additional wordlist added limits the space for subsequent wordlists in other languages. If additional wordlists should be added, languages with more speakers should have priority over those with few.

**Comment by StijnVA** [comment]
@AbelLykens Thank you for your input, do you have by any means any suggestion on how to perform a frequency analysis (some tooling?)

@frodojansen Thank you for your input, I indeed did not handpick the word. They are based on an word list and then selected by elimination on not conflicting and minimal conditions.  The frequency analysis suggested by @AbelLykens will address that. 

@pretyflaco and @frodojansen Both the questions are irrelevant "do we need multiple list" was addressed as soon ore than one list was created. "Do we need a Dutch list based on the number of speakers" is also addressed by the existence of the Czech word list.

**Comment by pretyflaco** [comment]
It is not addressed by existence of Czech wordlist as the situation is not the same. The space for new languages is not the same as when the Czech wordlist was created.

**Comment by kristapsk** [comment]
> It is not addressed by existence of Czech wordlist as the situation is not the same. The space for new languages is not the same as when the Czech wordlist was created.

Why there is limited space? What limits number of languages that can be added?

**Comment by AbelLykens** [comment]
> @AbelLykens Thank you for your input, do you have by any means any suggestion on how to perform a frequency analysis (some tooling?)

I started a bit here: https://github.com/AbelLykens/bip39-nl . It takes words from opensubtitles from 2014 and 2015, gets the most used ones, filters out unique first-four-letter words.

We could work from the resulting 4096 wordlist and eliminate bad ones to come to a 2048 word list.

**Comment by AbelLykens** [comment]
To elaborate, I suggest:

1. Use [this list](https://github.com/AbelLykens/bip39-nl/blob/main/results_4096_sorted.csv) as a start
2. (optional) Copy it to your own repo
3. Clear out all bad words: politically sensitive words, words that look too much alike (like `koop` and `koos`, just 1 letter difference)
4. (optional) submit back to my repo and/or (just) change the list of this PR

**Comment by pretyflaco** [comment]
> > It is not addressed by existence of Czech wordlist as the situation is not the same. The space for new languages is not the same as when the Czech wordlist was created.
> 
> Why there is limited space? What limits number of languages that can be added?

The first four characters of seed words must be unique, not just in the language wordlist, but across all language wordlists. Hence, the addition of every new wordlist with latin alphabet characters narrows down the space for unique 4 character combinations. 

See https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md#czech:
> No words already used in other language mnemonic sets (english, italian, french, spanish). Letters with diacritical marks from these sets are counted as analogous letters without diacritical marks.

Also https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#wordlists 
> Since the vast majority of BIP39 wallets supports only the English wordlist, it is strongly discouraged to use non-English wordlists for generating the mnemonic sentences.

**Review by Asoygeboy01 — COMMENTED** [review]
Sorry

**Comment by AbelLykens** [comment]
I see I never replied here. This could work: https://github.com/AbelLykens/bip39-nl/blob/main/results_2048_sorted.csv . 

Though I think we should close this. I think EN works fine for Dutchies.

If we do want to use an NL wordlist, let's see if we can use the one I linked (=mine). It uses words from open source word lists and subtitles to find often-occurring words. And filters for first-four-letter uniqueness.

**Comment by StijnVA** [comment]
closing, It was a nice exercise. But indeed not needed.

I kind of was triggered  by the discussion in relation to the Czech word list. I really can't comprehend making the "first come, first serve" and "future space allocation" in one sentence.. (let it go :-) )

**Pull request closed without merging**
