### PR TITLE
Fixing spelling in multiple BIPs

### PR DESCRIPTION
**Pull request by meshcollider**
Fixing spelling mistakes picked up by this bot:
https://github.com/ka7/misspell_fixer

### CODE REVIEW

**Comment by jimmysong** [comment]
ACK BIP80

**Comment by justusranvier** [comment]
ACK BIP47

**Comment by prusnak** [comment]
ACK BIP39

**Comment by maraoz** [comment]
ACK BIP45

**Comment by sipa** [comment]
ACK BIP9, BIP32, BIP103

**Comment by petertodd** [comment]
ACK BIP9, BIP65

**Comment by cdecker** [comment]
ACK BIP140

>

**Comment by UpalChakraborty** [comment]
ACK BIP106

**Comment by jtimon** [comment]
ack bip99

**Comment by sipa** [comment]
ack bip143

**Comment by rustyrussell** [comment]
ACK BIP9

**Comment by luke-jr** [comment]
Merged BIPs 9, 19, 32, 39, 45, 47, 65, 75, 80, 99, 103, 106, 140, 143

Still remaining: BIPs 10, 11, 14, 15, 16, 35, 61, 109, 150

* BIP 10: @etotheipi
* BIP 11: @gavinandresen
* BIP 14: @genjix @phantomcircuit
* BIP 15: @genjix
* BIP 16: @gavinandresen
* BIP 35: @jgarzik
* BIP 61:: @gavinandresen
* BIP 109: @gavinandresen
* BIP 150: @jonasschnelli

**Comment by jonasschnelli** [comment]
ACK BIP150

**Comment by luke-jr** [comment]
Merged BIP150

**Comment by gavinandresen** [comment]
Please don't bother me with trivial issues like spelling corrections in the future, I don't care if they are corrected or not, the meaning is clear either way so it is a non-issue.

**Comment by Pornprasert** [comment]
Hi

**Pull request closed without merging**
