### PR TITLE
Define retarget period in BIP9

### PR DESCRIPTION
**Pull request by Christewart**
Define the retarget period

### CODE REVIEW

**Comment by luke-jr** [comment]
@sipa @petertodd @gmaxwell @rustyrussell

**Comment by sipa** [comment]
"Currently" seems confusing, as this is not something that is easy to change. The interval for BIP9 however IS easy to change.

**Comment by Christewart** [comment]
@sipa What do you mean by the 'interval for BIP9'? Is this the amount of blocks that is needed for a proposed soft fork to go from 'DEFINED' to 'ACTIVE'/'FAILED'?

**Comment by sipa** [comment]
The sampling interval. BIP9 specifies to sample at every retarget, which is
every 2016 blocks. However, the sampling interval van be changes to
something else, the retarget interval can't. So saying that the retarget
interval is 'currently' 2016 is confusing.

**Comment by Christewart** [comment]
Interesting, perhaps we should add language around that in the BIP as well. It doesn't seem like that is said explicitly in the BIP right now. I'll write something up wrt to that later. I'll also remove the word 'currently'.

**Comment by Christewart** [comment]
Never mind, i'm not going to add language around the sampling interval. Assuming everyone is ok with my last change I'm not going to add any more commits.

**Comment by rustyrussell** [comment]
Luke-Jr <notifications@github.com> writes:
> @sipa @petertodd @gmaxwell @rustyrussell

Surprised retarget period needs definition.  If you want to, I'd say
just change:

 These are tallied each retarget period. 

To:

 These are tallied each retarget period (2016 blocks).

Cheers,
Rusty.

**Comment by sipa** [comment]
@rustyrussell's suggestion looks fine

**Comment by Christewart** [comment]
@luke-jr @sipa i've changed it to what @rustyrussell suggested and rebased. Should be good to merge

**Comment by petertodd** [comment]
Weak NACK - this isn't really detailed enough to be an implementable spec by itself, as there's other details about retarget periods that you'd need to know to actually implement this. So with that in mind I'd rather just keep calling it a "retarget period" in the spirit of "the code is the spec; bips just describe intent"

**Pull request closed without merging**
