### PR TITLE
Status => rejected

### PR DESCRIPTION
**Pull request by jwilkins**

### CODE REVIEW

**Comment by luke-jr** [comment]
Either @jgarzik needs to ACK, or it needs to timeout (3 years).

**Comment by gmaxwell** [comment]
https://lists.linuxfoundation.org/pipermail/bitcoin-segwit2x/2017-November/000685.html  < wouldn't this count as withdrawn by the proposer?

**Comment by ysangkok** [comment]
Actually the three years have passed now, but README.md needs to be updated, and the color of the row needs to be changed. I think this can be merged then? There is now a precedent for using the three year expiration rule. Ping @jwilkins

**Comment by luke-jr** [comment]
Merged via 2eca4d32c8284952ba4cbe19a1db7a23767482b9

**Pull request closed without merging**
