### PR TITLE
BIP-0069: [trivial] Move copyright section

### PR DESCRIPTION
**Pull request by MarcoFalke**
The section about the copyright should be either first or last.

### CODE REVIEW

**Comment by luke-jr** [comment]
No, see [BIP 1](https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki#what-belongs-in-a-successful-bip).

**Comment by MarcoFalke** [comment]
BIP1 does not impose the order. In fact, there is no other BIP with the copyright section between abstract and motivation. 

Section in the end:
[37](https://github.com/bitcoin/bips/blob/4553242d53719dcaaeb2bfe12e0acafcf03736a0/bip-0037.mediawiki#Copyright)
[42](https://github.com/bitcoin/bips/blob/1647c7e6d3e3866454b803fd874df2d0c4991f4a/bip-0042.mediawiki#Copyright)
[60](https://github.com/bitcoin/bips/blob/1647c7e6d3e3866454b803fd874df2d0c4991f4a/bip-0060.mediawiki#Copyright)
[65](https://github.com/bitcoin/bips/blob/5d0d854cdd5a69fa7d8b7ab6f557da4189cc5799/bip-0065.mediawiki#Copyright)
[105](https://github.com/bitcoin/bips/blob/f749070a23b62fd603c1341c36142b7d1c7f0f94/bip-0105.mediawiki#copyright)
[111](https://github.com/bitcoin/bips/blob/a110a5692fa25724f2ec6beffae5905a2c553564/bip-0111.mediawiki#copyright)
[112](https://github.com/bitcoin/bips/blob/6902f790f174c8af934869dcc5f10f94f816f65d/bip-0112.mediawiki#Copyright)
[113](https://github.com/bitcoin/bips/blob/d4c9a236ecb947866c61aefb868b284498489c2b/bip-0113.mediawiki#Copyright)

Section after motivation:
[38](https://github.com/bitcoin/bips/blob/master/bip-0038.mediawiki#Copyright)

**Comment by luke-jr** [comment]
The final call is up to @kristovatlas , but considering it uses BIP 1's order, I don't see how it can be an error.

**Comment by MarcoFalke** [comment]
Let's not call it an error but UX improvement: After reading the abstract, I was "ripped out" of the reading-flow.

So what about "fixing" BIP 1? ;-)

**Comment by kristovatlas** [comment]
I don't care at all

**Pull request closed without merging**
