### PR TITLE
witness reserved value

### PR DESCRIPTION
**Pull request by 4tochka**
current witness reserved value

### CODE REVIEW

**Comment by jl2012** [comment]
NACK. It has no special but no assumption could be made.

**Comment by 4tochka** [comment]
So at this moment to calculate correct commitment to verify block,  What  witness reserved value we should use?   Experimentally I got  correct value on existing testnet blocks using  b"\x00" * 32 
  _double_sha256(merkleroot(wtxid_list[::-1]) + b"\x00" * 32)_

**Comment by sipa** [comment]
For consensus rules, there is no restriction. Those 32 bytes can literally be anything, and the block will be valid.

**Comment by 4tochka** [comment]
Ok I understand, but still not clear about recent value. I have read BIP and got definition that Commitment hash: Double-SHA256(witness root hash|witness reserved value). Where is defined recently used _witness reserved value_? At example I take block from testnet and try to recalculate commitment hash. How do I know which value used by block creator concatenated with witness root hash? The result is Double-SHA256 and can't be reversed. Is any other document have definition about what value we should use today?

**Comment by sipa** [comment]
The value is in the coinbase transaction's witness. No need to guess it. It's chosen by the miner and included in the block.

**Comment by 4tochka** [comment]
Thank you!

**Comment by MarcoFalke** [comment]
Close?

**Comment by 4tochka** [comment]
Yes please close

**Comment by luke-jr** [comment]
I think it'd be reasonable to suggest some "default" value that can be used if a miner doesn't want to give it a special meaning. Otherwise, someone implementing could be left wondering...

**Pull request closed without merging**
