### PR TITLE
Fix typo on link to assignments

### PR DESCRIPTION
**Pull request by chriswheeler**

### CODE REVIEW

**Comment by luke-jr** [comment]
@sipa @petertodd @gmaxwell @rustyrussell

**Comment by btcdrak** [comment]
@luke-jr This is an obvious error, pointing to a 404 (introduced by my last commit). It should just be merged.

**Comment by MarcoFalke** [comment]
Can confirm this fixes the 404

**Comment by petertodd** [comment]
utACK https://github.com/bitcoin/bips/pull/395/commits/3dc43c84b134b4318376f40015a6840f6d900d14

**Pull request merged**
