### PR TITLE
BIPs 98, 116, and 117: Fast Merkle Trees; MERKLEBRANCHVERIFY; Tail Call Execution Semantics

### PR DESCRIPTION
**Pull request by kallewoof**

### CODE REVIEW

**Comment by luke-jr** [comment]
"(Consensus layer)" in the title of BIP 116 might be redundant with the Layer header, considering there's only one MERKLEBRANCHVERIFY BIP.

**Comment by kallewoof** [comment]
Added copyright sections. Will work out backwards compatibility and push changes.

**Comment by kallewoof** [comment]
Added compatibility sections.

**Comment by alexanderkjeldaas** [comment]
A quick read-through... there are a few things I would like to see in this BIP.  At least they would make it clearer to me. There should be a more comprehensive section on what this is NOT about.  For example:

1.  Who will be interpreting the proofs?  It seems like this is for the specific case where the receiver has no context or existing hashes.  This should be clarified.  If the receiver has a database of existing hashes, then much more efficient encodings are available (as used by git when displaying hashes for example).
2. The encoding seems to be focusing on defining multiple items in a set.  How about the single item case?
2. SKIP, DESCEND, and VERIFY are not defined.
3. I'm not sure, but it seems like some of the tree layouts are impossible in certain cases, for example when N-1 nodes have been defined, then the Nth node can't have any shape.

All in all, for various more focused cases, I'm guessing that the encoding could be significantly smaller than this.

On generic way of compressing the encoding would be to slice the hashes so 1 bit is encoded on each hash throughout the tree before the next bit is encoded.   This makes it possible to truncate the tree at some arbitrary point in order to use truncated hashes that can still be unique given some semantic rule as to how to order hashes.

**Pull request merged**
