### PR TITLE
Promote BIP9 to accepted

### PR DESCRIPTION
**Pull request by dcousens**

### CODE REVIEW

**Comment by laanwj** [comment]
You need to update the index table as well.

Was this status change discussed on the mailing list?

**Comment by dcousens** [comment]
> Was this status change discussed on the mailing list?

Unaware,  as I have trouble tracking the mailing list.
I was simply just probing the discussion given its status.

**Comment by luke-jr** [comment]
This status change only requires the Authors to ACK it at this point. (Transitioning to Final is another matter.)

One thing that may deserve consideration, however, is whether this BIP belongs to the Accepted/Final status realm at all, or instead to the Active status.

@sipa @petertodd @gmaxwell @rustyrussell

**Comment by laanwj** [comment]
> One thing that may deserve consideration, however, is whether this BIP belongs to the Accepted/Final status realm at all, or instead to the Active status.

As it is "Informational" and not "Standards-Track" that's a good point

**Comment by rustyrussell** [comment]
Luke-Jr <notifications@github.com> writes:
> This status change only requires the Authors to ACK it at this point. (Transitioning to Final is another matter.)

Acked by me.  I've leave the track/status question to you, however.

Thanks!
Rusty.

**Comment by petertodd** [comment]
ACK

**Comment by mcccs** [comment]
NACK, this has conflicts.

**Comment by luke-jr** [comment]
@mcccs Please explain what you're talking about.

**Comment by mcccs** [comment]
image

The pull request should be recreated.

**Comment by luke-jr** [comment]
This has been taken care of

**Pull request closed without merging**
