### PR TITLE
Update deployment of BIP113

### PR DESCRIPTION
**Pull request by btcdrak**

### CODE REVIEW

**Comment by luke-jr** [comment]
@maaku

**Comment by btcdrak** [comment]
@luke-jr This was discussed at the last [IRC meeting](http://bitcoinstats.com/irc/bitcoin-dev/logs/2015/10/15#l1444938803.0).

**Comment by luke-jr** [comment]
@btcdrak That's fine, it still needs an ACK from the BIP champion.

**Comment by btcdrak** [comment]
Closing for now because we're releasing this as a mempool only first. softfork will come later.

**Pull request closed without merging**
