### PR TITLE
Request for comments: Hardfork bit BIP

### PR DESCRIPTION
**Pull request by jl2012**

### CODE REVIEW

**Comment by luke-jr** [comment]
@jl2012 Ping me if you decide you want to move forward with this, or let me know if I should close it.

**Comment by jtimon** [comment]
Please, I would like a number for this BIP draft because I plan to refer it from bitcoin/#7566 and BIP99.

**Comment by MarcoFalke** [comment]
Maybe it's better to use something like `jl2012-hardforkbit` for now and refer to the actual bip number after merge?

**Comment by jl2012** [comment]
@jtimon after reading soft-hardfork proposalss like http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012457.html and http://lists.linuxfoundation.org/pipermail/bitcoin-dev/2016-February/012377.html , I'm not sure if this is a good idea

**Comment by jtimon** [comment]
@MarcoFalke what's the cost of giving it a number before merging? I don't think we're merging any bips without a number anyway.

@jl2012 those ideas are interesting but I don't think they make this one less of a good idea (even if the others are incompatible and better). Remember that not all BIPs need to be adopted. But if you don't want to continue persuing this, I understand. I can just talk about the hardfork bip in bip99 as originally planned instead of referring to this BIP.
If that is the case, I guess we should close this PR though.

**Comment by jl2012** [comment]
@jtimon I think you may still refer to this with the like to this PR. I'm closing this for now until someone really implement this

**Comment by jtimon** [comment]
> @jtimon I think you may still refer to this with the like to this PR. I'm closing this for now until someone really implement this

Here's an implementation (on top of my BIP9 implementation): https://github.com/jtimon/bitcoin/commit/990dda87b258c1e8d4d35b1fcbae4106303664f0

**Pull request closed without merging**
