### PR TITLE
Reject 156 (expired)

### PR DESCRIPTION
**Pull request by ysangkok**
This BIP proposal has expired according to BIP-0002 expiration rules, and I submit this PR even though I am not an author.

### CODE REVIEW

**Comment by ysangkok** [comment]
Currently not implementable because it would allow DoS attacks: [pr 13947 closed with comment by MarcoFalke](https://github.com/bitcoin/bitcoin/pull/13947#issuecomment-513858189)

**Comment by MarcoFalke** [comment]
Is this implemented by any other implementation?

**Comment by ysangkok** [comment]
@MarcoFalke It is not in btcd, Knots, bitcore, Bitcoin XT, libbitcoin or bcoin as far as I can see from cursory searching of their source repositories that are freely available online. Can the node impl list at https://coin.dance/nodes be trusted for the purpose of determining existing node implementations?

**Comment by luke-jr** [comment]
We can always revert this if it turns out to be in error

**Pull request merged**
