### PR TITLE
Update status for segwit related BIPs

### PR DESCRIPTION
**Pull request by jl2012**

### CODE REVIEW

**Comment by ysangkok** [comment]
You could also update `bip-0009/assignments.mediawiki`

**Comment by luke-jr** [comment]
Merged BIP 142 & 145 status changes.

@CodeShark @sipa Please ACK progression of BIP 144 to Final status.

**Comment by btcdrak** [comment]
@luke-jr Isnt the status of these BIPs defined by the blockchain, not by the original authors, and therefore this PR is obviously correct.

**Comment by sipa** [comment]
ACK

**Comment by CodeShark** [comment]
ACK

**Comment by jonathancross** [comment]
@jl2012 Please rebase.

**Pull request merged**
