### PR TITLE
Reject BIP-0075 (three years inactivity)

### PR DESCRIPTION
**Pull request by ysangkok**
Per BIP-0002 expiration rules, this can be requested by anybody.

### CODE REVIEW

**Comment by luke-jr** [comment]
@justinwnewton @techguy613 @voisine @jmacwhyte Any progress on this? Has it been implemented anywhere?

**Comment by jmacwhyte** [comment]
@luke-jr It is being used by some of Netki's products, one of which is https://github.com/netkicorp/addressimo.

BRD has some internal WIP projects built on it, but since I am no longer at BRD I can not comment on release schedules.

**Comment by jmacwhyte** [comment]
If the above is insufficient to address your concerns, please let me know before any action is taken so we can discuss. Thanks!

**Comment by luke-jr** [comment]
This would need 2 implementations. Is there another Netki product we can reference? And/or can BRD comment on the status of using it?

**Comment by justinwnewton** [comment]
PwC’s Vulcan platform uses BIP 75 on their mobile wallets as well as at their co-signer.  If you’d like I can connect you to the partner at PwC responsible for the platform.

Justin

**Comment by luke-jr** [comment]
Ok, so this should be closed.

Can a BIP champion ACK the progression from Draft->Proposed, so we can move it forward to Final?

**Comment by justinwnewton** [comment]
I’d be happy to do that.  Can you give me a pointer how?  Thank you!

**Comment by luke-jr** [comment]
Just saying so is enough. Done in 213fb62ceabdbcfe3576d83c3ca3d986e4b45ae9

**Comment by jmacwhyte** [comment]
Thanks @luke-jr !

**Pull request closed without merging**
