### PR TITLE
BIP341: fix int conversion in taproot_tweak_pubkey

### PR DESCRIPTION
**Pull request by DariusParvin**
- fix the int conversion to use `int_from_bytes()` rather than `int()`

### CODE REVIEW

**Review by jonasnick — APPROVED** [review]
ACK 232f47f210f72b3a0e675d616e567b190a870821

**Review by theStack — APPROVED** [review]
ACK 232f47f210f72b3a0e675d616e567b190a870821

**Comment by kallewoof** [comment]
Conflicts need resolving.

**Comment by jonasnick** [comment]
This has been fixed in #341. But thanks @DariusParvin for noticing this issue. Can you close the PR?

**Pull request closed without merging**
