### PR TITLE
bip-0039-wordlists : Typos, capitalization and trailing whitespace.

### PR DESCRIPTION
**Pull request by jonathancross**
* "there not must" => "there must not"
* "exemple" => "example"
* Capitalize "French", "Italian"
* Trailing whitespace removal.

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by prusnak** [comment]
ACK

**Comment by jonathancross** [comment]
@luke-jr

**Comment by jonathancross** [comment]
Hi @luke-jr, anything else you need on this?

**Comment by luke-jr** [comment]
No, sorry for the delay, I missed the ACK.

**Comment by Yessenia6969** [comment]
> * "there not must" => "there must not"
> * "exemple" => "example"
> * Capitalize "French", "Italian"
> * Trailing whitespace removal.https://github.com/bitcoin/bips/pull/521#issue-223111969

**Comment by Yuttana12wr** [comment]
> * "there not must" => "there must not"
> * "exemple" => "example"
> * Capitalize "French", "Italian"
> * Trailing whitespace removal.

**Comment by Yuttana12wr** [comment]
there not must" => "there must not"
"exemple" => "example"
Capitalize "French", "Italian"
Trailing whitespace removal.

**Pull request merged**
