### PR TITLE
[BIP 39] Create catalan.txt

### PR DESCRIPTION
**Pull request by fburrull**
No accents, no special characters, 4 first letters all different

### CODE REVIEW

**Comment by fburrull** [comment]
wordlist has the following characteristics:

a) smart selection of words

  - the wordlist is created in such a way that it's enough to type the first four
    letters to unambiguously identify the word

b) similar words avoided

c) sorted wordlist method:
cat unsortedlist.txt | uniq -w 4  | sort > sortedandunambiguouslist.txt

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by daniel3997** [comment]
How can I get my private Leo please

**Comment by daniel3997** [comment]
How can I get my private key please I think bitcoin and crypto are not meant for illiterate like me but I’m loosing my hard money 😭 😭 it’s too hard to get this key omg someone please help

**Review by Stevenans66 — APPROVED** [review]

**Comment by bradley101** [comment]
> How can I get my private key please I think bitcoin and crypto are not meant for illiterate like me but I’m loosing my hard money 😭 😭 it’s too hard to get this key omg someone please help

Download Bitcoin core. Run `dumpprivkey "<wallet file>" and you'll get your private key. If you have a password set, the first unlock your wallet by typing the phrase and then executing the command.

**Comment by Stevenans66** [comment]
Ok actually we can recover it back dont worry , run your wallet from the terminal and then check on gnu ,you will find your private key

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daniel3997** [comment]
Hello I really don’t understand how to do this I am not using an android
phone I’m using an iPhone please can you help me out

**Comment by Stevenans66** [comment]
Ok. Another way export try to export your wallet backup to email , then extract it ,then find some sort decrypt tool.i am not so sure with iphone function , i usually use linux ,android

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by daniel3997** [comment]
I have gotten the private key to my Blockchain Ethereum and also the
private key to my blockchain Stellar too but the problem here is that I
sent the BCH from a different crypto platform name CEX.IO into and
meanwhile in the cause of me sending this I copied my blockchain BTC wallet
and paste it in the CEX.IO BCH wallet to send so how can I get this bitcoin
back please help me

**Comment by bradley101** [comment]
You cannot undo a transaction in a blockchain.

**Comment by Stevenans66** [comment]
Contact the blockchain webmaster for asistance,

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by Stevenans66** [comment]
I have got his link
https://keybase.io/download?invite

Get Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by kallewoof** [comment]
Two violations of 4-first-letters-unique, and a duplicate pair.

badall
badar

granada
granular

incendi
incendi

**Comment by fburrull** [comment]
Corrected: 
badar -> badina
granular -> grao
eliminated duplicated: "incendi"
added: inert
[catalan.txt](https://github.com/bitcoin/bips/files/6643687/catalan.txt)

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Pull request closed without merging**
