### PR TITLE
BIP 340 & 341: use consistent definition of lift_x

### PR DESCRIPTION
**Pull request by jonasnick**
As pointed out by @Randy808 [here](https://github.com/bitcoin/bips/pull/1348#issuecomment-1212973614).

CC @sipa @ajtowns

### CODE REVIEW

**Comment by jonasnick** [comment]
I noticed that this PR alone does not fix the problem: lift_x has different definitions in the BIP-340 mediawiki specification and the reference code. The first commit in this PR makes `taproot_tweak_pubkey` correct with respect to lift_x in the mediawiki spec but incorrect wrt the reference code. I think the best option is to harmonize both definitions lift_x and added a commit that changes lift_x in the reference code.

CC @real-or-random

**Comment by real-or-random** [comment]
tACK

Should we add a Changelog that tracks (non-trivial) changes? I think it won't hurt but I'm not convinced that it's worth the effort. The git log may be good enough to be honest.
https://github.com/bitcoin/bips/commits/master?before=64aba767e2d422b5d471509acc340750432613ae+35&branch=master&path%5B%5D=bip-0340.mediawiki&qualified_name=refs%2Fheads%2Fmaster 
We'd need to decide on when to start it, maybe pragmatically after https://github.com/bitcoin/bips/commit/3b1fb9600b938172dd98a63e4906a861af9c3ab0? 



> As pointed out by @Randy808 [here](https://github.com/jonasnick/bips/pull/new/fix-missing-int).
wrong link target?

**Comment by jonasnick** [comment]
Sorry, fixed the link.

**Review by haleemshal — APPROVED** [review]

**Comment by jonasnick** [comment]
Added a changelog akin to https://github.com/sipa/bips/pull/221.

**Comment by real-or-random** [comment]
Ok let's get this merged here now that we have the ACKs and then we can batch-PR a few more changes here later (which are currently only PRed to @sipa's fork).

**Pull request merged**
