### PR TITLE
Bip122 - Creation of "ScaleNet"

### PR DESCRIPTION
**Pull request by priestc**

### CODE REVIEW

**Comment by btcdrak** [comment]
Was this BIP number assigned by @gmaxwell ?

**Comment by gmaxwell** [comment]
It certainly was not.

**Comment by btcdrak** [comment]
@gmaxwell Can I suggest editing the BIP subject line so Google doesnt index this.

**Comment by priestc** [comment]
How can I reformat this pull request so that it doesn't get deleted?

Do either of you have anything to say about the actual contents of the BIP?

**Comment by fanquake** [comment]
@priestc Start by reading through https://github.com/bitcoin/bips/blob/master/bip-0001.mediawiki#bip-work-flow

**Comment by btcdrak** [comment]
@priestc Your BIP should be named `bip-priestc-scalenet` until it is assigned a BIP number. You cannot self assign numbers, I see you have continued to use your self assignment and published elsewhere. Please change it.

**Pull request closed without merging**
