### PR TITLE
update Joinmarket BIP78 status

### PR DESCRIPTION
**Pull request by AdamISZ**
See https://github.com/JoinMarket-Org/joinmarket-clientserver/releases/tag/v0.7.1

### CODE REVIEW

**Review by benthecarman — APPROVED** [review]

**Comment by michaelfolkson** [comment]
ACK. This needs to be ACKed by the BIP author before it can be merged.

@NicolasDorier can you ACK this and then Luke can merge it? Thanks

**Comment by AdamISZ** [comment]
@NicolasDorier ping.

**Comment by AdamISZ** [comment]
I guess there's no point pinging @NicolasDorier again? This is still not done but Joinmarket has had full sending and receiving report for months now.

**Review by kristapsk — APPROVED** [review]
ACK 1fbcd28584f6b295a1d8a735e265415c1b3eb7e8

**Comment by NicolasDorier** [comment]
ACK

**Pull request merged**
