### PR TITLE
BIP 8: Elaborate and clarify parameter selection

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Review by jonasnick — COMMENTED** [review]
ACK 72bf969a1719aefdbd1094378cfd0386e4e4e9

Clearly better wording than before. In particular for `startheight` "a majority of economic activity is expected to have upgraded" is provides way better guidance than "reasonable number of full nodes".

**Review by darosior — APPROVED** [review]
ACK 72bf969a1719aefdbd1094378cfd0386e4e4e9bc

**Comment by darosior** [comment]
Note that you also have "recommended a year" in the Motivation section that in the spirit of these changes should imo be removed.

**Comment by ajtowns** [comment]
Post-merge ACK

**Pull request merged**
