### PR TITLE
Update bip-0037.mediawiki

### PR DESCRIPTION
**Pull request by kazute**
Spelling correction

### CODE REVIEW

**Comment by MarcoFalke** [comment]
The previous text is correct. Can be closed 

@kallewoof @luke-jr

**Comment by kallewoof** [comment]
@kazute 

> This BIP adds new support to the peer-to-peer protocol that allows peers to reduce the amount of transaction data they are [being] sent [from their peers].

It is referring to incoming data, not outgoing. Does that make sense to you?

**Comment by kazute** [comment]
Ahh yes I see now, sorry.

**Comment by kallewoof** [comment]
No need to apologize! :) I'm closing this then.

**Pull request closed without merging**
