### PR TITLE
BIP 0001: Change BIP editor to Luke Dashjr

### PR DESCRIPTION
**Pull request by luke-jr**
@gmaxwell asked that I take over BIP number assignments

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK

**Comment by MarcoFalke** [comment]
ACK

**Comment by harding** [comment]
ACK

**Comment by afk11** [comment]
ACK

**Comment by btcdrak** [comment]
ACK

**Comment by CodeShark** [comment]
ACK

**Comment by jmcorgan** [comment]
ACK

**Comment by wtogami** [comment]
ACK

**Comment by jl2012** [comment]
ACK

**Comment by petertodd** [comment]
ACK

**Comment by NicolasDorier** [comment]
ACK

**Comment by jonasschnelli** [comment]
Would be nice to get a ACK from @gmaxwell

**Comment by laanwj** [comment]
ACK

**Comment by laanwj** [comment]
But yes agree with @jonasschnelli, it looks better if @gmaxwell ACKs this too.

**Comment by gmaxwell** [comment]
I asked Luke to do this.

**Comment by greenaddress** [comment]
ACK

**Comment by fanquake** [comment]
ACK

**Comment by ducdigital** [comment]
ACK. Let luke-jr helps Bitcoin Core become
nirvana

**Pull request merged**
