### PR TITLE
Final BIP-0146 (Dealing with signature encoding malleability)

### PR DESCRIPTION
**Pull request by ysangkok**
The linked Bitcoin Core PR has been merged.

### CODE REVIEW

**Comment by ysangkok** [comment]
@jl2012 could you ack this?

**Comment by ysangkok** [comment]
since Lau is not replying, @sipa, would you be willing to ack this?

**Comment by sipa** [comment]
I think this should be marked Withdrawn instead. BIP146 isn't active on the network, and I don't think anyone is pursuing that anymore. The linked PR only implements it as a policy.

**Comment by luke-jr** [comment]
Closed via fd02fa4

**Pull request closed without merging**
