### PR TITLE
update bip0129 to reduce ambiguity

### PR DESCRIPTION
**Pull request by instagibbs**
I read it as "both types accepted" and couldn't find the definition of the signature format for non-p2pkh scripts, leading me to reread this section again after reading the BIP322. I think this is clearer, and if I'm wrong, it definitely needs a boost.

### CODE REVIEW

**Comment by luke-jr** [comment]
@hugohn

**Comment by hugohn** [comment]
Oops sorry I missed this. Thanks @luke-jr !

@instagibbs The idea was that I wanted to make BIP-0129 future-proof. Non-legacy BIP-0322 signatures would be ideal because those signatures actually commit to the XPUBs listed in the BSMS file. When BIP-0322 is ready we could just switch to the new signature type without having to update BIP-0129. But yeah BIP-0322 is still incomplete at the moment.

**Comment by murchandamus** [comment]
@hugohn, @instagibbs: Could you perhaps clarify the status of this PR?

**Comment by instagibbs** [comment]
I don't remember this :)

**Comment by murchandamus** [comment]
I suppose that is meant to mean that you no longer seek to get this merged?

Will close after 2024-05-10 unless I hear otherwise.

**Pull request closed without merging**
