### PR TITLE
Add a sentence explaining a risk with unsecure money receivers.

### PR DESCRIPTION
**Pull request by alokmenghrajani**

### CODE REVIEW

**Comment by luke-jr** [comment]
@sipa

**Comment by schildbach** [comment]
Actually three Java impls exist: bitcoinj is missing.

**Comment by alokmenghrajani** [comment]
re: bitcoinj, I (or anyone else) can add that in another PR.

**Comment by alokmenghrajani** [comment]
friendly ping

**Comment by nym-zone** [comment]
NACK:

>+Obviously, if someone illegally obtains access to the webserver, they can steal money by diverting future transactions to their own address.

Too obviously!  Obviously also, in this scenario, the intruder could steal credit card info, reduce the prices of all products to zero, insert Javascript malware into every page, replace the homepage with an [offensive “shock” image](https://upload.wikimedia.org/wikipedia/commons/thumb/a/ab/The_Global_Financial_Context_James_Dimon_%28cropped%29.jpg/545px-The_Global_Financial_Context_James_Dimon_%28cropped%29.jpg), or `rm -rf /` the whole server.

Sadly, the BIP 32 standard omits specification of magical means to stop the hax0r who pwned your server from replacing your Bitcoin addresses with his Bitcoin addresses.  `NOTABUG`.

So, yes, an intruder who takes control of a server can control the server and its outputs.  This is not a BIP 32-specific or Bitcoin-specific issue.  To explain such an elementary general fact in the standard would make the standard look dumb, and insult the intelligence of the reader.

**Pull request closed without merging**
