### PR TITLE
Remove duplication BIP69

### PR DESCRIPTION
**Pull request by azuchi**
The sentences in the motivation section of BIP69 are duplicated. So I deleted it.

### CODE REVIEW

**Comment by luke-jr** [comment]
@dcousens

**Comment by kristovatlas** [comment]
Hi @azuchi, can you clearly state which parts of the BIP you believe already contain the details you're proposing to remove?

**Comment by UdjinM6** [comment]
@kristovatlas 5 lines above are the same as removed ones. Introduced in https://github.com/bitcoin/bips/commit/d9acdcb6b12cd52424e8fec7cae89eef6bafcad9#diff-381a94c2f21517536d4ffb2a3a35437aR28

**Comment by kristovatlas** [comment]
Oops, good catch. ACK

**Comment by luke-jr** [comment]
(Oops, tagged the wrong person. Sorry.)

**Comment by dcousens** [comment]
Nice catch @azuchi

**Pull request merged**
