### PR TITLE
Finalize BIP-47

### PR DESCRIPTION
**Pull request by justusranvier**

### CODE REVIEW

**Comment by Priroch1979** [comment]
os: linux
language: generic
script:
    - scripts/link-format-chk.sh
    - scripts/buildtable.pl >/tmp/table.mediawiki || exit 1
    - diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' >/tmp/after.diff || true
    - if git checkout HEAD^ && scripts/buildtable.pl >/tmp/table.mediawiki 2>/dev/null; then diff README.mediawiki /tmp/table.mediawiki | grep '^[<>] |' >/tmp/before.diff || true; newdiff=$(diff -s /tmp/before.diff /tmp/after.diff -u | grep '^+'); if [ -n "$newdiff" ]; then echo "$newdiff"; exit 1; fi; else echo 'Cannot build previous commit table for comparison'; fi

**Comment by prayank23** [comment]
Concept ACK 

Status should be changed to `final` from `draft`

However I am not sure about the things added in https://github.com/bitcoin/bips/pull/1068/commits/bc069fa050fb9816746c9e13b34d9d13a7d89562 and the reasons for maintaining v3 in a separate repository:

> future developments of the reusable payment codes specification will not be distributed via the BIP process.

**Comment by gmaxwell** [comment]
This seems fine to me, including the redirection.

**Comment by murchandamus** [comment]
Since BIP47 is implemented by at least three software projects and this is a modification of the BIP author of his own BIP, this seems ready to merge to me.

**Pull request merged**
