### PR TITLE
Update bip-0148.mediawiki

### PR DESCRIPTION
**Pull request by jeffersoncarpenter**
There is no need to increase the block size.

### CODE REVIEW

**Comment by luke-jr** [comment]
@shaolinfry 

@jeffersoncarpenter Note this doesn't say it's needed, just that Segwit does it - which is true.

**Comment by shaolinfry** [comment]
Segwit is a blocksize increase.

**Comment by MickSHunt** [comment]
shaolinfry. the fixes are only for those using segwit keys. 
where as everyone else is still stuck in the 1mb base block and still able to malleate/quadratic spam and do the other things.
many people wrongly think that just activating segwit fixes all the stuff instantly for everyone.
it needs clarification that its not the activation of the block structure that matters, but who is using segwit keys

**Comment by afk11** [comment]
MickSHunt: BIP148 is an activation mechanism, it's not necessary to detail segwit's semantics here.

**Comment by MickSHunt** [comment]
but for people to know what they are flagging for. its best they know what they will get if it does activate

**Comment by shaolinfry** [comment]
@MickSHunt Segwit is a blocksize increase. @luke-jr please close this pull request.

**Comment by jeffersoncarpenter** [comment]
Okay, sounds good.  This is just how segwit is defined.

**Pull request closed without merging**
