### PR TITLE
typo: correct mispelling

### PR DESCRIPTION
**Pull request by alexbosworth**

### CODE REVIEW

**Comment by kallewoof** [comment]
I think you meant "misspelling" in the commit message. ;) (Or am I being whoooshed?)

**Review by barrybecker4 — APPROVED** [review]
Looks correct to me 👍

**Comment by michaelfolkson** [comment]
This is waiting on an update to the commit message? Also needs an ACK from @achow101.

**Comment by achow101** [comment]
ACK 96bcfef0505911634118eec1d63bb5646c9e2351

**Pull request merged**
