### PR TITLE
added 'btc_hd_wallet' amongst implementations in bip32, bip39, bip85

### PR DESCRIPTION
**Pull request by scgbckbone**
I would like to add my HD (paper) wallet implementation to BIP{32,39,85}. It is written as a follow up to reading @jimmysong great book - Programming Bitcoin. 

I had some issues trying to figure out what is going on just by looking on some other python implementations so I decided to write my own as a part of learning process. It should be easy to read and has a heavy load of unit tests. I hope it will help some novice bitcoiners to make their learning curve less steep.

### CODE REVIEW

**Comment by spongeeluv** [comment]
Be careful when you Bip 38 your private key. Only send..and try a little crypto currency to make sure you can get your funds. Always remember when purchasing bitcoin from Paxful.com..localbits etc... any platform you purchase cryptocurrencys from..withdraw your bitcoin to a wallet..tresor/paper...or even another computer off line.  Remember you purchased the bitcoin..but it is not in your possession..its on the market platform. forget your pass code  when Bip 38-ing and no brute force can help you. Once you Bip the private key..the long code or private key starts with a number 6 now...and remember you are relieing on address.org to encrypt the private key to use. I pErsonally have done this with £50.00 GBP..I HAVE THE  6P..CODE BUT I FORGOT THE PARA FASE

**Comment by luke-jr** [comment]
BIP 32 needs ACK from @sipa
BIP 39 needs ACK from one of @slush0  @prusnak  @voisine  @ebfull 
BIP 85 needs ACK from @ethankosakovsky

**Comment by prusnak** [comment]
BIP39 ACK

**Comment by ethankosakovsky** [comment]
BIP85 ACK

**Comment by sipa** [comment]
ACK for BIP32, because I don't want to hold this up.

However, I think at this point we should just remove the list of implementations from BIP32 - it's implemented almost universally in bitcoin wallet software, and this list here gives the incorrect impression of it being curated/recommended as a reference.

**Comment by reza1367777** [comment]
[]()reza1367777

**Pull request merged**
