### PR TITLE
docs: fix spelling

### PR DESCRIPTION
**Pull request by jbampton**
Another lot of spelling fixes and this has 53 additions and some that are not in the other PRs

The other two PRs for typo fixes only have 28 and 21 additions.

refs #579 
refs #675

### CODE REVIEW

**Review by dr-orlovsky — APPROVED** [review]
Confirm that PR contains only valid spelling changes into single words - and nothing else. Not sure whether in this case we need explicit ACK by authors of all those BIPs – probably multiple ACKs from independent ppl will do the job better. What do you think, @kallewoof and @luke-jr?

**Comment by kallewoof** [comment]
I think each PR should address a specific BIP and be approved by their respective authors.

**Comment by michaelfolkson** [comment]
> I think each PR should address a specific BIP and be approved by their respective authors.

I think these bulk spelling fix PRs across BIPs will need to be discouraged and eventually closed then. @luke-jr has also struggled to get BIP authors to care about minor spelling fixes. Thanks for the PR @jbampton but getting all the BIP champion(s) to ACK all the changes in a PR like this just isn't feasible.

**Comment by kallewoof** [comment]
> @dr-orlovsky It would be nice if BIP editors could just merge spelling changes, but unfortunately the current process requires each author to ACK.

We should address this as part of the revised next process, IMO.

**Review by 525411 — APPROVED** [review]

**Comment by Yuttana12wr** [comment]
0958275937

(นายยุทธณา สาระบูรณ์)

ในวันที่ ส. 22 ม.ค. 2022 13:07 525411 ***@***.***> เขียนว่า:

**Review by murchandamus — COMMENTED** [review]
All of the changes in this PR fix only typos within a word across multiple BIPs, they do not change the meaning of any BIP.

ACK 583e103ce467a31790ca299f97dc94c569ad01ae

**Comment by murchandamus** [comment]
I‘ve fixed the merge conflicts with BIP174 and BIP330 (where the passages in which the typo appeared had both been amended independently).

**Pull request merged**
