### PR TITLE
Promote Accepted->Final BIPs 11, 14, 21, 22, 23, 31, 32, 34, 35, 37, 65

### PR DESCRIPTION
**Pull request by luke-jr**
These seem to meet the criteria for Final, and are already Accepted status.

### CODE REVIEW

**Comment by dcousens** [comment]
ACK

**Comment by MarcoFalke** [comment]
Looks good. Needs rebase.

**Comment by luke-jr** [comment]
(Not going to rebase.)

**Comment by MarcoFalke** [comment]
(Oh, right. You are doing it with the merge.)

**Pull request merged**
