### PR TITLE
[BIP 44] Remove 21 Machine Wallet

### PR DESCRIPTION
**Pull request by torkelrogstad**
Link is broken, gives 404.

### CODE REVIEW

**Comment by luke-jr** [comment]
@prusnak @slush0

**Comment by prusnak** [comment]
IMHO Let's remove the whole section. There are thousands of wallets which use this standard.

**Comment by luke-jr** [comment]
@torkelrogstad Can you make the requested change?

**Comment by torkelrogstad** [comment]
Removed the section.

ping @luke-jr

**Pull request merged**
