### PR TITLE
Add implementation to bip-0069.mediawiki

### PR DESCRIPTION
**Pull request by DeftNerd**
Added the BitWasp BIP0069 implementation to the list of implementations

### CODE REVIEW

**Comment by luke-jr** [comment]
@kristovatlas

**Comment by kristovatlas** [comment]
@luke-jr: is it inappropriate to ACK this without first verifying that the implementation works correctly?

**Comment by luke-jr** [comment]
IMO probably, but I'm not sure the trend agrees with me.

**Comment by afk11** [comment]
It passes tests taken from bitcoin-js, and a couple of others too.

**Comment by jonathancross** [comment]
Friendly ping @kristovatlas

**Comment by murchandamus** [comment]
Given that this PR went without response from the BIP author for over six years, it seems that the author is not interested in adopting this change into the BIP document. Please feel free to request reopening, if I misinterpreted that @kristovatlas.

**Pull request closed without merging**
