### PR TITLE
Add BIP109 to BIP9 Deployments

### PR DESCRIPTION
**Pull request by chriswheeler**

### CODE REVIEW

**Comment by gmaxwell** [comment]
This is incorrect. BIP109 proscribes its own activation mechanism which is different from BIP9-- it uses the old IsSuperMajority rolling test.

**Comment by chriswheeler** [comment]
The implementation is based on an earlier version of BIP9 - but still I think it would be useful to show somewhere since its using one of the available bits, and is being actively mined on main net.

Could we add a note, or column to the table to convey this? Or a separate table for deployments which are not fully compatible with the current BIP9?

**Comment by luke-jr** [comment]
BIP9 has never been about more than softforks, and BIP 109 is not that.

Another table with potential conflicts might be useful, but nothing more IMO.

**Comment by luke-jr** [comment]
Interpreting @gmaxwell 's comment and lack of revisions here as a NACK; closing. Ping me if someone wants it reopened.

**Pull request closed without merging**
