### PR TITLE
typo: BIP [380-385]

### PR DESCRIPTION
**Pull request by jaonoctus**
Minor touch ups in the descriptors BIPs

### CODE REVIEW

**Review by MiguelMedeiros — APPROVED** [review]
Good catch, thanks!

**Comment by luke-jr** [comment]
@sipa @achow101

**Comment by achow101** [comment]
ACK 7007dbac006b8979c352f336039a47ffe32671c5

**Comment by MarcoFalke** [comment]
@luke-jr @kallewoof

**Comment by Ogloc419** [comment]
Unsubscribe

**Comment by michaelfolkson** [comment]
ACK 7007dbac006b8979c352f336039a47ffe32671c5 

(and more relevantly ACKed by a BIP author - @achow101)

**Pull request merged**
