### PR TITLE
BIP39: Clarify necessity for ideographic spaces.

### PR DESCRIPTION
**Pull request by bip39JP**
I left it unclear / open to interpretation on whether to use ideographic
spaces, but realized that without being specific on its necessity,
developers may implement something that would cause trouble with the
Japanese user. (two words looking like one word, or phrase verification
failing because it can't handle ideographic spaces, etc.)

Hopefully, this will clear up any mis-understandings.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I don't know if it is of any help in your debate. 
But what I ended up doing in NBitcoin is the following :

For normalization, I do nothing different between ideographic or ascii space. I just pass what the user pass as-is. (It works fine because ideographic is transformed into ascii during the normalization)
Thanks to that I am confident that it will not expose to any lost of fund for the user.

The only problem is when I need to split the words to extract the indices of the mnemonic.
What I ended up doing is adding a property called Wordlist.Space where the space is ideographic for Japanese wordlist and ASCII for other.
When I split the list, I split by using both : the ASCII space + the wordlist space, and remove empty strings.

With my solution, the user is not forced to use ideographic space for Japanese, and even if he does, the generated seed will be the same anyway.

**Comment by Thashiznets** [comment]
@NicolasDorier You should normalise the the Mnemonic when it is input by the user!!! The reason for this I believe was to allow for reinputting the mnemonic with a keyboard that may not have accented character sets etc. What you are doing I think is dangerous. Any user input needs to be normalised!!!!!

**Comment by dabura667** [comment]
@Thashiznets I don't think @NicolasDorier is doing anything bad or dangerous.

> For normalization, I do nothing different between ideographic or ascii space. I just pass what the user pass as-is. (It works fine because ideographic is transformed into ascii during the normalization)
Thanks to that I am confident that it will not expose to any lost of fund for the user.

So he says for seed generation (which is what matters, really) he just normalizes, and due to ideographic turns into ASCII after NFKD normalization, this is correct.

> When I split the list, I split by using both : the ASCII space + the wordlist space, and remove empty strings.
> Also, I split BEFORE the normalization. In fact my Mnemonic class do not store the normalized version of the mnemonic at all, I store exactly what the user passed. I normalize only for the seed generation process.

I think he is saying that:

1. User inputs string
2. He tries to split the string using both ASCII and the wordlist space
3. He figures out which one worked (actually results in an array of proper length)
4. He stores the array in the Mnemonic class as an array of words.
5. However, the string that gets normalized and sent to PBFKD2 is the original string that the user input as is.

@NicolasDorier Am I right? Also, subsequent generations of seed will draw the mnemonic phrase and join them with wordlist.space, then normalize and PBFKD2?

It doesn't seem dangerous, but I could see where someone trying to mimic that method might be more prone to coding mistakes.

**Comment by Thashiznets** [comment]
@dabura667 @nicolasdorier ah yes appologies guys, I missed the part where it states that nicolas is actually normalising before seed generation, that is fine. My error.

**Comment by NicolasDorier** [comment]
@dabura667 you are right. I don't use the array of words internally after splitting, I expose that just so UI developers can show it nicely to the user.

**Comment by andre-amorim** [comment]
HI Nicolas,
Please I don't want to cause any cognitive breakdown, and to be honest I
don't know if is the right time to ask about it.
But,
Do you intent, in the near future ... to refactoring crypto primitive "Ring
Signature" code ( like Bytecoin schema ?)
Thanks
Kind Regards,
AA

:.  Andre Amorim      .:

Key-ID:

A70B444E

Fingerprint:

FAAD3B6556A8877B938EAB2FC05E2CB0A70B444E

**Comment by NicolasDorier** [comment]
@andre-amorim I think this would be better to talk about that in [NBitcoin page] (https://github.com/NicolasDorier/NBitcoin/issues), I do not know what a Ring Signature. I am not a cryptographer, so if you have time to explain why it would help bitcoin and point out some link so I understand the why, what and how, I may implement it.

**Comment by Thashiznets** [comment]
@nicolasdorier @andre-amorim agreed, tag me in any discussions as well as I have not heard of such thing either but keen to learn.

**Comment by dabura667** [comment]
Ping authors @voisine @prusnak

**Comment by voisine** [comment]
I don't see any reason why bip39 couldn't be used to encode a seed for deriving ring signature private keys.

**Comment by dabura667** [comment]
@voisine Sorry they got off topic.

The topic of the pull request is specifying that Japanese phrases should be split with ideographic spaces to prevent users from mistaking words that might appear to run together and make different words.

**Comment by voisine** [comment]
I think it's useful to explain ideographic space handling to help non-japanese developers. I only learned of it when testing to see how they are handled by NFKD normalization.

If it's the case that the reference implementation fails to handle japanese test cases, then we should correct the reference implementation concurrently with including the test cases.

There are no spaces between characters in the same word in the japanese word list, so you can normalize the phrase first, then separate words on ASCII space, and use the words to index into the wordlist to calculate the checksum. Is this correct?

**Comment by Thashiznets** [comment]
@voisine Correct, so programmatically the reference code would just generate a mnemonic with an ASCII space between each Japanese word. And this is why I had an issue with the test vectors containing ideographic spaces instead of ASCII, because the mnemonic generated by the reference code was ASCII spaced, so I was failing against the Jap test data unless I explicitly added ideographic space after building the mnemonic. I didn't like this, however it has been decided (and I believe popped into the reference code) that any mnemonic that comes out that is Japanese comes out with ideographic spaces and I have followed suit in my .NET implementation.

**Comment by dabura667** [comment]
> I think it's useful to explain ideographic space handling to help non-japanese developers. I only learned of it when testing to see how they are handled by NFKD normalization.
>
> If it's the case that the reference implementation fails to handle japanese test cases, then we should correct the reference implementation concurrently with including the test cases.

Trezor Python Mnemonic supports Japanese and ideographic spaces now.

> There are no spaces between characters in the same word in the japanese word list, so you can normalize the phrase first, then separate words on ASCII space, and use the words to index into the wordlist to calculate the checksum. Is this correct?

This is incorrect, as most interpreters will view them as different strings and will not be able to find the word in the list. (non-normalized string != normalized string on a per-byte basis... though depending on the interpreter perhaps it will accommodate for normalized strings when comparing... but I would rather not rely on that.)

Example:
れきだい
UTF8: e3828c e3818d e381a0 e38184 (twelve bytes for 4 characters)
Normalized: e3828c e3818d e3819f e38299 e38184 (notice how byte-wise it adds a new character, this is because it separates the た and the ゛ but when next to each other it would be shown as だ

**Comment by Thashiznets** [comment]
@dabura667 All words on the wordlist are already Normalised as per the spec to right? So unless the normalisation process created a space between characters of words there should be no spaces between characters and I believe that is what @voisine is asking.

**Comment by voisine** [comment]
If I understand @dabura667 correctly, then the japanese word list itself contains non-NFKD normalized words? If so, that should be corrected. Since key derivation involves normalization, then we can normalize the word list without affecting already generated wallets.

**Comment by voisine** [comment]
@bip39JP excellent, BIP39 actually specifies that wordlists must be NFKD normalized to begin with. I will try to remember to verify this is the case when future wordlists are submitted. Thanks for including a fix.

**Comment by Thashiznets** [comment]
@bip39JP I'm assuming the test vectors remain the same as we should be normalising before generating the seed anyway correct?

**Comment by dabura667** [comment]
@voisine @Thashiznets I have normalized the actual words on the wordlist now. (as well as the test vectors on my other repo) All I need to do now is make a pull request with python-mnemonic.

This should not cause problems, though, as all implementations should normalize the phrases before hashing, not to mention the only places using the Japanese list currently are my bip32jp site and Electrum (which is no longer BIP39 anyways, and has decided to normalize >> then remove all spaces for CJK languages... to I think I'll leave Electrum as is.)

**Comment by Thashiznets** [comment]
@dabura667 I fear that github is displaying the wordlist the same either normalised or not, they certainly look the same I mean I don't know if copy and pasting from either/or results in different actual bytes between them, so it may be worth while forcing devs to normalise the list themselves rather than copy and paste? I believe I did this when putting the list in my implementation. As you say tho, given we normalise pre seed generation anyway I don't think anything is going to break as a result.

**Comment by voisine** [comment]
@Thashiznets normalization should result in identical looking results in most cases (ideographic spaces appear to be the odd exception)

ACK, this is important to get in.

**Comment by dabura667** [comment]
https://github.com/trezor/python-mnemonic/pull/25/files

Yes. If you view it in a browser it shows normalized text as the same as it's non-normalized partner. (or at least in the case of hiragana + dakuten it does)

I believe if you copy it though... it should copy the normalized bytes...

Try opening the javascript console in your browser, pasting the below bytes, then overwriting the "pastehere" with the normalized (post-fix) then see the results, then try again but this time copy paste the old words. see if the bytes that come out differ.

```javascript
var nstring = "pastehere";
var bytes = [];
for (var i = 0; i < nstring.length; ++i) {
  bytes.push(nstring.charCodeAt(i));
}
bytes;
```

**Comment by dabura667** [comment]
@laanwj @prusnak Notice: Aaron gave an ACK.

**Comment by Thashiznets** [comment]
@dabura667 Right you are, I see Array [ 12354, 12362, 12382, 12425 ] and then the extra byte apparent in the normalised one [ 12354, 12362, 12381, 12441, 12425 ] using あおぞら

**Comment by prusnak** [comment]
Although I don't have a strong opinion I vote ACK. I don't think that using non-English wordlist is a good idea in general, but if there is a demand for this, let's do it the correct way.

**Comment by gary-rowe** [comment]
Although MultiBit HD does not support Japanese wordlists yet we will very likely introduce them once they arrive in bitcoinj. We *may* offer a pull request for this at an undefined point in the future. Speaking personally I feel that people are more likely to use a word list in their native language so this will help with Bitcoin adoption globally.

ACK on this clarification from MultiBit HD.

**Comment by simcity4242** [comment]
The ideographic space issue confused me for test vectors. Is it correct to say only Japanese uses this?

**Comment by NicolasDorier** [comment]
@simcity4242 in my code, I have the type WordList with all the words, but I also pass the "space" character to it, so it can adapt to future language.

**Comment by Thashiznets** [comment]
@simcity4242 so far JP is the only word list that has to factor in ideographic spaces yes, but if in doubt just use ASCII spaces it's only really an issue if you want to display the mnemonic in a GUI, so output the mnemonic to display with wide spaces.

**Comment by voisine** [comment]
The issue is ideographic spaces being used by default when a user inputs the phrase. The wallet has to anticipate and correctly handle it.

**Comment by Thashiznets** [comment]
Negative @voisine the normalization process converts ideographic to ASCII space so it doesn't matter to the wallet which one is input. Only display of mnemonic to user in GUI is issue so again I'd recommend OS localization to detect correct spaces, user using JP device, you know to make spaces ideographic.

**Comment by voisine** [comment]
as a non-Japanese developer, I was initially unaware of ideographic spaces and had to make code changes to account for them during input, prior to normalization, so I found the notes useful.

**Comment by Thashiznets** [comment]
What code changes did you have to make? Were you splitting the string by spaces or something?

**Comment by voisine** [comment]
Initially

**Comment by simcity4242** [comment]
@Thashiznets The trouble is, [the JP test vectors](https://github.com/simcity4242/pybitcointools/blob/master/test_JP_BIP39.json#L4) use ideographic spaces, so if you're unit testing the `entropy_to_mnemonic` function, you will get a fail otherwise. Perhaps this is specific to Python, but FWIW I'm importing the [JSON file](https://github.com/simcity4242/pybitcointools/blob/master/test_JP_BIP39.json)

**Comment by Thashiznets** [comment]
@simcity4242 what specifically is the problem? You do realise a mnemonic with ideographic or normal space produces identical seed bytes right?

**Comment by dabura667** [comment]
@simcity4242 https://github.com/trezor/python-mnemonic/blob/master/mnemonic/mnemonic.py#L135

Reference implementation joins using ideographic space. Works with test vectors fine.

**Comment by simcity4242** [comment]
@Thashiznets mate, I do realise that. It's the `entropy_to_MNEMONIC` I am referring to. Seed generation is not what confused me. 

@dabura667 If the unit test uses code which was written prior to [this 3 month old commit](https://github.com/bitcoin/bips/commit/f0dd2d58ab920647a8e288c4ab93129686b20be2#diff-77888683310fe50a2218bbb62ec5cd68), as I did, it's based on very ambiguous recommendations, eg:

1. *I left it unclear / open to interpretation on whether to use ideograpic spaces, but realized that without being specific on its necessity, developers may implement something that would cause trouble with the
Japanese user. (two words looking like one word, or phrase verification failing because it can't handle ideographic spaces, etc.)* 
2. [Note the https://github.com/bitcoin/bips/commit/f0dd2d58ab920647a8e288c4ab93129686b20be2#diff-77888683310fe50a2218bbb62ec5cd68R13

I'm not saying that the test vectors fail when using `\u3000` or `\xe3\x80\8x0` as seperators; I'm just saying the it was confusing to me. You're right, re reference implementation code; I just checked and my local copy was 2-3 versions old.

Anyway, thanks everyone because [I got it working :D](https://github.com/simcity4242/pybitcointools/blob/master/test_bip39.py)

**Comment by fczuardi** [comment]
What is the process to include a new wordlist for a different language? Create it and make a pull request? Discuss it on a list first? If that's the case, which list?

**Comment by fczuardi** [comment]
ok, found it https://lists.sourceforge.net/lists/listinfo/bitcoin-development

**Comment by manobra** [comment]
isso ajuda? https://www.youtube.com/watch?v=qT_Zqe_E_QE

**Comment by andre-amorim** [comment]
eu to lendo sobre o sha3 ( https://www.youtube.com/watch?v=opT6pIfyGUs)
 ... nao importa o que eu diga vao dizer que e' OFF TOPIC que coisa mais
previsivel que isso ?

**Comment by harrycheng8** [comment]
#1143

**Pull request merged**
