### PR TITLE
Withdraw BIP151

### PR DESCRIPTION
**Pull request by jonasschnelli**
The BIP151 proposal does have some practical downsides and thus a new proposal has been made (https://gist.github.com/jonasschnelli/c530ea8421b8d0e80c51486325587c52)

### CODE REVIEW

**Comment by luke-jr** [comment]
BIP 151 never left Draft status, so why not just revise it?

**Comment by sipa** [comment]
Given that BIP151 already has an assigned number, I think it would be inadvisable to keep using the same number for a substantially different design.

**Comment by luke-jr** [comment]
Number assignment is not finalisation. Maybe if there was a production implementation of it, but as a mere draft, I don't see why. The new one is still "Peer-to-Peer Communication Encryption", no?

**Comment by jonasschnelli** [comment]
The main reason why this number/proposal should and probably cannot be re-used for a new, heavy incompatible proposal is, that implementations have been made (bcoin, armory). I don't think they are (no longer) in production but still,... the code is available.

**Comment by luke-jr** [comment]
I'm not really convinced, but not worth spending time arguing...

The README needs a style change, though: |- style="background-color: #ffcfcf"

**Comment by jonasschnelli** [comment]
> The README needs a style change, though: |- style="background-color: #ffcfcf"

Done.

**Comment by luke-jr** [comment]
... the style change is needed for BIP 151, not BIP 152 ;)

**Comment by jonasschnelli** [comment]
Fixed

**Pull request merged**
