### PR TITLE
add turkish wordlist

### PR DESCRIPTION
**Pull request by hknylcnsy**
1. Simple and common Turkish words.
2. Only words with 4-8 letters.
3. The first 4 letters are unique among all words.
4. The letters (â,î,û,ô) used in Turkish are considered equal to (a,e,u/ü,o/ö). (like: kâğıt-kağıt, sükût-sükut)
5. No complex verb forms.
6. No plural words.
7. No offensive/negative words.
8. No words with double vowels. (like: maalesef, şuur) 
9. No words to mingle. (like: adam-aday, alet-alev, surat-suret)
10. No words with repeated syllables. (like: leblebi, baba)
11. No infinitive words. (like: yapmak, gülmek)

### CODE REVIEW

**Comment by izzetemredemir** [comment]
+1 Well prepared

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Review by zinderud — CHANGES_REQUESTED** [review]
https://github.com/zinderud/scure-bip39 
 I changed the letters in some words in Turkish (ü,ğ,ş,ı,ö) to their English equivalents (u,g,s,i,o) to be compatible with the tests.

// Normalization replaces equivalent sequences of characters
// so that any two texts that are equivalent will be reduced
// to the same sequence of code points, called the normal form of the original text.

https://tonsky.me/blog/unicode/#why-is-a----

**Comment by zinderud** [comment]
https://github.com/zinderud/scure-bip39/blob/main/src/wordlists/turkish.ts

**Comment by murchandamus** [comment]
If BIP39 no longer accepts new wordlists, and such pull requests should instead be directed at the WLIPs repository, can we close this?

**Pull request closed without merging**
