### PR TITLE
179: Remove my email due to spam

### PR DESCRIPTION
**Pull request by MarcoFalke**
To reduce incoming spam

### CODE REVIEW

**Comment by katesalazar** [comment]
dang you got 1337

ACK aa452fa

plz squash

**Comment by MarcoFalke** [comment]
> plz squash

feel free to use the "Squash on merge" GitHub button

**Comment by michaelfolkson** [comment]
> Not refusing to merge, but I think we should figure out a better solution... :/

What's your concern @luke-jr? You want one of the other BIP co-authors to ACK removing Marco as a co-author or you want Marco to provide a different email address which he doesn't mind being spammed?

**Comment by luke-jr** [comment]
My main concern is that people won't write BIPs at all because of spam fears.

I'm not sure the fears are justified - this seems to be prompted by a single human-written mass email to all BIP authors, the first in nearly a decade of the BIP process.

But it's not my place to say Marco must tolerate it either - so some solution is desirable. Maybe we should find a way to mask emails, or allow BIPs without emails published somehow?

**Comment by kanzure** [comment]
> Not refusing to merge, but I think we should figure out a better solution... :/

Your post advocates a

( ) technical ( ) legislative ( ) market-based ( ) vigilante

approach to fighting spam. Your idea will not work. Here is why it won't work. (One or more of the following may apply to your particular idea, and it may have other flaws which used to vary from state to state before a bad federal law was passed.)

https://craphound.com/spamsolutions.txt

**Comment by katesalazar** [comment]
> My main concern is that people won't write BIPs at all because of spam
fears.

People will write BIPs if the cost of being spammed is worth the benefits
of the BIP.

**Comment by michaelfolkson** [comment]
Right, I'm not a BIP co-author nor a BIP maintainer but I'd be for merging this and then discussing afterwards what should be done in future if similar requests are made in future. Especially as this is just a draft informational BIP.

**Comment by MarcoFalke** [comment]
@kallewoof @luke-jr

**Pull request merged**
