### PR TITLE
Update bip-0049.mediawiki

### PR DESCRIPTION
**Pull request by torkelrogstad**
Fix broken internal link

### CODE REVIEW

**Comment by ysangkok** [comment]
Given that this proposal is in Draft status and hasn't evolved for the last three years, shouldn't it be marked Rejected?

**Comment by torkelrogstad** [comment]
I don't really have an opinion on that, I would just like to fix that typo:-)

**Comment by luke-jr** [comment]
@DanielWeigl

**Comment by clarkmoody** [comment]
> Given that this proposal is in Draft status and hasn't evolved for the last three years, shouldn't it be marked Rejected?

Similar to other proposals, BIP-49 is in production, albeit with modified version bytes (c.f. #762 ). Electrum and Trezor are probably the two largest wallets that implement this spec.

**Comment by luke-jr** [comment]
If @DanielWeigl is MIA, would someone like to take over this BIP?

**Comment by clarkmoody** [comment]
> If @DanielWeigl is MIA, would someone like to take over this BIP?

I can take it if needed to push things forward.

**Comment by DanielWeigl** [comment]
ACK

**Comment by DanielWeigl** [comment]
Ive also made a PR to set it to `active` here https://github.com/bitcoin/bips/pull/809

**Pull request merged**
