### PR TITLE
fixed minor typo in BIP 79

### PR DESCRIPTION
**Pull request by moneyball**
"assumptions" instead of "assumption"

### CODE REVIEW

**Comment by luke-jr** [comment]
@RHavar

**Comment by jonathancross** [comment]
@moneyball Please consider adding "BIP-79 : " or similar prefix to the PR title.

**Comment by RHavar** [comment]
Looks good!

**Comment by moneyball** [comment]
> @moneyball Please consider adding "BIP-79 : " or similar prefix to the PR title.

Hi @jonathancross, this PR merely adds an 's' to a word, so I don't think it should address other issues. I'd suggest opening a new issue or PR if something else needs to change.

**Comment by jonathancross** [comment]
> Hi @jonathancross, this PR merely adds an 's' to a word, so I don't think it should address other issues. I'd suggest opening a new issue or PR if something else needs to change.

I was saying you should change the *title* of this pull request so it might be more clear what it is. Not a comment about the content of the pull request or an addition.

**Pull request merged**
