### PR TITLE
BIP44: Added Coinomi to the list of supported wallets

### PR DESCRIPTION
**Pull request by GeorgeKimionis**

### CODE REVIEW

**Comment by luke-jr** [comment]
I wonder if maybe removing the "Compatible wallets" section might be a better idea. Lists like this don't seem to belong inside BIPs IMO.

**Comment by GeorgeKimionis** [comment]
@luke-jr I believe that these wallets serve as an excellent showcase for BIP44 which still is in `draft` status and not yet implemented by `Bitcoin Core`. If BIP44 was already part of the core implementation I would agree that the "Compatible wallets" section wouldn't really have a place inside this document as it would often be incomplete and difficult to maintain but also out of context.

**Comment by luke-jr** [comment]
@GeorgeKimionis Bitcoin Core's wallet is not really anything special - if more than a few wallets have adopted this BIP, its status should probably be progressed beyond Draft.

**Comment by laanwj** [comment]
I agree that a list of supported applications doesn't really belong in a standards document.
Having the list *somewhere* makes sense though, for people that are looking to implement it and looking for an example implementation.

**Comment by GeorgeKimionis** [comment]
@luke-jr even if it's not it would still be easily accessible by anyone who would want to get their hands dirty with a `Multi-Account Hierarchy for Deterministic Wallets` approach for their own solutions in which case the core implementation would serve as a great example, so if it's not for this document let's keep the list somewhere else, as @laanwj proposed.

**Comment by laanwj** [comment]
As no one seems to be working on moving this anywhere else, I'm fine with merging this. Needs rebase, though.

**Comment by laanwj** [comment]
Still needs rebase.

**Pull request closed without merging**
