### PR TITLE
BIP 158: fix mistyped tag

### PR DESCRIPTION
**Pull request by 4tochka**
mistyped tag rev changed to ref this was a reason of broken visible  symbols inside code tags below mistyped tag

### CODE REVIEW

**Comment by luke-jr** [comment]
@Roasbeef @aakselrod

**Comment by Roasbeef** [comment]
Unsubscribing from this as it looks to be more than a modification to BIP 158 (the tag or w/e) and rather an entirely new BIP.

**Comment by luke-jr** [comment]
I'll take that as a NACK...

**Comment by 4tochka** [comment]
I am sorry I forgot to switch branch after pull request.

**Pull request closed without merging**
