### PR TITLE
Spelling: resistance -> resistant

### PR DESCRIPTION
**Pull request by greglaun**
I believe it means to say that the Lamport signature is "quantum computing resistant".

### CODE REVIEW

**Comment by luke-jr** [comment]
@CodeShark @sipa @jl2012

**Comment by CodeShark** [comment]
small nit: Lamport signatures should be plural, so the sentence should read "Examples of new script system include Schnorr signatures which reduce the size of multisig transactions dramatically, Lamport signatures which are quantum computing resistant, and Merklized abstract syntax trees which allow very compact witness for conditional scripts with extreme complexity."

**Comment by greglaun** [comment]
@CodeShark I agree. I was trying not to be too fussy. I added another commit that makes the pluralization uniform and also corrects the spelling of Merkelization.

**Comment by murchandamus** [comment]
Since this PR has seen no activity since 2016, I interpret that there is not sufficient interest from the authors to merge this change to their BIP.

This PR proposes a minor improvement of the phrasing that seems consistent with the original text. I would be happy to merge either the version that @CodeShark proposed or the one that @greglaun suggested, if @CodeShark, @sipa, or @jl2012 indicated that they would like to proceed that way.

I am closing this PR for now, but please let me know if any of you would like to reopen it.

**Comment by murchandamus** [comment]
Oh. When I tried to reopen I got the error that "The repository that submitted this pull request has been deleted. I reopened a new PR in #1575.

**Comment by murchandamus** [comment]
Changes adopted via #1575.

**Pull request closed without merging**
