### PR TITLE
BIP 90: Buried deployments

### PR DESCRIPTION
**Pull request by sdaftuar**
I think this is ready to move forward, can this be assigned a BIP number?

### CODE REVIEW

**Comment by luke-jr** [comment]
Let's call this BIP 90.

It would be ideal if it had a dedicated Backwards Compatibility section and was explicit about being a hardfork.

**Comment by sipa** [comment]
It does explicitly mention `It is technically possible for this to be a non-backwards compatible change.`, which is true, though in Bitcoin Core at this point that is dependent on also removing checkpoints.

**Comment by luke-jr** [comment]
Indeed, it's not a barrier to merging because B.C. is being addressed in another section. I just thought it would still be nice to have an explicit section for this. :)

AFAIK Core doesn't enforce checkpoints strictly anymore?

**Comment by sdaftuar** [comment]
@luke-jr I felt the Considerations section addressed all the information that a Backwards Compatibility section would have; if I were to add one, I'm not sure what more to say.

As for using the term "hard fork" in this document -- I considered adding something like that, but rejected that idea because I think the term "hard fork" is not a universally well understood/defined term, and that it would be less clarifying to use that term than the language I've already included, which more explicitly describes the circumstances which lead to consensus split.  (FYI I double-checked that BIP 34 and BIP 65 make no mention of the terms "soft fork" or "hard fork", though BIP 66 does use the term "soft fork" without definition.)

This is an aside, but regarding checkpoints:
> though in Bitcoin Core at this point that is dependent on also removing checkpoints.

I don't believe this is the case for BIP 65 or BIP 66, which activated past the last Core-checkpointed block height.

> AFAIK Core doesn't enforce checkpoints strictly anymore?

There have been some tweaks to how checkpoints are used, but Core hasn't yet released a version that disable the effect of checkpoints locking in a particular chain, once the headers have been seen -- though I believe there's work underway to do so, potentially even for the next release.

**Comment by sdaftuar** [comment]
Updated with BIP number assignment and added to README.mediawiki.

**Comment by btcdrak** [comment]
ACK

**Comment by NicolasDorier** [comment]
if anybody have interest, I can rebase https://github.com/bitcoin/bitcoin/pull/8460 which formalize that better in code.

**Pull request merged**
