### PR TITLE
BIP 372: Pay-to-contract tweak fields for PSBT

### PR DESCRIPTION
**Pull request by dr-orlovsky**
A proposal was originally discussed in https://github.com/bitcoin/bips/pull/1239 and than on a mailing list https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2022-January/019761.html

### CODE REVIEW

**Comment by dr-orlovsky** [comment]
Asking @achow101 to review

**Comment by dr-orlovsky** [comment]
Kindly pining @achow101 to review. This is a stuff we briefly discussed with @apoelstra, basing also on his ideas, so his review is also highly appreciated.

**Comment by Yuttana12wr** [comment]
checking

**Comment by apoelstra** [comment]
concept ACK. I like this approach, it's narrow but general and clean. It could be used for hypothetical broken P2C schemes but I'm not too worried about that.

Thank you for the authorship but AFAIR this approach is not mine.

**Comment by luke-jr** [comment]
Assigned BIP number 372

**Comment by achow101** [comment]
Seems fine to me. I'm not particularly familiar with p2c constructions, so can't really pass further judgement on this topic.

**Comment by dr-orlovsky** [comment]
@luke-jr whom do you think we need to review this PR before getting it merged?

**Comment by Yuttana12wr** [comment]
16

(ยุทธณา สาระบูรณ์)

ในวันที่ ส. 30 ก.ค. 2022 18:26 Dr. Maxim Orlovsky ***@***.***>
เขียนว่า:

**Comment by kallewoof** [comment]
> @luke-jr whom do you think we need to review this PR before getting it merged?

The BIP was assigned number 372, so for starters edit the BIP to replace the "?" placeholders as appropriate. Also make sure to address the travis issues, if any.

**Comment by dr-orlovsky** [comment]
@kallewoof did as you asked for.

First, I have re-based on the current master since the master I was based before contained a CI failure, which was fixed in 66aed730432eedc1dadc5436d0e4dd7a6d3b5216

I also had to fix the CI script in https://github.com/bitcoin/bips/pull/1293/commits/2f57890cbe439839f7a53f69232d1433fd727db0  since my e-mail contains dashes, which were not allowed by CI before.

Finally I also created an entry in the README since it was required by the CI.

**Comment by kallewoof** [comment]
Please don't use @{username} in commit descriptions. It results in a lot of spammy notifications sent to that user. (Github should really do something about that.)

**Comment by dr-orlovsky** [comment]
@kallewoof ok, sorry, I didn't know

**Comment by kallewoof** [comment]
No biggie. Github's at fault here. But yeah, do avoid in the future :)

**Comment by dr-orlovsky** [comment]
@kallewoof any requirements what to do next with this PR in order to get the new BIP merged into the master?

**Comment by michaelfolkson** [comment]
> Thank you for the authorship but AFAIR this approach is not mine.

Apologies if I'm misunderstanding the context here but would you prefer to be listed in the acknowledgements rather than as a BIP co-author @apoelstra? Being listed as a co-author does seem to confer more perceived responsibility over the BIP than just being listed in the acknowledgements.

**Comment by apoelstra** [comment]
@michaelfolkson yes, I would prefer to be listed in the acknowledgements rather than as a co-author. This is not my BIP to maintain :)

**Comment by dr-orlovsky** [comment]
@michaelfolkson @apoelstra fixed

**Pull request merged**
