### PR TITLE
BIP 123: change "Accepted" to "Proposed" in initial classification table

### PR DESCRIPTION
**Pull request by ysangkok**
according to BIP 2

### CODE REVIEW

**Comment by luke-jr** [comment]
@CodeShark Not sure if you want to update this or leave it for historical reasons.

**Comment by ysangkok** [comment]
Why is this historical? It says "Status: Active".

**Comment by luke-jr** [comment]
>  ==Classification of existing BIPs==

**Comment by ysangkok** [comment]
Closing this because I think CodeShark isn't contributing to this repository any more, so there is no point in keeping it open if it can never proceed.

**Pull request closed without merging**
