### PR TITLE
Reject BIP-0064 (three years inactivity)

### PR DESCRIPTION
**Pull request by ysangkok**
Expiring according to BIP-0002.

### CODE REVIEW

**Comment by luke-jr** [comment]
This was in fact implemented by two pieces of software, so I guess it should be Final...

**Comment by ysangkok** [comment]
Do you want me to make a new PR for that change then? Or should I reuse this one?

**Comment by sipa** [comment]
PR title is wrong (it's changing BIP 64, not 63).

**Comment by ysangkok** [comment]
@sipa Thanks! Fixed. BIP-0063 isn't even assigned (according to the README).

**Comment by luke-jr** [comment]
We're going to hit another case of "Hearn is no longer working on Bitcoin, so won't approve the progression from Draft to Proposed. But nobody else wants to take over the BIP either." :/

**Pull request closed without merging**
