### PR TITLE
BIP 0174: bring back transparent background to figures

### PR DESCRIPTION
**Pull request by katesalazar**
tweaking tkiz arrows for luke-jr with <3

### CODE REVIEW

**Comment by katesalazar** [comment]
using white arrows with black borders should work sweetly
in dark themes and in white themes

**Comment by katesalazar** [comment]
this shit is not very straightforward...
I wonder how exactly did achow101 generate the svg pics.

If I knew that,
it's possible I could rerun this in some way the svg diff
volume is less shitty than in cdc629b66edce4951099e

but I think the SVG visual diff is very mostly OK tho

**Comment by murchandamus** [comment]
@achow101: This appears to modify your BIP, any chance you could review?

**Comment by achow101** [comment]
ACK 3248581928b5299525b32979c8a569ce9107fdfc

The new images look good in both light and dark mode.

>  I wonder how exactly did achow101 generate the svg pics.

I don't remember either. But the build script in here produces valid svgs, so I guess it's fine.

**Pull request merged**
