### PR TITLE
Polish wordlist for BIP0039

### PR DESCRIPTION
**Pull request by p2w34**
This is my proposition for a Polish word list.

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by p2w34** [comment]
Recently I also came up with the description how I did it:
https://github.com/p2w34/blog/blob/master/2019-03-25-polish-word-list-bip0039/polish-word-list-bip0039.md

**Comment by dabura667** [comment]
... BIP39 added wordlists are always ignored by all authors.

Can the authors come together on an auto-NACK agreement or something?

Ignoring them forever does not help anyone.

If you want I can maintain a separate wordlist repository similar to how SLIP-44 contains the BIP44 coin indices...

People who are born in countries that learn English at a young age do not understand how hard English is to non-european countries.

So many Japanese people gave up on holding their own keys because they can't transcribe English from a screen without writing a word wrong... But Copay supports Japanese wordlist and I have never heard a problem from anyone about it.

Refusing to support multiple languages is losing peoples' money.

**Comment by DonaldTsang** [comment]
Cross-reference https://github.com/bitcoin/bips/pull/493

**Comment by p2w34** [comment]
There is not much going on here - I've created this PR some time ago and I've been thinking about the problem of creating all the lists ever since. I think I might have come up with a good idea of how to do this, that is why I bootstrapped it in a separate repo: https://github.com/p2w34/wlips.
Yes, that means there will be a lot of work, including re-doing existing lists. Even the Polish one I have created myslelf. I spent a lot of time thinking about it and I do not really see another approach other than trying to kinda create all of the lists at once. That is why I would like to give it a go. In the upcoming days I am planning to create some useful Python scripts and the instruction how to create a word list for a particular language.

**Comment by luke-jr** [comment]
Could always add a new BIP for new wordlists (or perhaps a BIP for the separate WL repo?)

**Comment by p2w34** [comment]
> Could always add a new BIP for new wordlists (or perhaps a BIP for the separate WL repo?)

@luke-jr Could you please elaborate on that?

Personally, I am in favour of developing all lists in a separate repo. Not only they are loosely coupled with BTC (or basically any other cryptocurrency - I use my hardware wallet as a second factor and for SSH as well), but also I think BIPs repo would be unnecessarily loaded with PRs and all discussions about it.

**Comment by luke-jr** [comment]
I mean you could write a new BIP defining new word lists. Or even a new BIP defining an external repository for word lists.

**Comment by tevador** [comment]
The following words are already part of the Czech wordlist and must be replaced:

```
alkohol
ananas
astma
balkon
beton
bizon
blizna
bojkot
bufet
burza
butik
cedr
centrum
chata
chichot
chirurg
chmura
choroba
debata
deska
dioda
dokument
dolar
dolina
dostatek
drozd
dudek
dynamit
esej
eskorta
filozof
filtr
flirt
fosfor
geolog
groteska
harfa
hokej
horda
ikona
jantar
jarmark
jelito
jogurt
kabaret
kajuta
kaktus
kino
knot
komora
konkurs
kronika
kuna
laik
legenda
linoleum
logika
makrela
malina
metoda
metr
mimika
mnich
monarcha
most
mozaika
mulat
muzeum
neuron
odpad
osada
osika
osoba
ozdoba
patent
pedagog
petarda
pianista
pikle
piknik
pipeta
plakat
planeta
plomba
pokuta
pomoc
projekt
prorok
reklama
rekord
rekrut
ropucha
rotunda
rozkaz
rozum
ryba
sasanka
sekunda
skaut
smog
smutek
snob
socha
stopa
struna
suchar
tajga
tapeta
telefon
tenor
traktor
troska
tundra
zima
znak
```

**Comment by p2w34** [comment]
> The following words are already part of the Czech wordlist and must be replaced:
> 
> ```
> alkohol
> ananas
> zima
> znak
> ```

@tevador - I suppose your comment is based on the belief that there should be no common words among the lists. I think this is not really possible and I think quite the opposite. IMHO the lists should have as much in common as possible. Having this as the base idea I bootstrapped the repo mentioned already above (https://github.com/p2w34/wlips) and I encourage to contribute. Especially that the state of BIP0039 as it is written in the summary is: "Comments-Summary: Unanimously Discourage for implementation".

**Comment by luke-jr** [comment]
>I bootstrapped the repo mentioned already above (https://github.com/p2w34/wlips) 

I suggest a BIP (or modification to BIP 39) linking this.

> Especially that the state of BIP0039 as it is written in the summary is: "Comments-Summary: Unanimously Discourage for implementation".

You know you can always leave a comment of your own encouraging it, right?

**Comment by tevador** [comment]
@p2w34 It's not an explicitly stated rule, but most of the latin-alphabet wordlists follow it, e.g.

Spanish
> There are no words in common between the Spanish wordlist and any other language wordlist, therefore it is possible to detect the language with just one word.

Italian
> No words already used in other language mnemonic sets.

Czech
> No words already used in other language mnemonic sets

**Comment by p2w34** [comment]
@tevador  - I am aware of that nevertheless thank you for additional explanation.
@luke-jr - I was postponing linking https://github.com/p2w34/wlips, but I decided not to wait and I just created a PR. Thank you.

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Pull request closed without merging**
