### PR TITLE
BIP39: Dart implementation

### PR DESCRIPTION
**Pull request by ethicnology**

### CODE REVIEW

**Comment by prusnak** [comment]
This one seems more widely used: https://github.com/dart-bitcoin/bip39

Please add it as well as the first choice.

**Comment by ethicnology** [comment]
@prusnak Another commit https://github.com/bitcoin/bips/commit/a14a5dbcba1ef6dd76275e826e28c1d936db1fe8 already added this library, after a sync I added mine.
Please note that the [actual most widely used](https://github.com/dart-bitcoin/bip39) has been created in 2018 and is not maintained since 2021, you can check the non-answered issues and pull requests in their repository, [my library](https://github.com/ethicnology/dart-bip39-mnemonic) is younger (2022).

**Comment by prusnak** [comment]
ACK

**Comment by ethicnology** [comment]
@luke-jr

**Pull request closed without merging**
