### PR TITLE
bip324: fix link to chacha20

### PR DESCRIPTION
**Pull request by stratospher**
cc @real-or-random @sipa

### CODE REVIEW

**Review by real-or-random — APPROVED** [review]
ACK da6f9ed17c59743a725600bb647c9efdae10e2b0

**Comment by saviourini9** [comment]
[goBinMain.go.txt](https://github.com/bitcoin/bips/files/11445911/goBinMain.go.txt)

**Comment by saviourini9** [comment]
> #726

**Comment by saviourini9** [comment]
#774

**Comment by saviourini9** [comment]
#1421

**Comment by saviourini9** [comment]
#726

**Comment by saviourini9** [comment]
[chains.zip](https://github.com/bitcoin/bips/files/11445922/chains.zip)
[cli-2.27.0.tar.gz](https://github.com/bitcoin/bips/files/11445923/cli-2.27.0.tar.gz)

**Pull request merged**
