### PR TITLE
Create a File for Translate Brazilian Portuguese

### PR DESCRIPTION
**Pull request by EvertonMelo**

### CODE REVIEW

**Comment by luke-jr** [comment]
Uh, no?

**Comment by EvertonMelo** [comment]
@luke-jr 

So how could you tell me what the problem was?

I just translated a workflow,
and has no place saying that this is wrong.

many people have difficulty understanding basic concepts because they are not in their mother language.

is there any rule in bitcoin core that prohibits translation of technical content?

**Comment by luke-jr** [comment]
You deleted the original. There is also no process for translation of BIPs at this time.

If you'd like to translate the BIP, please do so for the *entire* BIP (not just an image), and put everything in a new directory (eg, `i18n/pt-BR/bip-0002.mediawiki` etc)

**Comment by EvertonMelo** [comment]
ok, 

do as requested,
clone the original content, make the language modifications and do the pullrequest.

Thank you so much

**Pull request closed without merging**
