### PR TITLE
BIP39: mention hard limit of 1024 bytes

### PR DESCRIPTION
**Pull request by afk11**
By using SHA256 as a checksum and requiring a 32 to 1 ratio of entropy to checksum, we bound ENT to 8192 bits (1024 bytes), because CS has reached a maximum of 256 bits. Although it seems unrealistic, it is a hard limit, and not preventing it could lead to mnemonics that can't be decoded or other implementations can't verify. 

Libraries that expose encoding/decoding a BIP39 mnemonic should check:
  - whilst encoding, that the entropy size does not exceed 8192 bits, and that `entropyBits % 32 == 0`
  - whilst decoding, that the length of the encoded bit-string does not exceed 8448 bits

Context: https://github.com/bitcoinjs/bip39/pull/37 @dcousens @rubensayshi @voisine @prusnak

### CODE REVIEW

**Comment by dabura667** [comment]
Not necessary. Anyone making phrases that long are already breaking the BIP, anyways.

-1

**Comment by prusnak** [comment]
-1 as well. BIP39 specifies valid sizes of 128, 160, 192, 224 and 256
bits. Anything else is not BIP39.

**Comment by afk11** [comment]
The BIP makes recommendations (feel free to correct me) Not being stronger on this point is perhaps the reason for this PR in the first place?

**Comment by prusnak** [comment]
No, it does not make recommendations. If the wording is not strong
enough, please change it.

I don't want to have several BIP39 wallets floating around which are not
compatible.

**Comment by afk11** [comment]
> The recommended size of ENT is 128-256 bits. 

I know if this is to be taken as written, wallets are already not compatible. (haskoin, greenaddress..)

**Comment by prusnak** [comment]
Then they are not BIP39 compatible.

Loosing restrictions in BIP39 does not make the situation better (2
wallets which are not BIP39 compatible vs making all BIP39 wallets
incompatible).

**Comment by dcousens** [comment]
> The recommended size of ENT is 128-256 bits.

@prusnak this was definitely not clear.
There is no mention that sizes outside that range is not BIP39 compatible.

**Comment by rubensayshi** [comment]
iirc most implementations that I have seen do not limit the size at all because the BIP only recommends certain sizes.

considering this has been "out in the wild" in this state for so long already I think it would be more sane to asume there's people using non "recommended" sizes and to only limit the BIP to 1024 bytes, the point where things start to break.

**Comment by prusnak** [comment]
I don't know how to put it any more cleaner. If there are some broken
implementations of BIP39, that is their problem.

Let's rephrase the BIP if it is not crystal clear to everybody.

Anyone is free to start their own BIP if BIP39 is not enough for
their usage.

End of discussion. Please close this request. Thanks!

**Comment by rubensayshi** [comment]
@prusnak @luke-jr what the ... 

the BIP until now has not being clear AT ALL on what the limits were, only the recommended size, not a single word about that being the LIMIT.
  
as a result there are implementations and usage in the wild that have gone over the recommended sizes and I think you should man up to the result of the poorly specified limits and adjust the BIP to match what has happened as a result of that instead of suddenly making a whole bunch of "BIP39 compatible wallets"  become no longer BIP39 compatible!

**Comment by btcdrak** [comment]
I tend to agree with @rubensayshi - the written specification is the specification, you can't declare the specification is whatever you _intended_ but didn't write down. Does the reference implementation test for these supposed limits?

**Comment by luke-jr** [comment]
I'm inclined to agree that existing implementations shouldn't be retroactively made incompatible with the BIP, *especially* if Haskoin is one of such violations to this recommendation yet was accepted as an "other implementation". But the author has the final word on what changes to include in the BIP, so the only recourse would be to submit a competing BIP.

**Comment by rubensayshi** [comment]
Reference Implementation
http://github.com/trezor/python-mnemonic
 - no check for max length at all

Other Implementations
https://github.com/nybex/NYMnemonic

https://github.com/haskoin/haskoin
 - max 64 bytes

https://github.com/Thashiznets/BIP39.NET

https://github.com/NicolasDorier/NBitcoin

https://github.com/bitpay/bitcore-mnemonic
https://github.com/bitcoinjs/bip39 
 - no check

https://github.com/sreekanthgs/bip_mnemonic
 - no check

Other Other Implementations
BitcoinJ
 - no check

**Comment by rubensayshi** [comment]
even the reference implementation itself does not limit itself to the recommended sizes.

**Comment by prusnak** [comment]
> disclaimer: Blocktrail is not BIP39 compatible, I don't have any incentive for this to go down either way except that I feel this is clearly WRONG

@rubensayshi However you phrase it, the reality is - if you don't use 128-256 bits, but something out of this range, most of the BIP39 wallets won't be able to import this mnemonic you generated. I don't know what _your_ incentive is, but if you are generating mnemonics out of this range, it is clear that your incentive is not interoperability for your users.

And my point is that easier way to fix this "mess" (if there is any, TBH, I don't know how many users Blocktrail or hascoin has, but I doubt these are significant numbers when compared to other BIP39 wallets using the 128-256 bit range ...), is to make the standard more tighten (=interoperability) not more loose (another meaningless standard which does not guarantee anything).

**Comment by btcdrak** [comment]
@prusnak I think you have this backwards. Someone who wants to implement a BIP will read the text look at the reference implementation and test vectors in order to ensure they faithfully reproduce the specification. In this case certain limits are not specified, not in text, not in reference implementation and not in test vectors. As such, I dont understand how you can claim compatibility based on intent. The specification and even reference implementation clearly allows higher limits.

**Comment by prusnak** [comment]
This is closed issue.

**Pull request closed without merging**
