### PR TITLE
BIP340 updates: clarifications, variable-length messages, expand domain separation

### PR DESCRIPTION
**Pull request by sipa**
For clarification, this does not make any semantics changes apart from permitting messages to have another length than 32. BIP341 and BIP342 obviously keep making use of just the 32-byte ones, and are thus unaffected.

### CODE REVIEW

**Review by real-or-random — APPROVED** [review]
ACK 200f9b26fe0a2f235a2af8b30c4be9f12f6bc9cb

**Review by jonasnick — COMMENTED** [review]
ACK d80e437ab1660a134c0cdd3e0397f37482e47f43

**Comment by real-or-random** [comment]
Is there anything to do on our side that prevents this from being merged?

**Comment by michaelfolkson** [comment]
cc @luke-jr @kallewoof

**Comment by kallewoof** [comment]
Sorry for the delay.

**Pull request merged**
