### PR TITLE
BIP-49 - Add Version Bytes Section

### PR DESCRIPTION
**Pull request by clarkmoody**
Added version bytes section in parallel with #761.

- [x] Update test vectors with new version bytes

cc @DanielWeigl

### CODE REVIEW

**Comment by prusnak** [comment]
ACK. Should we add link to https://github.com/satoshilabs/slips/blob/master/slip-0132.md?

**Comment by clarkmoody** [comment]
Ready for review @DanielWeigl. Update test vectors with new version bytes.

**Comment by DanielWeigl** [comment]
Ah, sorry - missed that github notification. Checked testvector against electrum.

LGTM

**Comment by clarkmoody** [comment]
@luke-jr I think we're good to go here.

**Pull request merged**
