### PR TITLE
BIP8: remove redundant and conflicting sentence from param selection and fix typo

### PR DESCRIPTION
**Pull request by jonasnick**
At the end of the param selection section it's explicitly stated that
`startheight` _must_ be a multiple of 2016.

### CODE REVIEW

**Comment by ajtowns** [comment]
Should fix the "4096" instead of "4032" typo as well probably? See https://github.com/bitcoin/bips/pull/1019#commitcomment-47677052

**Comment by jonasnick** [comment]
Done.

**Comment by Sjors** [comment]
ACK bc9d139

**Comment by jonasnick** [comment]
Rebased

**Comment by michaelfolkson** [comment]
ACK e1def09d6d75877a447dcc418a85291c80803a33

**Comment by MarcoFalke** [comment]
ACK @luke-jr

**Pull request merged**
