### PR TITLE
Adding crypzo to BIP44 supported wallets

### PR DESCRIPTION
**Pull request by dangershony**
Some of the source will be released soon.

### CODE REVIEW

**Comment by luke-jr** [comment]
@prusnak @slush0

**Comment by prusnak** [comment]
ACK if there is a sign that this wallet indeed uses BIP44

**Comment by dangershony** [comment]
Fair point, I can't think of any way to proof that (yet).
Two options I'll either expose source code or create a sand box page on the site.
I'll then update the pull request.

**Comment by dangershony** [comment]
Hi @prusnak 
Please check out this link showing Crypzo support BIP32/BIP44 
https://www.dropbox.com/s/gmxjnwln8ur5ywt/crypzo-bip44-proofe.pdf?dl=0
I'll still be opensourceing some of the code but not quite yet (when it's out of beta).

**Comment by prusnak** [comment]
ACK

**Comment by dangershony** [comment]
Gentle reminder @luke-jr

**Pull request merged**
