### PR TITLE
BIP 341: fix tuple index in taproot_tweak_pubkey

### PR DESCRIPTION
**Pull request by Crypt-iQ**
It is [0] but the pubkey is index [1]

### CODE REVIEW

**Comment by gmaxwell** [comment]
ACK.  It appears that https://github.com/bitcoin/bips/commit/0916da6594609b811e31c1f666638d15c8bd7381 swapped the order. @jonasnick

**Review by jonasnick — COMMENTED** [review]
Thank you @Crypt-iQ.
ACK 6baef391e010f01225ee76ab0df7e4f7e5460a36

Would you like to fix the line
```
output_pubkey, _ = taproot_tweak_pubkey(internal_pubkey, h)
```
in `taproot_output_script` too?

**Comment by Crypt-iQ** [comment]
Fixed the line in `taproot_output_script` as well

**Review by jonasnick — COMMENTED** [review]
ACK b1dbe62a21381661dff8d670480944c7a70eff61

**Pull request merged**
