### PR TITLE
bip versioning

### PR DESCRIPTION
**Pull request by RandyMcMillan**

### CODE REVIEW

**Comment by RandyMcMillan** [comment]
A way to structure major changes to BIPs while preserving original commit content
for easy reference.

**Comment by jonatack** [comment]
This proposal would appear to require an update to the process. According to BIP 2: "It is highly recommended that a single BIP contain a single key proposal or new idea. The more focused the BIP, the more successful it tends to be. If in doubt, split your BIP into several well-focused ones."

BIP85 will also be updated to Final status, given its adoption.

**Comment by jonatack** [comment]
Therefore, if a separate version is truly needed alongside an existing one, it should probably be a separate BIP.

For instance, BIP 78 (Payjoin) and [future BIP 77 (Payjoin v2)](https://github.com/bitcoin/bips/pull/1483).

**Comment by RandyMcMillan** [comment]
Note: We have plenty of bips that use external links to reference implementations that get clobbered or go stale for some other reason - this should be avoided.

**Comment by jonatack** [comment]
Yes, I'm in favor of changelogs, and the current process update proposal at https://github.com/murchandamus/bips/pull/2 adds them.

> We have plenty of bips that use external links to reference implementations that get clobbered or go stale

Please don't hesitate to open a pull to update or remove stale links.

**Pull request closed without merging**
