### PR TITLE
BIP-60: typo fix

### PR DESCRIPTION
**Pull request by fakefraud**
minor typo fix

have a nice one

### CODE REVIEW

**Comment by luke-jr** [comment]
@genjix

**Review by illesdavid — APPROVED** [review]

**Comment by katesalazar** [comment]
@genjix

**Review by murchandamus — APPROVED** [review]
ACK 682fd8bc588df7d71476420f7bc9ed1cbacabd05

This PR only fixes trivial spelling mistakes and does not change the meaning of the text.

**Comment by ProofOfKeags** [comment]
ACK [682fd8b](https://github.com/bitcoin/bips/pull/1522/commits/682fd8bc588df7d71476420f7bc9ed1cbacabd05)

**Pull request merged**
