### PR TITLE
Create AML-KYC

### PR DESCRIPTION
**Pull request by jollysean**
The proposal to create a regulator module in Bitcoin protocol.

### CODE REVIEW

**Comment by gmaxwell** [comment]
You have not been assigned 185. You may not use 185. Please follow the process in BIP1.

**Comment by jollysean** [comment]
Hi,

I am proposing to allow regulation in consensus of Bitcoin Protocol for ALLOW and BLOCK of user accounts and this should start a sanitation process on Bitcoin

**Comment by laanwj** [comment]
Do you have the proper authorization from the Internet trolling central planning commission?

**Comment by dabura667** [comment]
KYPK Know Your Public Key
ABL Anti-Bitcoin Laundering
OIBC Office of Internet Bitcoin Control

I'm sorry, I can't keep a straight face here...

**Comment by ToTheMoonGuy** [comment]
(°.°)

**Comment by gmaxwell** [comment]
@jollysean Yes, I understood, but you still need to follow process. :)  Just make your proposal there, discuss it, and you can have a BIP number assigned if you still want one.

**Pull request closed without merging**
