### PR TITLE
Update compatible wallets list

### PR DESCRIPTION
**Pull request by moodmosaic**

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak

**Comment by prusnak** [comment]
NACK, wrong URL

**Comment by moodmosaic** [comment]
Ops, sorry about that. I'm about to fix it.

**Comment by moodmosaic** [comment]
Fixed in efd1068.

**Comment by prusnak** [comment]
Not fixed, I can still see `https://https://`

**Comment by moodmosaic** [comment]
I can't believe this is me, but what can I say. It's fixed and forced pushed in c54e7f9.

**Comment by prusnak** [comment]
ack

**Pull request merged**
