### PR TITLE
add more tests for leading zero

### PR DESCRIPTION
**Pull request by klim0v**
In the library [btcsuite/btcutil](https://github.com/btcsuite/btcutil) and [decred/dcrd](https://github.com/decred/dcrd) all the tests that are listed here pass successfully, but there is an error on my case. 
```
seed: "57fb1e450b8afb95c62afbcd49e4100d6790e0822b8905608679180ac34ca0bd45bf7ccc6c5f5218236d0eb93afc78bd117b9f02a6b7df258ea182dfaef5aad7", 
path: "m/44H/60H/0H",
want pub: "xpub6CpsfWjghR6XdCB8yDq7jQRpRKEDP2LT3ZRUgURF9g5xevB7YoTpogkFRqq5nQtVSN8YCMZo2CD8u4zCaxRv85ctCWmzEi9gQ5DBhBFaTNo", 
want priv: "xprv9yqXG1Cns3YEQi6fsCJ7NGV5sHPiyZcbgLVst61dbLYyn7qy1G9aFtRmaYp481ounqnVf9Go2ymQ4gmxZLEwYSRhU868aDk4ZxzGvqJVH"
```
The correction and discussion can be found here https://github.com/btcsuite/btcutil/pull/161

### CODE REVIEW

**Comment by klim0v** [comment]
@luke-jr

**Comment by luke-jr** [comment]
This needs @sipa, not me

**Comment by sipa** [comment]
@klim0v Does btcutil not fail the existing test vector 3? If not, in what way does this one differ?

If we're adding this, please make it a test vector 4 rather than squishing it into vector 3.

**Comment by klim0v** [comment]
@sipa

**Comment by fametrano** [comment]
NACK
Unless I am missing something, a library not failing at test vector #3 would not fail at this new proposed case:
e.g. see https://github.com/btclib-org/btclib/commit/0cab43454b876d190a743a7886d77ad8ed0e8255

**Comment by kallewoof** [comment]
Is this resolved and can be closed, or is there still an issue that needs addressing?

**Pull request closed without merging**
