### PR TITLE
added test vector #5 for invalid extended keys

### PR DESCRIPTION
**Pull request by fametrano**
The BIP32 specification lacks test vectors for invalid extended keys that should not be parsed as valid. Such test vectors are proposed here.

### CODE REVIEW

**Comment by junderw** [comment]
good point.

I might also add some derivation tests that test specifically for leading zeroes in the private key for hardened derivation.

So many bigInt libraries in many languages convert to byte arrays with varying lengths and people forget that the ser_key needs to be 32 bytes.

For example: btcsuite btcutil ExtendedKey will not derive the following correctly as per this Pull Request: https://github.com/btcsuite/btcutil/pull/161

```
Root m:
xprv9s21ZrQH143K2PjtEr9foXN58DmBJu3nHmSnzXwvbqQiKqWZSsGPCNG1Je5qVeBF8fGGffBHAFu4jqXLkaHW4AbnByYDCfGKB4pxpyTTFRn
m/0H
xprv9v7bi4PiA35i9dhjDptXMMn46wLrFx37xorBaJhYzvjYUFC4fAFmPv1thGA9BinMyqdh6YnDAfasQdCBpYKUkW548fmeG1ZPkXLy5KLwkUY
```

Would be one such example.

**Comment by luke-jr** [comment]
@sipa

**Comment by fametrano** [comment]
> I might also add some derivation tests that test specifically for leading zeroes in the private key for hardened derivation.

that is already covered by the test vector 3 added in April 2017

**Comment by fametrano** [comment]
If it helps, a test vector is [available here](https://github.com/btclib-org/btclib/blob/master/btclib/tests/test_data/bip32_invalid_keys.json), as part of the [btclib](https://github.com/btclib-org/btclib) test suite, namely tested [here](https://github.com/btclib-org/btclib/blob/master/btclib/tests/test_bip32.py#L188)

**Comment by klim0v** [comment]
https://github.com/bitcoin/bips/pull/905

**Comment by fametrano** [comment]
> #905

Unless I am missing something, a library not failing at test vector #3 would not fail at this new proposed case:
e.g. see btclib-org/btclib@0cab434

**Comment by fametrano** [comment]
is there anything I could do to help this PR being accepted?

For a json file of the invalid keys see in the btclib library https://github.com/btclib-org/btclib/blob/master/btclib/tests/test_data/bip32_invalid_keys.json

**Comment by sipa** [comment]
The tests for "zero parent fingerprint with non-zero depth" are wrong. There is no reason why fingerprint 0 implies it's a root.

**Comment by fametrano** [comment]
> The tests for "zero parent fingerprint with non-zero depth" are wrong. There is no reason why fingerprint 0 implies it's a root.
My bad!

I've amended the code and squashed all commits so far.

**Comment by fametrano** [comment]
any chance for this to be accepted?

**Comment by MarcoFalke** [comment]
Needs rebase?

**Comment by luke-jr** [comment]
Rebasing isn't needed assuming the vector # can just be bumped to 5.

Just needs @sipa's approval

**Comment by sipa** [comment]
ACK.

See implementation for Bitcoin Core here: https://github.com/bitcoin/bitcoin/pull/22836

**Comment by benthecarman** [comment]
ACK

this found a bug in bitcoin-s

https://github.com/bitcoin-s/bitcoin-s/pull/3634

**Comment by darosior** [comment]
ACK

Implemented in python-bip32, which was too lax on parsing. https://github.com/darosior/python-bip32/pull/17

**Pull request merged**
