### PR TITLE
Add Go implementation

### PR DESCRIPTION
**Pull request by dongri**
I added a BIP39 Go implementation link.

### CODE REVIEW

**Comment by dabura667** [comment]
Your implementation is broken.

1. Your tests don’t check the seed vectors.
2. Your library doesn’t NFKD normalize.

NACK

Please fix for reconsideration.

**Comment by dongri** [comment]
https://github.com/dongri/go-mnemonic/commit/a6bb3ac443e0cf8522899e7076aeb9d659460704 

1. Fix Japanese word (NFKD normalize)
2. Fix library apply NFKD normalize

Please check

**Comment by dabura667** [comment]
You need to NFKD normalize mnemonic and password for ToSeedHex before casting to a []byte()

**Comment by dabura667** [comment]
Also chunksRe should be

[01]{11}

and not

.{1,11}

**Comment by dongri** [comment]
@dabura667 Thank you

I fixed some issue

https://github.com/dongri/go-mnemonic/commit/4ccec56a5421efb908134624d22c91e05e7b3be6

**Comment by dabura667** [comment]
1. Using TREZOR as the passphrase for testing Japanese will not test NFKD. This is because
norm.NFKD(“TREZOR”) == “TREZOR” (try it)

So you should keep the passphrase used in the Japanese test vectors. (It is made so that
norm.NFKD(passphrase) != passphrase

Then your tests will make sure NFKD is used properly.

**Comment by dabura667** [comment]
This is also why the Japanese test vectors are NOT pre-normalized.

We want to test the NFKD is working correctly.

:-)

**Comment by dabura667** [comment]
One tiny nit-pick: `binaryToByte` should be `binaryToInt` since you return an int64 and not a []byte...

Other than that, the vectors look good to me. I tested using apps I know to work and the entropy / mnemonic / seed for all the Japanese and English test vectors in your app passed.

Also, I might prefer if you convert the wordlists into .go files rather than using the statik dependency.

In general cryptocurrency libraries should avoid dependencies when at all possible.

ie. https://github.com/bitpay/bitcore-mnemonic/blob/master/lib/words/japanese.js

Maybe make a package called wordlists in /wordlists and have one go file for each language and make a struct like:

```go
// /wordlists/wordlist.go
type Wordlist [2048]string

// /wordlists/english.go
const WordlistEnglish Wordlist = [2048]string{
  "aaa",
  "bbb",
  ...
  "zzz"
}

// /wordlists/french.go
const WordlistFrench Wordlist = [2048]string{
  "aaa",
  "bbb",
  ...
  "zzz"
}
```

etc etc... (I am new to go, so if my syntax is wrong I am sorry.

**Comment by dongri** [comment]
@dabura667  Thank you advice
I fixed func name, and remove statik dependency

**Comment by dabura667** [comment]
Looks great.

ACK on adding it to the list of implementations.

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by dongri** [comment]
@dabura667 
Why don't you merge? Should I close it?

**Comment by dabura667** [comment]
@dongri I don't have merge permissions.

@luke-jr has merge permissions, and as a rule of thumb, there needs to be an ACK from the authors.

Since this account is not associated with a known author, my ACK means nothing in regards to whether it is merged or not (though if enough of the people see me around and trust my judgements maybe eventually my ACK will be a sign that they don't need to check anything closely)

Also, historically BIP39 pull requests are usually ignored since the original authors are busy with other things. (Especially new wordlists... but that's unrelated to this PR so I won't go off on a rant here)

So you will probably wait for a while.

**Pull request closed without merging**
