### PR TITLE
Travis: Initial formatting tests

### PR DESCRIPTION
**Pull request by luke-jr**
This needs an admin to actually enable Travis...

### CODE REVIEW

**Comment by laanwj** [comment]
I've enabled travis for this repository

**Comment by MarcoFalke** [comment]
I was planning this as well. Thanks for going forward. Do you think it makes sense to grep for the copyright section as well; Or even add another field for the copyright?

**Comment by luke-jr** [comment]
That sounds reasonable to me, especially since it's a common omission.

**Comment by MarcoFalke** [comment]
> Or even add another field for the copyright?

Adding a field in the header would be the cleanest (and machine-readable) solution, imo. But this would require extending BIP 1?

**Comment by luke-jr** [comment]
It should be sufficient to add it in BIP 2 IMO.

**Pull request merged**
