### PR TITLE
Added bip39 Italian wordlist

### PR DESCRIPTION
**Pull request by paoloaga**
Here you can find the proposed Italian wordlist for BIP0039.

Words have been chosen using the following rules:

1. Simple and common italian words.
2. Length between 4 and 8 characters.
3. First 4 letters must be unique between all words.
4. No accents or special characters.
5. No complex verb forms.
6. No plural words.
7. No words that remind negative/sad/bad things.
8. If both female/male words are available, choose male version.
9. No words with double vocals (like: lineetta).
10. No words already used in other languages mnemonic sets.
11. If 3 of the first 4 letters are already used in the same sequence in another mnemonic word, there must be at least other 3 different letters.
12. If 3 of the first 4 letters are already used in the same sequence in another mnemonic word, there not must be the same sequence of 3 or more letters.

Rules 11 and 12 prevent the selection words that are not different enough. This makes each word more recognizable among others and less error prone. For example: the wordlist contains "atono", then "atomo" is rejected, but "atomico" is good.

All the words have been manually selected and automatically checked against the rules.

Words have been checked automatically against an italian dictionary and spell-checker and reviewed one by one.

### CODE REVIEW

**Comment by paoloaga** [comment]
I apologize for the multiple commits, I tried to squash everything into one but failed (resulting also in 2 closed pull requests). Is it possible to proceed from here?

**Comment by luke-jr** [comment]
Sure, doesn't matter how many commits there are. Can you get an ACK from one of the BIP 39 Authors?

**Comment by voisine** [comment]
@paoloaga is the word list NFKD normalized? (I haven't checked)

**Comment by dcousens** [comment]
@voisine [its](https://github.com/paoloaga/bips/blob/bip0039-italian/bip-0039/italian.txt) not using any non-ascii characters, AFAIK itt should be OK

**Comment by paoloaga** [comment]
@voisine yes, all the words are using standard ASCII charset. Chosen words don't have any accent or special char in native language so they don't cause any confusion. They are also different enough so that they can't be misspelled/misunderstood, they are all recognizable from the first 4 characters, there are at least 3 different chars between words, and words that have similar letter patterns have been avoided.

**Comment by dcousens** [comment]
Great work @paoloaga :+1:

**Comment by laanwj** [comment]
@voisine looks like this word list meets all the requirements; just waiting for your ACK to merge

**Comment by voisine** [comment]
non-itallian speaking ACK, thanks @paoloaga

**Comment by HostFat** [comment]
italian speaking ACK

**Comment by Polve** [comment]
Italian speaking ACK :+1:

**Comment by paoloaga** [comment]
Thanks @dcousens , @voisine , @HostFat , @Polve .

**Pull request merged**
