### PR TITLE
New BIP: P2SH and Version 0 Segwit Script enforcement from genesis

### PR DESCRIPTION
**Pull request by sdaftuar**
I believe this is ready for BIP number assignment?

### CODE REVIEW

**Comment by luke-jr** [comment]
See also PR #639.  (This topic should be brought up on the bitcoin-dev mailing list for discussion.)

**Comment by MarcoFalke** [comment]
@luke-jr I think it was: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2018-January/015588.html

**Comment by sdaftuar** [comment]
On further thought, we can wait on BIP number assignment for now, if the PR to Bitcoin Core isn't merged then I'll just withdraw this.

**Comment by luke-jr** [comment]
@MarcoFalke That doesn't address the question of whether to make BIPs for "technically a protocol change, but has no actual effect on the chain present or future".

**Comment by evoskuil** [comment]
Would the plan then be to document soft forks only after miners have actually rejected blocks by enforcing them?

**Comment by MarcoFalke** [comment]
Talking about protocol upgrades, whether they are soft forks or hard forks, clearly they should be documented.

**Comment by evoskuil** [comment]
That was my point, we don’t wait until there is a split to document a fork, we do it well beforehand. So the occurance of a split cannot be a threshold criteria.

Upgrade is a loaded term, implying that there are other deviations that do not need to be documented. If the purpose of the documentation is to document the protocol, any deviation from the protocol needs to be documented.

**Comment by sdaftuar** [comment]
Closing in favor of @luke-jr's suggestion here: https://github.com/bitcoin/bips/pull/639#issuecomment-382196357

**Pull request closed without merging**
