### PR TITLE
Update BIP39 Comments-Summary

### PR DESCRIPTION
**Pull request by BitcoinErrorLog**
The current summary seems inconsistent with reality, updated

### CODE REVIEW

**Comment by apoelstra** [comment]
This PR is probably going to lead to a lot of fighting, but I agree that "unanimously discouraged" is disconnected from reality here. And I say this as somebody who really dislikes BIP39.

My suggestion would be:
* Somebody sets up a wiki page on Core's github, or the bitcoin wiki, or whatever, detailing the problems with BIP39. [I have written up some stuff on the rust-bitcoin wiki](https://github.com/rust-bitcoin/rust-bitcoin/discussions/814). I have also written [a rant on the codex32 FAQ page](https://secretcodex32.com/faq/index.html).
* This should be linked somewhere in the BIP text itself, maybe under a new "Controversy" heading. (It might be okay to use one of the two links above, but they're both controlled by me and I don't make any claims about them being permanent.)
* The text that this PR tries to change should be changed to something like "Widely deployed but discouraged; see Controversy section" or something.

I would further suggest that we link to an alternate suggestion -- but I'm actually not aware of any alternates that have a BIP number.

**Comment by BitcoinErrorLog** [comment]
I'd be happy with anything actually accurate and providing context. Basically, someone on our team was saying "uhh John, why does this say this, doesnt everyone use this?!" so I just assumed it was some artifact of history that needed updating.

That said, it still feels oddly authoritative to word an update as "but discouraged" and "controversy" -- why can't we be more objective?

Something like, "Widely deployed, but better designs are possible (see Suggestions section)" or such.

**Comment by BitcoinErrorLog** [comment]
"A lot of fighting" has not materialized :)

Could we proceed with a compromise?

**Comment by achow101** [comment]
This shouldn't name software specifically, both because it comes off as an exhaustive list (which it is not), and it may appear to be an attack on the developers of that software itself (which I assume this is not). I would go with something like "Widely deployed, but discouraged for further implementation (see comments)"

**Comment by apoelstra** [comment]
We are very close to having BIP 93 merged -- see https://github.com/bitcoin/bips/pull/1425 -- which has some critiques of BIP39 and lives in this repo. I think we could say something like "Widely deployed, but see concerns described in BIP 93" if the word "discouraged" is too opinionated on the part of the BIP maintainers.

**Comment by luke-jr** [comment]
`Comments-Summary` is a summary of the comments wiki page. The current summary looks accurate.

Feel free to add additional comments to the wiki page, and PR an update to the summary to reflect the new comment(s).

Note, however, that the Comments-Summary is not concerned with implementations. Only comments on the wiki page.

**Pull request closed without merging**
