### PR TITLE
BIP143: Explicitly mention the SignatureHash function

### PR DESCRIPTION
**Pull request by kanzure**
The purpose of BIP143 is to propose an updated SignatureHash function. However, the only keyword reference in the BIP text is "sighash" buried near the end, meanwhile some of the existing source code floating around does not use the name "transaction digest algorithm". Hopefully over time this will change. On a related note, SignatureHash is a really bizarre name....

### CODE REVIEW

**Comment by jl2012** [comment]
ACK

**Comment by sipa** [comment]
@kanzure Do you mind explaining what's bizarre about SignatureHash? It
doesn't really matter, as it's just the name of the function, but I'd like
to know what made you say that.

**Comment by kanzure** [comment]
@sipa, it's not a signature and it's not a hash of the signature, couldn't possibly be a hash of the signature because the signature is made once signing the output of the function anyway.

**Comment by sipa** [comment]
@kanzure It's the hash being signed.

**Pull request merged**
