### PR TITLE
BIP 2: Allow editors to fix typos

### PR DESCRIPTION
**Pull request by luke-jr**
Please see https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/015065.html

### CODE REVIEW

**Comment by artem22801** [comment]
Все отлично

**Comment by bpivcard26** [comment]
`marged`

**Comment by randolf** [comment]
@luke-jr If this can't be implemented easily in GitHub's system, I'm willing to help out by watching for these kinds of Pull Requests and then fast-tracking them in when they are only spelling/grammar corrections.

**Comment by luke-jr** [comment]
Nobody's approval matters other than the author of the BIP being modified (unless it's s a Final/Active BIP, in which case the usual requirements apply *also*).

Approving changes you don't have authority to approve is at best a waste of time. :/

**Comment by jimpo** [comment]
I'm in support of this, perhaps requiring sign off from multiple BIP contributors (not necessarily the BIP author) that the meaning is unchanged, [as suggested by cdecker](https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-September/015083.html).

**Comment by Varunram** [comment]
This would be a good idea since it wouldn't waste people's time to ACK trivial stuff and also if the contributor(s) of the BIP(s) is/are not available, it prevents merging trivial fixes.

**Comment by btcdrak** [comment]
ACK.

**Comment by jonathancross** [comment]
Hi @luke-jr, it would be nice to move this forward.
Can you please respond to feedback on the mailing list and/or modify wording here if you agree?

Here is a summary:

@kanzure :
> Even minor revisions can not change the meaning of text. Changing a single
> word can often have a strange impact on the meaning of the text. There
> should be some amount of care exercised here. Maybe it would be okay as
> long as edits are mentioned in the changelog at the bottom of each
> document, or mention that the primary authors have not reviewed suggested
> changes, or something as much; otherwise the reader might not be aware to
> check revision history to see what's going on.


@Sjors :
> Perhaps it's enough to @mention authors in the PR and give them a week to object before merging?

Jean-Paul Kogelman :
> Perhaps having authors consent to certain types of changes when they submit their BIP?

@cdecker :
> Agreed, I think a sign-off mechanism might be desirable. Currently it must
be the original author(s) signing off, but we can probably widen that to be
any 2-3 community members. They'd basically be attesting that the meaning
did not change.

@petertodd :
> As part of this, we may want to say that the BIP editor should
cryptographically sign (and ideally timestamp) all their changes as a secondary
measure to make it clear who actually made the change.

**Comment by petertodd** [comment]
I'm happy for editors to fix typos even without kanzure's requirements.

Check PGP signatures if you want to be totally sure.

On December 31, 2018 7:25:56 AM UTC, Luke Dashjr <notifications@github.com> wrote:
>I got the impression there isn't consensus for this change. @kanzure's
>requirements in particular seem to make it more effort than it's worth,
>so I'm inclined to just close the PR...
>
>OTOH, maybe I should point out that these are just documents, and if
>there's ever a problem, things can be reverted with little harm...?

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by jonathancross** [comment]
I'd be fine with simply requiring that changes be pgp signed (although it might reduce participation a bit).  Remember, this is only about fixing obvious typos and everything will be recorded in git history.

**Comment by petertodd** [comment]
Oh! I'm ok with both allowing editors to use their judgement in fixing typos, and not requiring PGP signatures on contributions.

These are after all just design docs; leave it up to the authors to decide if they want the security of a PGP signature on their contributions. It's mostly their problem after all as the harm would be to their reputation.

I'm signing (and timestamping) all of mine!


On January 1, 2019 4:37:34 PM UTC, Jonathan Cross <notifications@github.com> wrote:
>I'd be fine with simply requiring that changes be pgp signed (although
>it might reduce participation a bit).  Remember, this is only about
>fixing obvious typos and everything will be recorded in git history.

-- 
https://petertodd.org 'peter'[:-1]@petertodd.org

**Comment by murchandamus** [comment]
I would consider it a strict improvement if BIP editors had permission to merge non-meaning changing PRs to BIPs.
Permitted should be to fix a typo or a broken link (where it can be adjusted to link to the new location of the original document). Not permitted without sign-off from the authors should be changing any words or adding punctuation.

**Comment by ProofOfKeags** [comment]
> I would consider it a strict improvement if BIP editors had permission to merge non-meaning changing PRs to BIPs.
Permitted should be to fix a typo or a broken link (where it can be adjusted to link to the new location of the original document). Not permitted without sign-off from the authors should be changing any words or adding punctuation.

I agree with this and would like something closer to this language to land in the actual proposed change. As it stands right now the diff suggests something more vague than what @murchandamus writes here.

**Comment by katesalazar** [comment]
I'd rather prefer using some kind of layers or ignorelists in order to
leave those PRs on hold indefinitely while sticking to process, but I think
that would imply migrating the ticket system finally (I appreciate 0xb10c
work about that), so for the sake of collaborators sanity, I would hope for
allowing BIP editors to merge typos **as a temporary measure only in effect
as long as the community is still using GitHub as issue tracker**

**Comment by achow101** [comment]
ACK

As an author of several BIPs with far too many typos, I wholeheartedly agree with this change.

**Comment by jonathancross** [comment]
ACK

**Review by 5twelve — APPROVED** [review]

**Pull request merged**
