### PR TITLE
Fix hex of first FindAndDelete example

### PR DESCRIPTION
**Pull request by richardkiss**

### CODE REVIEW

**Comment by richardkiss** [comment]
@jl2012

**Comment by jl2012** [comment]
yes, that's wrong, but the correct tx should be

`0100000000010169c12106097dc2e0526493ef67f21269fe888ef05c7a3a5dacab38e1ac8387f14c1d000000ffffffff01010000000000000000034830450220487fb382c4974de3f7d834c1b617fe15860828c7f96454490edd6d891556dcc9022100baf95feb48f845d5bfc9882eb6aeefa1bc3790e39f59eaa46ff7f15ae626c53e012102a9781d66b61fb5a7ef00ac5ad5bc6ffc78be7b44a566e3c87870e1079368df4c4aad4830450220487fb382c4974de3f7d834c1b617fe15860828c7f96454490edd6d891556dcc9022100baf95feb48f845d5bfc9882eb6aeefa1bc3790e39f59eaa46ff7f15ae626c53e0100000000 `

**Comment by richardkiss** [comment]
Yes, sorry, I got the last two transactions mixed up. I've tried again.

**Comment by richardkiss** [comment]
OK, this one should be right. I'd also like to propose expanding these last two FindAndDelete transactions so they have much of the same info as in the other five examples. I'm happy to do this if you're interested.

**Comment by jl2012** [comment]
ACK.

I prefer to keep the current examples, as they are already used as unit tests here https://github.com/bitcoin/bitcoin/blob/master/src/test/data/tx_valid.json

**Comment by richardkiss** [comment]
I don't intend to change the transactions (I use them as unit tests in pycoin too), only add information, like about the unsigned version of the transaction, scriptPublicKey, etc. This information would have helped me in getting these tests working.

**Pull request merged**
