### PR TITLE
Fix Descriptor BIP typos

### PR DESCRIPTION
**Pull request by Christewart**
Fix typos in BIP380

### CODE REVIEW

**Comment by murchandamus** [comment]
cc @achow101, @sipa

**Comment by achow101** [comment]
ACK 109811e4b95168159155a98afb6229c8065a65ea

**Comment by murchandamus** [comment]
It would probably be easier to get this merged if changes to different BIPs were collected in separate PRs, even if the authors of the BIPs match.

**Comment by achow101** [comment]
ACK 4a937e1887891b58eb5a1c5bebc3eda00d3ba5c9

**Pull request merged**
