### PR TITLE
bip-0032: remove the 'Implementations' section

### PR DESCRIPTION
**Pull request by darosior**
~~This links to a (basic) Python3 implementation which passes all the bip's test vectors.~~

~~There are already two links to Python implementations but both are using Python2,
which was EOL at the begining of the year.~~
https://github.com/bitcoin/bips/pull/962#issuecomment-668274236

### CODE REVIEW

**Comment by sipa** [comment]
I think this list of implementations has outlived its usefulness. Nearly every Bitcoin library these days implements BIP32 - way more than are listed in the BIP - and as I don't have the time to review them all, I think listing some may be misinterpreted as an endorsement by the BIP's authors.

I think we should delete the entire section.

**Comment by darosior** [comment]
I understand the possibility of misinterpretation.

I could push a commit deleting it while i'm at it then.

‐‐‐‐‐‐‐ Original Message ‐‐‐‐‐‐‐

**Comment by darosior** [comment]
Pushed a commit which removes the section.

**Comment by sipa** [comment]
ACK, thanks!

**Comment by rustyrussell** [comment]
FYI: the commit which removed this does not have any explanation of why it was removed.

Please be more careful, as the base reasoning for a change belongs in the repository itself, not on GitHub which is naturally transient.

I would have simply quoted @sipa in the commit message in this case.

**Pull request merged**
