### PR TITLE
Minor grammatical change

### PR DESCRIPTION
**Pull request by droark**
The sentence regarding empty byte arrays being used to indicate an invalid ECDSA signature is confusing. I attempted to make it clearer. If I screwed it up or can make it even clearer, please let me know.

Thank you.

### CODE REVIEW

**Comment by jonasschnelli** [comment]
Please open trivial, non change PR at trivial next from @theuni: https://github.com/theuni/bitcoin/tree/trivial-next

**Comment by fanquake** [comment]
@jonasschnelli This is the bips repo

**Comment by jonasschnelli** [comment]
Aii.. Ignore my comment then. Sorry.

**Comment by laanwj** [comment]
Don't feel strongly about it but "the empty byte array" is strictly correct. There is only one possible empty byte array.

**Comment by droark** [comment]
@laanwj - Sorry if my comment wasn't totally clear. I mentioned the empty byte array because that was the affected sentence. (Granted, I think "empty byte array" still sounds weird, but I won't rewrite that.) I've highlighted the differences below. In particular, "for with" is definitely a typo.

Original: "To provide a compact way to deliberately create an invalid signature for with OP_CHECKSIG and OP_CHECKMULTISIG the empty byte array (the result of OP_0) is also allowed."

Revision: "To provide a compact way to deliberately create an invalid signature **for** OP_CHECKSIG and OP_CHECKMULTISIG, an empty byte array (**i.e.,** the result of OP_0) is also allowed."

**Comment by luke-jr** [comment]
@sipa ACK please, when you get a chance?

**Comment by sipa** [comment]
ACK

**Pull request merged**
