### PR TITLE
Simplify UASF Activation Logic, and update specification.

### PR DESCRIPTION
**Pull request by da2ce7**
Updated BIP 148 Activation Logic, as the timeout of this BIP is completely redundant.

### CODE REVIEW

**Comment by da2ce7** [comment]
@shaolinfry please review.

**Comment by da2ce7** [comment]
I'm going to withdraw this pull request, as dealing with the logic for a very slow hash-rate after the enforced period starts.

**Comment by shaolinfry** [comment]
In case you arent aware of the discussions, the reason the date was moved to Aug 1 was exactly to handle a ridiculous drop in hashrate, regardless of how unlikely.

**Comment by dooglus** [comment]
There's no point in having this UASF active after the SegWit activation period has timed out.

From Bitcoin's `src/chainparams.cpp`:

        // Deployment of SegWit (BIP141, BIP143, and BIP147)
        consensus.vDeployments[Consensus::DEPLOYMENT_SEGWIT].bit = 1;
        consensus.vDeployments[Consensus::DEPLOYMENT_SEGWIT].nStartTime = 1479168000; // November 15th, 2016.
        consensus.vDeployments[Consensus::DEPLOYMENT_SEGWIT].nTimeout = 1510704000; // November 15th, 2017.

**Pull request closed without merging**
