### PR TITLE
add persian wordlist to bip39

### PR DESCRIPTION
**Pull request by narimanam**
In this pull request we add a persian wordlist for bip-0039

### CODE REVIEW

**Comment by junderw** [comment]
BIP39 has been abandoned by its authors.

ThomasV moved on to use an improved version for Electrum, and SatoshiLabs made public statements that BIP39 should be English only and refuse to ACK any of the 10 or so wordlist addition pull requests.

Just tell the people of your country "if you want to use Bitcoin, be sure to study English harder, or lose money."

This PR is likely to never get ACKed or merged.

---

That being said, could you explain any considerations you made, or how you created this list?

Other Persian devs may want to debate on its contents.

**Comment by p2w34** [comment]
Almost a year ago I have spent a significant amount of time creating the Polish word list by myself only (my thought process might be found here: https://github.com/p2w34/blog/blob/master/2019-03-25-polish-word-list-bip0039/polish-word-list-bip0039.md)
I have been thinking about BIP-0039 ever since. I have already kicked off the work on all the lists:
https://github.com/p2w34/wlips. I hope that once the number of word lists grows to a significant number, it will become a standard.
I admit it might be too early to 'advertise' it by writing this post here, but maybe it will inspire some of us to contribute.
BIPS repo indeed does not seem to be the best place for submitting word lists. I can understand it - English list, at least for the time
being, serves good its purpose. However, I cannot imagine widespread adoption without creating word lists for each of the languages.

**Comment by junderw** [comment]
I personally know of at least 500BTC spread across 15 users or so that have been lost or nearly lost (I had to decipher their chicken scratch/misspelled English and find matches in the wordlist) due to the user not having strong English skills.

Probably more if you count all the altcoins that use BIP39 for backups.

**Comment by laanwj** [comment]
> BIP39 has been abandoned by its authors.

Looks like "bip39-wordlists" might be better as a separate project.

**Comment by p2w34** [comment]
> > BIP39 has been abandoned by its authors.
> 
> Looks like "bip39-wordlists" might be better as a separate project (if there's _anyone_ willing to maintain such a thing).

This is the reason abovementioned WLIPS (Word Lists Improvement Proposals) repo has been launched: https://github.com/p2w34/wlips

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Pull request closed without merging**
