### PR TITLE
Add Hebrew wordlist to BIP39 

### PR DESCRIPTION
**Pull request by GuyPergal**
An exciting step to make blockchain technology accessible for Hebrew native speakers.

All words are manually reviewed by native speakers in addition to python script which verified length, order and 4-characters rule.

Hebrew wordlist rules:

1. Common and simple words in Hebrew.
2. Only words with 4-8 letters.
3. Words can be uniquely determined by typing the first 4 characters.
4. No personal names or geographical names.
5. No offensive or negative words.
6. If both female/male words are available, choose only one version.

### CODE REVIEW

**Comment by GuyPergal** [comment]
@luke-jr

**Comment by luke-jr** [comment]
This needs @slush0 @prusnak @voisine @ebfull, not me.

It may be more productive in the short run to look at submitting this to https://github.com/p2w34/wlips

**Comment by prusnak** [comment]
+1 for moving all wordlists to wlips repo

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Comment by GuyPergal** [comment]
Thanks for your time! will do.

**Comment by eyaler** [comment]
@GuyPergal i did not find your new pr @ wlips yet so i am replying here. your list does not seem to adhere to the latest spelling standard of the hebrew language academy. According to the recent כללי הכתיב המלא from 2017, e.g. תכנית is written תוכנית. i am working on my own hebrew word list suggestion taking into account also word popularity in a large online corpus. lmk if you want to join forces.

**Comment by GuyPergal** [comment]
@eyaler Let's do it

**Pull request closed without merging**
