### PR TITLE
BIP112: fix example

### PR DESCRIPTION
**Pull request by jl2012**
CHECK(MULTI)SIG should be used.

### CODE REVIEW

**Comment by luke-jr** [comment]
@btcdrak @maaku @CodeShark

**Comment by luke-jr** [comment]
Personally, I think it's preferable to use the VERIFY...

**Comment by jl2012** [comment]
@luke-jr , technically you could do that, which requires an extra push in scriptSig

**Comment by luke-jr** [comment]
Why would it need an extra push? AFAIK, OP_CHECK[MULTI]SIGVERIFY behaves exactly as OP_CHECK[MULTI]SIG except that the VERIFY variant short-circuits script execution immediately.

**Comment by jl2012** [comment]
Without an extra push the stack will be empty after evaluation, which is invalid

**Comment by petertodd** [comment]
@luke-jr The easiest way to convince us would be to make such a transaction on mainnet and show that it works.

**Comment by petertodd** [comment]
utACK

Though I'd suggest jl2012 take my advice. :)

**Comment by btcdrak** [comment]
ACK

**Pull request merged**
