### PR TITLE
Changes/clarifications to bip-330.

### PR DESCRIPTION
**Pull request by naumenkogs**
We chose to drop truncated txids, because for certain protocols (such as Lightning or Coinjoin), 128-bit IDs would mean 64-bit collision-resistance due to the Meet-in-the-Middle attack.
We think this is not enough, because finding a collision might allow an attacker to censor a transaction (especially dangerous in a Lightning-like protocol).

Other changes include just fixing small mistakes in the spec and making it more clear.

P.S.

Added more stuff, mainly switching to extensions instead of bisections. The motivation is in the PR.

### CODE REVIEW

**Comment by naumenkogs** [comment]
Let's not merge it for now, considering that looking at the implementation might spawn more changes?

**Comment by luke-jr** [comment]
Please close this until it is ready to be merged

**Comment by sdaftuar** [comment]
@naumenkogs I think there is a mistake in the image describing the protocol flow.  At the bottom of the "InitRecon" step, it says that if there is success, then you move on to ExtendSketch, else you FinalizeRecon. I think those are swapped? If set reconciliation succeeds, you go straight to FinalizeRecon, while if it fails, you should attempt to extend the sketch?

Also it seems to me like there is an implicit assumption that we're only going to do Erlay for wtxid-based relay, so gating this on successful negotiation of BIP 339 would make sense to me.  Is that what you had in mind?  If so there should probably be some mention of that in this BIP.

**Comment by naumenkogs** [comment]
>@naumenkogs I think there is a mistake in the image describing the protocol flow. At the bottom of the "InitRecon" step, it says that if there is success, then you move on to ExtendSketch, else you FinalizeRecon. I think those are swapped? If set reconciliation succeeds, you go straight to FinalizeRecon, while if it fails, you should attempt to extend the sketch?

Yes.

>Also it seems to me like there is an implicit assumption that we're only going to do Erlay for wtxid-based relay, so gating this on successful negotiation of BIP 339 would make sense to me. Is that what you had in mind? If so there should probably be some mention of that in this BIP.

Yes.

-------- 

Will update the BIP with both suggestions.

**Comment by naumenkogs** [comment]
Other TODO:
1. Mention protocol version 70017
2. Update q=0.02
3. Mention that sendrecon should come after wtxidrelay
4.

**Pull request closed without merging**
