### PR TITLE
Update bip-0079.mediawiki

### PR DESCRIPTION
**Pull request by multisignature**
Fixed a couple of spelling errors.

### CODE REVIEW

**Comment by michaelfolkson** [comment]
ACK. Thanks for the correction!

**Comment by michaelfolkson** [comment]
The status of this BIP is "Replaced" and as far as I understand we need to go chase the BIP author (Ryan Havar) to make any changes to the BIP including typos. 

Hence I think this should be closed. Unless someone wants to chase the BIP author to make minor typos to a "Replaced" BIP.

**Comment by multisignature** [comment]
Oh, alright then. If it doesn't matter anyway, then feel free to close it. (I know Ryan and I can talk to him if you really want; not entirely sure what "Replaced" entails, I'm assuming it means the BIP is no longer relevant.)

**Comment by michaelfolkson** [comment]
Ok cool. If you can get Ryan to place an ACK here then Luke can merge it. The author of the BIP has to ACK it before Luke merges it (even for typos as I understand)

**Comment by multisignature** [comment]
Sure thing! I'll let him know the next time I see him in chat. Thanks.

**Comment by michaelfolkson** [comment]
Sorry to bother you @RHavar but can you ACK these typos. It needs an ACK from the BIP author to be merged.

**Comment by RHavar** [comment]
ACK

**Comment by michaelfolkson** [comment]
Thanks @RHavar. This is ready to merge @luke-jr.

**Pull request merged**
