### PR TITLE
fix for reference link error

### PR DESCRIPTION
**Pull request by brain-zhang**
BIP-0037 link: https://github.com/bitcoin/bips/blob/master/bip-0037.mediawiki

### CODE REVIEW

**Comment by MarcoFalke** [comment]
It depends on the software you use to render the links? https://en.bitcoin.it/wiki/BIP_0060 looks fine to me

**Comment by brain-zhang** [comment]
> It depends on the software you use to render the links? https://en.bitcoin.it/wiki/BIP_0060 looks fine to me

I open the origin url link in a browser as a dead link:

`https://github.com/bitcoin/bips/blob/master/BIP%200037; `

I think it's better to contain relative link of the repository and sync in real time.

**Comment by MarcoFalke** [comment]
Should be closed as duplicate of #688

**Comment by MarcoFalke** [comment]
Or just remove the link *meh

**Comment by brain-zhang** [comment]
duplicate of #688

**Pull request closed without merging**
