### PR TITLE
bip327: Link to right section

### PR DESCRIPTION
**Pull request by real-or-random**
cc @jonasnick

### CODE REVIEW

**Comment by real-or-random** [comment]
Oops, I had "fixed" the wrong link. The PR should make sense now.

**Review by jonasnick — APPROVED** [review]
ACK 7c6f500516a66c4796d0940d1d429a4fcf173d1a

**Review by 0xGRAV3R — APPROVED** [review]
ACK https://github.com/bitcoin/bips/commit/7c6f500516a66c4796d0940d1d429a4fcf173d1a

**Comment by real-or-random** [comment]
Superseded by https://github.com/bitcoin/bips/pull/1549

**Pull request closed without merging**
