### PR TITLE
BIP-341: explicitly allow softforks with future leaf versions

### PR DESCRIPTION
**Pull request by dr-orlovsky**
Currently the BIP-341 and BIP-342 leave the question of how to verify signature for non-`0xC0` leaf version scripts undefined. I haven't checked the Bitcoin Core code for that matter yet, but (1) I think we need to cover signature validation of non-`0xC0` leaf version scripts in this standard and (2) the only way of doing that is "always succeed" rule for the future leaf version values (otherwise we will need a hard fork to introduce them).

### CODE REVIEW

**Comment by sipa** [comment]
I think this is covered already, by saying evaluation happens according to applicable rules. Without applicable rules, there is nothing to execute, and thus no way execution could fail. I don't object to clarifying this, but (a) I'd do it in the existing section on validation and (b) I don't understand what signature validation has to do with this; validation rules for future leaf versions is entirely up to the definition of those leaf versions if and when they get defined. Hypothetically speaking, a future leaf version may have "scripts" that completely distinct from what we think of scripts today - potentially they don't even involve signature at all.

**Comment by dr-orlovsky** [comment]
Ok, I see your point on signature term and I will change this PR to add the statement to the existing section. I do think that this clarification is needed, since it is not obvious for the reader (at least was not obvious for me). 

Can you please confirm that it is the way it is currently implemented in Bitcoin Core? I was digging the source code but was not able to find the exact place where the `0xC0` version is checked and the rest is ignored (simple search for `0xC0` nor `TAPROOT_LEAF_TAPSCRIPT` didn't reveal anything in that regard).

**Comment by sipa** [comment]
@dr-orlovsky https://github.com/bitcoin/bitcoin/blob/v22.0/src/script/interpreter.cpp#L1948L1953

**Comment by dr-orlovsky** [comment]
@sipa thank you very much, do not know how I missed that part. May be GitHub search algorithms are not that good and I should have searched locally...

Anyway, thank you for the clarification. I have updated wording for this PR according to your suggestions

**Comment by sipa** [comment]
ACK 592cb6fa0c8e1484488cfc4e43fe1e4825c17132

**Comment by dr-orlovsky** [comment]
@kallewoof I assume this can be merged with an ACK from the BIP author?

**Pull request merged**
