### PR TITLE
NFKD normalize BIP39 spanish word list

### PR DESCRIPTION
**Pull request by voisine**
BIP39 specifies that word lists must be Unicode NFKD normalized. This should not affect existing wallet seeds since they must be NFKD normalized prior to deriving a master private key.

### CODE REVIEW

**Comment by dabura667** [comment]
This should also be done for Chinese... I assume you're going through the languages and checking? or would you like me to make a few pull requests as well?

**Comment by voisine** [comment]
I checked. They look good, but it would be great if you can double check my work.

**Comment by dabura667** [comment]
Double checked, both simplified and traditional give the same hash before and after running through NFKD.

**Comment by dabura667** [comment]
@laanwj PR by BIP author. Please merge. Thanks.

**Pull request merged**
