### PR TITLE
BIP 108: Block size increase to 2MB + small steps (BIP 102 variant w/ small steps)

### PR DESCRIPTION
**Pull request by jgarzik**
A request for BIP 102 was "a variant that does not require revisiting", so a small step was included per the current thinking on small-step small-shock.

*NOTE*: Creates new "drafts" directory to illustrate different proposal technique.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
Just for the record: @gmaxwell Did you assign this BIP number?

**Comment by jgarzik** [comment]
He didn't - proper number assignment appreciated

The index was intentionally not updated, for this reason.

**Comment by jgarzik** [comment]
Updated to illustrate a BIP-number-neutral, IETF-like technique.  Proposed process:

1. BIP author creates PR to store unnumbered BIP in drafts/    Naming convention similar to IETF draft:  draft-AUTHOR-SUMMARY.
2. BIP editors review drafts/* periodically for minimum standards, as per existing process.
3. BIP editor assigns a number, moves into main directory, updates index.

**Comment by btcdrak** [comment]
@jgarzik fwiw, draft naming is also recommended by BIP-0001 in the form `bip-jgarzik-2mb-small-steps`.

**Comment by luke-jr** [comment]
Needs Copyright section.

**Comment by jgarzik** [comment]
Closing request.  No near term horizon for this proposal.

**Comment by luke-jr** [comment]
It's not clear if I should de-allocate BIP 108 for reuse, or leave it assigned...

**Comment by dabura667** [comment]
BIPs should not be reused for clarity purposes imo.

**Comment by afk11** [comment]
Mark it as withdrawn?

**Comment by luke-jr** [comment]
Withdrawn makes sense IMO, but @jgarzik never completed the submission. :/

@jgarzik Can you license the BIP so it can be included as Withdrawn at least?

**Comment by gmaxwell** [comment]
meh. just turn it into an empty document with the header and withdrawn in order to kill the number. You're making things to complex. :)

**Pull request closed without merging**
