### PR TITLE
Reject 136 (expired)

### PR DESCRIPTION
**Pull request by ysangkok**
This has expired according to BIP-0002 expiration rules. Even though I am not an author, I can request this change. Tagging @veleslavs, an author.

### CODE REVIEW

**Comment by luke-jr** [comment]
Dunno if progression has occurred or not

**Comment by gmaxwell** [comment]
Is anything using this?

**Comment by danpape** [comment]
@ysangkok @luke-jr It is too bad you all didn't tag all three authors--I have been working on updates and am just about to issue a new PR when I noticed this in the PR history.

**Comment by luke-jr** [comment]
closing this per author opening #1121

**Pull request closed without merging**
