### PR TITLE
Minor: linking BIPs in BIP9

### PR DESCRIPTION
**Pull request by fresheneesz**

### CODE REVIEW

**Comment by sipa** [comment]
ACK cda85c75c176ebeba4152a238998b4c54aa74e89

**Comment by MarcoFalke** [comment]
Shouldn't relative links be used? Otherwise, regardless of where this is hosted, all links lead to GitHub.

**Comment by fresheneesz** [comment]
I do think relative links should be used. However for some reason markdown wasn't working, which confused TF out of me. Checking other BIPs, full URLs were used. Since I don't understand the bracket-link-text-bracket format of the links, I gave up and did it the old way with absolute URLs.

**Comment by MarcoFalke** [comment]
This is not markdown syntax, it is mediawiki syntax. IIRC relative links are `[[foo]]`

**Comment by fresheneesz** [comment]
Ohh, like wikipedia. I'm familiar with that. `[[link|text]]` actually. I updated.

**Pull request merged**
