### PR TITLE
BIP39 Turkish Wordlist - Proposal

### PR DESCRIPTION
**Pull request by paribu**
Words chosen using the following rules:

1. Words are 3-8 letters long.
2. No very similar words with 2 letter of difference.
3. Only nouns, adjective and adverbs, no other word types.
4. No words with double vocals (like: saat).
5. No complex verb forms.
6. No plural words.
7. No words that remind negative/sad/bad things.
8. No words with double spelling.

### CODE REVIEW

**Review by Horlarhold — APPROVED** [review]

**Review by mhkafadar — APPROVED** [review]

**Review by Kognitif — APPROVED** [review]

**Comment by michaelfolkson** [comment]
Please see: https://github.com/bitcoin/bips/pull/1129#issuecomment-873267328

> For now, the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo here: https://github.com/p2w34/wlips

**Review by Luis123QG — APPROVED** [review]
@Luis4Q

**Review by Luis123QG — APPROVED** [review]
@Luis123QG

**Comment by murchandamus** [comment]
Hey, this has been open for a while. Would you happen to have an update for us? Has this list been adopted in some implementations, or has it been discussed in some other forum/mailing list?

This PR appears to need a rebase presumable since something else changed `bip-0039-wordlists.md` and that is causing a merge conflict.

**Comment by murchandamus** [comment]
It appears that [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

If BIP39 no longer accepts new wordlists, and such pull requests should instead be directed at the WLIPs repository, it seems to me that this PR can be closed.

I propose to close this PR after 2024-05-10 unless further activity indicates otherwise.

**Comment by murchandamus** [comment]
This [update](https://github.com/bitcoin/bips/pull/1395) sounds to me as if the BIP39 authors have generally restricted themselves to focus only on an English wordlist. I am afraid that I do not know where your wordlist should be submitted eventually, since neither BIP39 nor the WLIPs seem to be looking to incorporate further lists. Perhaps this would be a topic to discuss with other Turkish speaking Bitcoin users.

Since this PR does not seem to have a prospect of getting merged, it seems to me that it should probably be closed.

**Pull request closed without merging**
