### PR TITLE
BIPs 157 & 158: Block Filtering stuff

### PR DESCRIPTION
**Pull request by jimpo**
This is a revision of #609 that is intended as a replacement due to the number of substantial changes. Test vectors will be added once the BIP has been reviewed by the community and the reference implementation is updated.

### Abstract

This BIP describes a new light client protocol in Bitcoin that improves upon currently available options. The standard light client protocol in use today, defined in BIP 37, has known flaws that weaken the security and privacy of clients and allow denial-of-service attack vectors on full nodes. The new protocol overcomes these issues by allowing light clients to obtain compact probabilistic filters of block content from full nodes and download full blocks if the filter matches relevant data.

New P2P messages empower light clients to securely sync the blockchain without relying on a trusted source. This BIP also defines a filter header, which serves as a commitment to all filters for previous blocks and provides the ability to efficiently detect malicious or faulty peers serving invalid filters. The resulting protocol guarantees that light clients with at least one honest peer are able to identify the correct block filters.

### State of Implementation

We've tested the implementation of both a [light client implementing this BIP](https://github.com/lightninglabs/neutrino), as well as the serving full-node on Bitcoin's testnet over the past several months. Additionally, this new operating mode also serves as the basis for our [light weight Lightning node](https://github.com/lightningnetwork/lnd/). These implementations are based on an earlier version of the spec, and require some updates.

### CODE REVIEW

**Comment by luke-jr** [comment]
Please use BIP number 158.

**Comment by jimpo** [comment]
@luke-jr Thanks! There are two BIPs now though. It would be nice to get two sequential numbers.

**Comment by luke-jr** [comment]
Two BIPs? What am I overlooking? I don't see that?

**Comment by jimpo** [comment]
There are two files. They are related, but separate BIPs.

1. Client Side Block Filtering
2. Compact Block Filters for Light Clients

**Comment by luke-jr** [comment]
Sorry, totally overlooked that this PR had two files.. Let's go with 157 & 158 then? Also, note there is no `Editor` key in the preamble.

**Comment by jimpo** [comment]
@luke-jr Anything else required for merge here?

**Comment by luke-jr** [comment]
Looks good

**Comment by hkjn** [comment]
Maybe you're already aware, but FYI there's a remaining `TODO` in BIP158 for test vectors:
* https://github.com/bitcoin/bips/blob/master/bip-0158.mediawiki#appendix-c-test-vectors

cc @jimpo @luke-jr

**Pull request merged**
