### PR TITLE
BIP155: Remove external link

### PR DESCRIPTION
**Pull request by kiminuo**
Fix link.

### CODE REVIEW

**Review by jonatack — COMMENTED** [review]
ACK

**Comment by michaelfolkson** [comment]
ACK. The old link redirects to the new link it appears but no harm in updating it.

As the author of the BIP can you ACK this please @laanwj? Then Luke can merge it.

**Comment by laanwj** [comment]
I'm not sure linking to bitcoin.org was a good idea here in the first place. After all BIPs should be self-contained as possible (for the long term), and the reference is not specific—it's not like the format for the `addr` message can only be found in one place 

So I'd prefer to just remove the link.

**Comment by kiminuo** [comment]
@laanwj Updated.

**Comment by laanwj** [comment]
Thanks you, ACK cd1f225a0bd008efe1be5a1d60af3f68573b0ff4

**Pull request merged**
