### PR TITLE
unicode normalization in BIP-39

### PR DESCRIPTION
**Pull request by grondilu**
Four languages have word lists encoded in non-normalized unicode.  See [canon and compatibility equivalence](https://unicode.org/reports/tr15/#Canon_Compat_Equivalence).

This makes display and comparison with input fail on some terminals (admittedly I can only report on alacritty, though).

I suggest replacing all these files with normalized versions.

I obtained these normalized versions with bash/raku (raku always outputs normalized unicode) :

```console
bip-0039 $ for f in *.txt; do raku -e "print q{$f}.IO.slurp" > /tmp/$f; mv {/tmp/,}$f; 
```

### CODE REVIEW

**Comment by apoelstra** [comment]
Are the non-normalized versions fed into the hash function that derives the BIP32 seed? If so, changing the encoding will cause seeds to change and people to be unable to recover their coins.

This isn't concern trolling -- I really think this might be true, but I don't know.

**Comment by roconnor-blockstream** [comment]
I don't know what I'm talking about, but...

From https://docs.raku.org/language/unicode it suggests that `raku` is outputting NFC data, but BIP-39 specifically calls for NFKD data.  Thus I'm guessing the words lists are written in NFKD format, as one would expect.

How wallets display these words, is probably out of scope.  I think that normalizing them for display could perhaps be reasonable, but TBH, it sounds more like alacritty is perhaps "broken" for not treating combining characters correctly.

BIP-39 is listed as "Unanimously Discourage for implementation" for this and many other reasons.  We really need to follow that advice and move onto alternatives such as SLIP-39 or [Codex32](https://github.com/bitcoin/bips/pull/1425).

P.S. @luke-jr it would be helpful to get a BIP number assigned to Codex32 so that we can start directing people to BIP-39 alternatives.

**Comment by grondilu** [comment]
> Are the non-normalized versions fed into the hash function that derives the BIP32 seed? If so, changing the encoding will cause seeds to change and people to be unable to recover their coins.

I think you are right.   A different encoding will generate a different seed.  So I suppose it is a bad idea to change this.

My bad.

**Comment by grondilu** [comment]
> From https://docs.raku.org/language/unicode it suggests that `raku` is outputting NFC data, but BIP-39 specifically calls for NFKD data.

It appears you are correct.  This PR is unfounded.   Sorry for the inconvenience.

**Comment by roconnor-blockstream** [comment]
No worries.

**Pull request closed without merging**
