### PR TITLE
Update bip-0039.mediawiki

### PR DESCRIPTION
**Pull request by nathanph**

### CODE REVIEW

**Comment by laanwj** [comment]
Ping authors @voisine @prusnak

**Comment by prusnak** [comment]
In general this is a good idea I am not very fond of this change.

While creating the original english wordlist I tried to use soundex & co. to detect similar words, but in the end I realized it removed a half of the list. This makes the process of creating wordlist much more difficult and leads to worse wordlist (because you introduce more and more obscure words).

Also the main purpose of bip39 is to create a mnemonic sentence to write on the paper, not to tell by the phone.

**Comment by voisine** [comment]
Agree with @prusnak

**Comment by NicolasDorier** [comment]
You might don't care about my point for now, but BIP39 dictionaries will be used for other usage than BIP39.

But I'm creating a bip, for remembering and transmitting over phone [any reference to the blockchain](https://github.com/NicolasDorier/BIP-MnemoReference/blob/master/bip-mnemo.mediawiki).

So indeed, this is already the case, if that works, people will use it to transmit information over the phone. The question is more whether you care about it or not.

**Comment by laanwj** [comment]
The authors have made it clear that that is explicitly not the goal of BIP39 word lists. So for your BIP, you should use another scheme or list.

**Pull request closed without merging**
