### PR TITLE
BIP-0069: [trivial] expression

### PR DESCRIPTION
**Pull request by MarcoFalke**
`Randomly order` sound a bit like an oxymoron. Maybe `randomizing the order of` is better English?

### CODE REVIEW

**Comment by luke-jr** [comment]
@kristovatlas

**Comment by luke-jr** [comment]
@kristovatlas Please comment "ACK" if this change is okay.

**Comment by dcousens** [comment]
ACK

**Comment by kristovatlas** [comment]
ACK

**Comment by kristovatlas** [comment]
ACK after the fact

**Pull request merged**
