### PR TITLE
BIP85: Fix wrong test vector

### PR DESCRIPTION
**Pull request by azuchi**
There seems to be an error in the entropy of the Test Vector in BIP85.

* In test case1, `DERIVED KEY` is correct, but `DERIVED ENTROPY` is wrong. `efecfbccffea313214232d29e71563d941229afb4338c21f9517c41aaa0d16f00b83d2a09ef747e7a64e8e2bd5a14869e693da66ce94ac2da570ab7ee48618f7` is correct.
* In test case2, `DERIVED KEY` is correct, but `DERIVED ENTROPY` is wrong. `70c6e3e8ebee8dc4c0dbba66076819bb8c09672527c4277ca8729532ad711872218f826919f6b67218adde99018a6df9095ab2b58d803b5b93ec9802085a690e` is correct.

The entropy derivation for the other applications has been derived correctly except for the following path mistake.

* In XPRV test vector, `app_no` in the path is `39'` but `32'` is correct, in which case the `DERIVED ENTROPY` is `52405cd0dd21c5be78314a7c1a3c65ffd8d896536cc7dee3157db5824f0c92e2ead0b33988a616cf6a497f1c169d9e92562604e38305ccd3fc96f2252c177682`. If `DERIVED ENTROPY` does not include chaincode, need to change it to `ead0b33988a616cf6a497f1c169d9e92562604e38305ccd3fc96f2252c177682`.

`python-bipentropy` also outputs the above entropies.

### CODE REVIEW

**Comment by scgbckbone** [comment]
was about to write the same PR - thanks

**Comment by junderw** [comment]
I mentioned it in the original PR.

Not sure why it wasn't fixed.

**Comment by scgbckbone** [comment]
I also found bug in reference implementation and created fix [PR](https://github.com/ethankosakovsky/bipentropy/pull/3)

**Comment by azuchi** [comment]
> In test case 2 (which you have named 'test case 1') derived entropy is wrong also in your description here (commit is fine) --> you have 'h' at the end that should not be there

oh, thanks. I fixed.

**Comment by luke-jr** [comment]
@ethankosakovsky

**Comment by scgbckbone** [comment]
found another issues with this BIP - created new [PR](https://github.com/bitcoin/bips/pull/934)

**Comment by ethankosakovsky** [comment]
ACK

**Pull request merged**
