### PR TITLE
Updated C++ library link and added acknowledgement.

### PR DESCRIPTION
**Pull request by CodeShark**

### CODE REVIEW

**Comment by jonasschnelli** [comment]
ACK

**Comment by sipa** [comment]
I really hate to nitpick about this, but I don't think I can acknowledge
you in a BIP for an implementation that didn't exist at the time.

**Comment by CodeShark** [comment]
I had an implementation way before Bitcoin Core did...and the implementation has been listed in this BIP document forever.

**Comment by sipa** [comment]
Sure, but not when the BIP was written...

**Comment by luke-jr** [comment]
@sipa Please merge or close this.

**Comment by sipa** [comment]
ACK

**Comment by sipa** [comment]
I have no authority over the bips repository, nor is there any reason why I should. The fact that it is hosted under the bitcoin organization is coincidental, so I do not use this to merge bip changes.

**Pull request merged**
