### PR TITLE
BIP 8: Make threshold configurable, and reduce recommendation to 90%

### PR DESCRIPTION
**Pull request by luke-jr**

### CODE REVIEW

**Review by darosior — APPROVED** [review]
ACK 6ea5857b62d37724b1ea6947e0dc847afbc1b644 -- This is what was agreed during [2021/02 Taproot activation meeting](https://en.bitcoin.it/wiki/Taproot_activation_proposal_202102) in which most participants agreed it was reasonable.

**Comment by gmaxwell** [comment]
I think a reduced threshold is probably a good idea.  The downsides of a reduced threshold can be offset by putting in an effort to go nag parties that haven't updated during the period between lock in and activation.

**Comment by TheBlueMatt** [comment]
90% seems like a reasonable threshold, last i saw anyone run the probability of long forks of non-upgraded miners, 90% was reasonably unlikely to cause them. That said, much lower and you start to hit unlikely-but-unreasonable-risk territory, at least if I recall the numbers presented to me correctly.

I’m not sure why this needs to be a parameter so much as an amount - I worry that defining everything as a “parameter” normalizes ideas that are probably bad ideas - why would anyone ever bother with readiness signaling with activation thresholds materially less than 90%? If there’s material fork risk, might as well go for a flag day and make it explicit.

**Comment by jonasnick** [comment]
@TheBlueMatt I did a simple simulation here: https://github.com/jonasnick/bip8-tester/blob/master/threshold.py
```
Probability that unupdated node is on >= 2 block invalid fork with 95.0% threshold: 1.22%
Probability that unupdated node is on >= 3 block invalid fork with 95.0% threshold: 0.17%
Probability that unupdated node is on >= 2 block invalid fork with 90.0% threshold: 4.81%
Probability that unupdated node is on >= 3 block invalid fork with 90.0% threshold: 1.28%
Probability that unupdated node is on >= 2 block invalid fork with 85.0% threshold: 10.45%
Probability that unupdated node is on >= 3 block invalid fork with 85.0% threshold: 4.13%
```

This represents the worst-case of miners not updating after lock-in. In light of that, 90% doesn't seem too bad while 85% would be quite a bit worse. Defining the threshold as a parameter may help increasing it - depending on the circumstances - to 95% again because that's just safer.

**Comment by luke-jr** [comment]
I'm not sure there's any reason to even look at less than the standard confirmation minimum of 6 blocks...?

**Comment by luke-jr** [comment]
@TheBlueMatt I made it a parameter because I'm not sure 90% is going to be ideal for every softfork.

For example, if a softfork only affects miners, it might make sense to use a lower, or perhaps higher threshold, with an expectation that miners are also making a decision and not merely activating a predecided change.

Would it be satisfactory to simply make the 90% recommendation stronger somehow? (Though it already says "should"...)

**Comment by michaelfolkson** [comment]
> why would anyone ever bother with readiness signaling with activation thresholds materially less than 90%?

I can't envisage a scenario where it should be less than 90 percent personally but we can't tell the future and I think we should lean on flexibility for the consideration of future soft forks. I don't think there is certainty that 90 percent should always be used. A future soft fork may choose to go back up to 95 percent for example.

> Would it be satisfactory to simply make the 90% recommendation stronger somehow? (Though it already says "should"...)

I think "should" and the setting of precedent for future of soft forks is strong enough personally. Without flexibility, future soft fork proposals may merely choose to ditch this BIP and create a new BIP for the purpose of the activation mechanism. I think we should do our best to avoid that necessity.

**Comment by TheBlueMatt** [comment]
> I'm not sure there's any reason to even look at less than the standard confirmation minimum of 6 blocks...?

Sadly, 6 isn't really "standard" anymore. Lots of users accept at 3 confirmations (many 1, but there's not really anything we can do about that, they have fork risk monthly anyway).

> I made it a parameter because I'm not sure 90% is going to be ideal for every softfork.
> 
> For example, if a softfork only affects miners, it might make sense to use a lower, or perhaps higher threshold, with an expectation that miners are also making a decision and not merely activating a predecided change.

I don't think this holds - a lower threshold carries needles fork risk no matter the scenario.

> Would it be satisfactory to simply make the 90% recommendation stronger somehow? (Though it already says "should"...)

I think maybe it makes sense to say something stronger about 90%, eg MUST be 90% or higher, likely with a justification section that mentions the above calculations and notes that long forks can put significant user funds at risk.

**Comment by luke-jr** [comment]
>The important thing is to describe what the reasonable values for the threshold are.

Doesn't this do that already, at least? It says it should be 90% (except on testnet)...

**Comment by TheBlueMatt** [comment]
Err, sorry, I meant that if its parameterized with an intent that people may change it, it probably makes sense to describe why the suggested values are suggested, not just write that you should use 90 or whatever. This would presumably be two sentences and the math that jonas posted above.

**Comment by luke-jr** [comment]
The *opinion* that 3 block confirmation should be given special attention isn't universal (I certainly don't agree).

This seems good enough to merge; but feel free to open another PR elaborating further on reason(s) for the recommendation if you strongly think it's needed.

**Comment by ajtowns** [comment]
Post-merge ACK.

**Pull request merged**
