### PR TITLE
Fix error in scriptPubKey field in BIP 143 example

### PR DESCRIPTION
**Pull request by Sword-Smith**
It seems that a scriptPubKey used when signing a transaction was wrong.

### CODE REVIEW

**Comment by luke-jr** [comment]
@jl2012 @sipa

**Comment by ysangkok** [comment]
@Sword-Smith Do you have some code that you use to test this?

**Comment by Sword-Smith** [comment]
> 
> 
> @Sword-Smith Do you have some code that you use to test this?

I do not at the moment. But it is obvious, no? You are using BIP143 which is only used when spending segwit inputs. Agreed? So the scriptCode of the input I am spending must be of form P2WPKH or P2WSH in order for BIP143 to be used. Agreed? 

The field in question is field 5: 
`5. scriptCode of the input (serialized as scripts inside CTxOuts)`

So we are signing a scriptPubKey of something sent to a segwit address. That output must be of the form 0014 (P2WPKH) or 0020 (P2WSH). 

Or am I missing something?

**Comment by sipa** [comment]
This is incorrect. The `scriptCode` is the script being _executed_. It is not the scriptPubKey. For P2SH it is the redeemscript, for P2WSH (P2SH or not) it is the witness script. For P2WPKH it is the equivalent P2PKH script.

**Pull request closed without merging**
