### PR TITLE
BIP-131 Removing extra 'a' from sentence.

### PR DESCRIPTION
**Pull request by jonathancross**

### CODE REVIEW

**Comment by luke-jr** [comment]
@priestc

**Comment by kanzure** [comment]
ACK.

**Comment by jonathancross** [comment]
Ping @priestc

**Comment by jonathancross** [comment]
FYI: I don't believe we will be hearing from @priestc  -- I even wrote him an email about a month ago and no response.  Something we can do via BIP-2?

**Comment by jonathancross** [comment]
Giving up.

**Pull request closed without merging**
