### PR TITLE
BIP 119: CHECKTEMPLATEVERIFY

### PR DESCRIPTION
**Pull request by JeremyRubin**
I believe now is an appropriate time to apply for a BIP number/Draft Status for OP_CTV. A few elements will require updating before the BIP moves out of draft (e.g., the activation dates) but activation dates are a separate discussion from the technical considerations which are the focus of this BIP.

### CODE REVIEW

**Comment by JeremyRubin** [comment]
BTW I looked into the travis error -- it seems that the linter is reading a code block and failing because a C++ lambda *looks like* a improperly formatted markdown link.

I am happy to add a revert-able patch as below:
```c++
bool filter(const CTxIn& c) {
    return c.scriptSig != CScript();
}
uint256 GetStandardTemplateHash(const CTransaction& tx, const uint256& outputs_hash, const uint256& sequences_hash,
                                    const uint32_t input_index) {
        bool skip_scriptSigs = std::find_if(tx.vin.begin(), tx.vin.end(), filter) == tx.vin.end();
        return skip_scriptSigs ? GetStandardTemplateHashEmptyScript(tx, outputs_hash, sequences_hash, input_index) :
            GetStandardTemplateHashWithScript(tx, outputs_hash, sequences_hash, GetScriptSigsSHA256(tx), input_index);
    }
 ```

so that you don't have to muck around with a broken linter/supressions, but I think it's better to fix the linter longer term.

**Comment by luke-jr** [comment]
@JeremyRubin This is missing a backwards compatibility section.

@kallewoof Can you look into a better fix for the linter issue?

**Comment by kallewoof** [comment]
Looking.

**Comment by JeremyRubin** [comment]
@luke-jr it was unclear to me that a backwards compatibility section was needed for this BIP, referencing BIP-68 and BIP-112 as examples (while 68 covers compatibility for the interpretation of locktimes, neither covers the OP_NOP reinterpretation as being an incompatibility).

Regardless, I can push a section noting that there are no Backwards Incompatibilities.

**Comment by JeremyRubin** [comment]
* BIP 65 -- CLTV/CSV.

**Comment by JeremyRubin** [comment]
Added a backwards compatibility section; and rebased to pick up the linter fixes.

**Comment by luke-jr** [comment]
Use BIP 119

**Comment by JeremyRubin** [comment]
Thanks Luke! I've set the number & fixed links.

**Comment by murchandamus** [comment]
Hi @JeremyRubin, I was just going through the list of Draft BIPs, and trying to gauge which ones should be advanced to another Status. Would you agree that BIP119: CHECKTEMPLATEVERIFY should perhaps be advanced from Draft to [Complete](https://github.com/bitcoin/bips/blob/master/bip-0003.md#complete6)?

**Comment by JeremyRubin** [comment]
I think it's appropriate to be Complete.

The point of being Complete wrt CTV BIP is that there's historical discussions of what CTV can or cannot do, as an unchanged BIP artifact, spanning almost 7 years.

Previously, my preferred way to iterate when there was a substantive change during a feature BIP was to rename it. `CheckOutputsHashVerify -> SecureTheBag -> CheckTemplateVerify` are still 3 "independent" concepts from one another.

CTV I think would be unlikely to change at this point, and it serves historical discussion well to not change something like this, since it would confusingly invalidate much historical discussion.

So I'm favorable, but would want to think on it for a bit.

**Comment by murchandamus** [comment]
Yeah, as far as I could tell, the CTV proposal hadn’t changed in years, so my read was that your planned work on it must have concluded. There have also been several deployment attempts since it changed, which indicates that other people also think of it as ready. Since you wanted to think more about it, I am going to hold off on opening a PR. If you come to the conclusion that it makes sense, please open one.

**Pull request merged**
