### PR TITLE
Reject BIP-0043 (expired)

### PR DESCRIPTION
**Pull request by ysangkok**
BIP-0002 allows me to request even though I am not the author, this since 3 years have passed.

### CODE REVIEW

**Comment by MarcoFalke** [comment]
If this is used in production anywhere, it should not go to rejected

**Comment by luke-jr** [comment]
This seems to be used by BIPs 44, 45, 47, 49, 80, 81, 84, and 175.
At least one of these (BIP 49) is Final status.

@slush0 @prusnak Can we move BIP 43 to Final status?

**Comment by ysangkok** [comment]
Ok, see #916.

**Comment by schildbach** [comment]
BIP43 is quite widely implemented in wallets.

**Pull request closed without merging**
