### PR TITLE
Add C# implementation of BIP39 (NBitcoin)

### PR DESCRIPTION
**Pull request by NicolasDorier**

### CODE REVIEW

**Comment by laanwj** [comment]
Needs rebase

**Comment by NicolasDorier** [comment]
rebased

**Comment by NicolasDorier** [comment]
can someone merge that ? the is a 2 months pull request.

**Comment by vixxen** [comment]
It's very easy to make some words **bold** and other words *italic* with Markdown. You can even [link to Google!](http://google.com)
It's very easy to make some words bold and other words italic with Markdown. You can even link to Google!

**Comment by SamiQu** [comment]
> rebased
>

**Comment by SamiQu** [comment]
> It's very easy to make some words **bold** and other words _italic_ with Markdown. You can even [link to Google!](http://google.com)
> It's very easy to make some words bold and other words italic with Markdown. You can even link to Google!
>

**Pull request merged**
