### PR TITLE
BIP 106: Dynamically Controlled Bitcoin Block Size Max Cap

### PR DESCRIPTION
**Pull request by UpalChakraborty**
Transferred from https://github.com/UpalChakraborty/bips/blob/master/BIP-DynamicMaxBlockSize.mediawiki

### CODE REVIEW

**Comment by btcdrak** [comment]
Can you edit the title of the PR please. "Create BIP-1xx.mediawiki" isnt very meaningful.

**Comment by UpalChakraborty** [comment]
@btcdrak Oops. My Bad. Done.

**Comment by luke-jr** [comment]
Also need to update README.mediawiki please. And request a BIP number from @gmaxwell if you haven't already.

**Comment by UpalChakraborty** [comment]
@gmaxwell Requesting to assign a BIP number.

@luke-jr Will update README.mediawiki once the BIP number is assigned.

**Comment by gmaxwell** [comment]
106 cheers!

**Comment by UpalChakraborty** [comment]
@gmaxwell Thank you.

@luke-jr Pull request to update README.mediawiki has been created - https://github.com/bitcoin/bips/pull/193.

**Comment by andychase** [comment]
@gmaxwell Aren't you the only one that is supposed to approve and merge BIP changes into the code base according to BIP-0001?

Also this proposal is missing a copyright declaration which means the author is free to going around suing anyone who copies it in full or uses parts of it in derivative works.

**Comment by btcdrak** [comment]
Was this PR ready for merging? Looks like it was not complete (has two proposals in the specification)

**Comment by luke-jr** [comment]
It's Draft status. Beyond getting the BIP number assigned properly, the author basically has free reign. "[WIP]" sounds fine to me, but really a PR shouldn't be submitted at all until it is ready for review by the BIP author and merging...

**Comment by UpalChakraborty** [comment]
@andychase Regarding copyright declaration , BIP 70, 73, 101 do not have it either.

@btcdrak Status: Draft

**Comment by luke-jr** [comment]
@UpalChakraborty Please do add a proper copyright license in your next revision to the draft. Prior omissions are not really a good reason to neglect it. Thanks :)

**Comment by btcdrak** [comment]
> It's Draft status. Beyond getting the BIP number assigned properly, the author basically has free reign. "[WIP]" sounds fine to me, but really a PR shouldn't be submitted at all until it is ready for review by the BIP author and merging...

@luke-jr I disagree, a PR is also part of the review process and you need to give enough time for people to review it, spell check it, and iron out the nits. It's probably worth asking the OP if a PR is completely ready if it's not obvious and I think also the repository maintainer should question obvious issues - like this PR has two proposal in it, and is obviously unworkable in that state.

**Pull request merged**
