### PR TITLE
BIP113: Median Past LockTime

### PR DESCRIPTION
**Pull request by afk11**
Following the announcement on the ML (https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2015-August/010348.html).

TODO:
  - [x] BIP number assignment (113)
  - [ ] Link to discussions between @gmaxwell and @luke-jr where this change was first described

### CODE REVIEW

**Comment by gmaxwell** [comment]
Looking good so far.

**Comment by luke-jr** [comment]
@afk11 @maaku Ready for merging this? (note you can still update it in a future PR if necessary)

**Comment by btcdrak** [comment]
Let me squash some commits first.

**Comment by btcdrak** [comment]
rebased.

**Comment by btcdrak** [comment]
ACK for merge

**Review by Scutua — APPROVED** [review]

**Pull request merged**
