### PR TITLE
Add Korean Wordlist

### PR DESCRIPTION
**Pull request by junderw**
Alternative to #544 

Made on behalf of @Annyonghaseyo a Korean native that lives in Japan and regularly attends the Tokyo Bitcoin Meetup. She is also the translator of a lot of Korean bitcoin apps.

I don't really have much to say in the matter except the limited knowledge I have of Korean based on similarities to Japanese. She echoed the concerns of using -hada verbs in the list which was also echoed by others and myself.

This list is NFKD normalized and sorted in order of UTF-8 binary so as to allow for binary search.

### CODE REVIEW

**Comment by gnujoow** [comment]
Very nice @junderw @Annyonghaseyo

All words on the list are not difficult, easy to remember and well-following the rule mentioned by @Annyonghaseyo, and [bip39](https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#wordlist)
this is much better than #544

**Comment by voisine** [comment]
This list looks good. Non-Korean speaking ACK.

**Comment by junderw** [comment]
@luke-jr Looks like we have an ACK from BIP author @voisine and Korean natives @Annyonghaseyo and @gnujoow both see this wordlist as sufficient. Please merge if everything seems in order.

Thanks everyone.

**Comment by junderw** [comment]
Just generated 100 phrases using bitcore-mnemonic.

Can't understand it, but looks good.

```
역시 삼십 하드웨어 보통 세월 고궁 시골 제한 한마디 장미 청춘 관념
암컷 영국 같이 토마토 법률 탤런트 고전 마음 갈색 공업 점점 공동
예선 고구려 목숨 흥분 모퉁이 단골 시아버지 바탕 울음 사슴 의학 원인
신비 명예 내일 모양 교직 연출 전문 팝송 부문 부탁 사나이 창고
정비 왕자 태권도 만화 번개 전체 중학교 막걸리 입사 서명 승용차 전시
탤런트 책가방 형부 주택 퇴근 강아지 인공 사냥 어려움 극히 엔진 기원
무릎 테니스 전혀 알루미늄 간섭 즉석 칠십 밥솥 예전 엔진 줄거리 임무
행복 도저히 주말 벌레 공부 백화점 혹시 추천 교과서 자연 별도 법률
촛불 의논 단추 지진 고양이 습기 가뭄 시아버지 전통 정성 매장 가족
진짜 홍수 상자 강도 유적 지리산 막걸리 닭고기 햄버거 사슴 클래식 진료
전개 범위 개구리 위협 서명 여인 증세 견해 명예 이용 조건 속옷
과학 뒷산 왼손 약수 새벽 비빔밥 시중 무지개 지급 지진 아침 개방
필자 질병 인체 생명 장래 근처 저고리 상표 반대 물리학 공항 손실
요청 위험 보람 우연히 고집 오른발 장면 독립 시간 교실 학년 손질
스웨터 수필 한때 공무원 외갓집 종교 만족 조금 예술 대접 업무 대충
지원 연예인 의심 가르침 계약 관습 청바지 손녀 장미 요즘 자정 조상
만세 어둠 아스팔트 자정 조각 오히려 챔피언 수화기 숙녀 인류 파일 박물관
대충 보라색 향기 언어 공연 만두 화분 냉동 농장 철도 견해 장사
상처 삼촌 하지만 호텔 단계 도대체 박물관 손목 도중 평가 진통 부담
월세 토요일 불교 참외 새벽 화분 회전 외국 원피스 마흔 장미 인쇄
송편 매스컴 어려움 연출 방해 소문 변경 현대 정확히 오로지 매력 전주
왼발 하순 보람 천재 아흔 이곳 근본 문득 조절 한계 냉방 신문
마찬가지 원피스 반성 순서 평균 취업 총장 다음 볶음 초원 경찰 박사
신세 다양성 웨이터 수입 대전 음악 신문 일등 만일 쿠데타 올해 대충
흰색 철도 쇠고기 만약 지적 음주 연기 용어 화요일 원고 교장 전철
착각 상처 모금 한쪽 검토 차츰 녹차 논문 상식 경력 중국 홍차
수출 줄거리 운전 세상 자신 법원 민주 쇼핑 소풍 근로 성명 환갑
통역 자동 특히 요일 외로움 연예인 국적 재생 예상 내용 발톱 실시
영향 소용 초밥 상표 중국 아홉 환경 조미료 박수 빨간색 출입 전철
타자기 엉터리 스물 통일 정오 방금 음성 회장 마늘 골짜기 저녁 실력
근원 금연 녹음 정리 남매 유럽 엉터리 통역 여군 계곡 나침반 토론
비상 메일 승리 보관 여동생 각오 대접 인천 서른 운행 약수 중단
분홍색 단편 지극히 필요 이야기 추진 논리 업무 필자 목소리 연애 고무신
오월 절망 중앙 올림픽 김치 수건 태풍 간부 공사 희곡 도망 도입
영남 아스팔트 스님 교통 경비 시설 성장 지갑 일부 식사 석유 협력
여행 시합 아울러 일곱 일손 지출 발표 시멘트 단체 박수 장군 숙제
달리 시설 대중 목록 팩시밀리 모니터 고향 특성 화장 대합실 집단 간장
목소리 천국 불행 그토록 설명 방면 튼튼히 여권 단독 중세 의견 나물
용서 해석 고통 왜냐하면 사립 소극적 버섯 복사 학급 가을 즐거움 박수
경비 안내 시금치 수명 외로움 마중 효율적 북한 작용 강도 작성 원서
타입 방해 화분 매력 영국 어려움 관람 볼펜 집단 증가 포스터 광경
시일 신발 달러 날씨 큰절 공개 와인 영상 자판 교직 우정 실태
일대 발바닥 본인 스케이트 엉덩이 증거 분필 가정 단편 작은딸 혹시 녹음
중세 대응 수준 건물 신고 빗방울 홀로 줄기 큰아들 이중 장사 알코올
아스팔트 불만 품질 성명 일손 발표 왜냐하면 긴급 서민 군대 점검 불만
약점 텔레비전 심판 차츰 옷차림 절차 재학 초반 재활용 엔진 본사 복숭아
녹차 원래 순수 사계절 수험생 형제 굉장히 우산 중소기업 작년 지원 물체
장모 경복궁 일본 구름 가방 월요일 비둘기 찌꺼기 예정 제과점 실험 고급
이상 외삼촌 육십 연애 인종 반장 그제서야 매장 시즌 주먹 버릇 지점
안동 사탕 플라스틱 추천 김밥 도덕 점심 판사 능력 수명 도심 영남
이튿날 살인 자극 거짓 만족 계층 형수 인기 포스터 일월 국왕 열흘
헬기 안내 상상 예약 조각 어젯밤 한눈 내년 파출소 월세 찻잔 통과
중국 이틀 훨씬 큰길 대합실 어쩐지 이성 축소 스트레스 스위치 지능 민족
농민 큰아들 암시 종소리 짜증 깜빡 천장 단위 잔디 활용 한여름 몰래
생산 시험 포함 단골 센티미터 상태 절약 과학 사탕 비난 근처 통합
농부 민주 도입 서랍 원서 하룻밤 일손 술병 하필 신사 위험 불법
목적 발레 달러 결혼 필요 서클 방식 교육 벌금 형태 사랑 골짜기
마을 비빔밥 수업 모금 그제서야 학술 콩나물 상식 다양성 작은딸 종교 지진
도덕 항공 다방 전체 여덟 음력 밑바닥 경주 특징 미팅 이튿날 전용
한문 구속 보자기 센티미터 불꽃 저곳 생신 아프리카 복습 내년 물음 운전
고구려 번역 변명 수집 철도 북부 희생 도저히 고장 솜씨 환영 출판
여군 한라산 보관 백색 학위 베이징 일요일 사계절 햇살 신념 형부 글씨
노동 권위 번개 구청 고전 여학생 시부모 실수 야간 시험 구름 연락
스웨터 감기 이월 중반 총장 업체 변동 허락 자부심 전쟁 식물 에어컨
오징어 선전 일종 그러나 바늘 코미디 축구 교장 치약 슬쩍 충돌 종소리
심부름 집단 여성 가뭄 강수량 상처 아나운서 킬로 건조 화면 게임 살림
단위 현금 독서 준비 교복 편지 이력서 전라도 심장 독립 가운데 어젯밤
흑인 일주일 김치 필자 전반 어젯밤 귀신 원피스 대낮 평일 기원 강남
마련 수상 방금 재산 자율 영원히 초저녁 창구 풍경 금액 직장 보상
불만 소지품 증상 조금 이력서 움직임 복습 제주도 플라스틱 전반 여덟 시부모
손톱 만세 상태 서민 입대 견해 수돗물 소중히 종교 주름 침실 고전
트럭 축제 말씀 재학 시월 씨앗 해석 장마 월급 선원 잠옷 교환
작년 대답 대통령 밀리미터 체육 특별 강의 소규모 우정 제과점 친척 마무리
충분히 인구 냉면 교직 덩어리 세미나 달러 빨래 단추 팬티 마련 셋째
기술 만두 관심 주장 생명 작은딸 금요일 재학 입력 올림픽 원숭이 자전거
물리학 흥미 마흔 엉망 만일 참기름 침묵 현관 진행 환자 필름 사흘
주전자 목표 소속 막내 예상 오른발 평화 계층 환경 이혼 단골 주일
고무신 지금 고춧가루 경주 물고기 천천히 작가 칠판 외갓집 유럽 배꼽 음성
신사 예정 자신 보장 제한 진동 카운터 지금 법적 손길 티셔츠 한꺼번에
생물 긴급 협력 일체 기침 안경 지역 배경 구멍 시장 독감 재빨리
여건 문화 잠자리 설탕 영남 도움 멀리 손뼉 순서 대량 큰어머니 무척
에너지 자정 일월 여섯 결국 연세 병원 수출 무지개 종합 협력 학점
색연필 캠퍼스 교장 나침반 벌금 농부 육십 효율적 미국 세종대왕 연인 본질
매달 온라인 청년 암컷 한마디 봉사 의학 보너스 차별 구청 이혼 주인
달력 최종 학원 장비 한낮 비바람 연합 전통 적극 비타민 어른 일찍
야단 햄버거 배달 김포공항 연인 한번 킬로 원고 현실 승객 계약 표현
장미 출산 지점 보상 가르침 기침 막상 매장 센터 판단 관념 경험
몸매 공사 호텔 표정 모범 원인 심정 효율적 확인 무궁화 장마 제안
흥미 서클 문화 수시로 그날 저축 수출 학점 축구 간섭 형부 설치
주문 형부 민주 변동 짜증 낱말 타자기 차라리 학점 태풍 장애인 손질
수상 손실 권위 모델 국수 입술 철저히 필수 독감 점원 경상도 결혼
기업 예금 순수 가이드 버튼 실체 국가 풍경 허락 출산 흰색 성장
강남 대낮 바닷가 색연필 중학교 종합 요일 찬성 환자 건설 노동 단골
이전 연락 줄무늬 테스트 시어머니 경계 대중 대륙 나머지 단맛 복도 전세
법원 장점 화면 통제 기둥 미술 약속 살림 잠수함 실례 갈비 볼펜
보라색 소중히 피망 달러 평균 어려움 충격 정부 기독교 축제 심사 체험
부장 설문 저곳 저고리 국어 정도 송아지 방울 영상 본부 시점 주일
현관 육십 가장 경찰 방울 의학 자정 도전 공군 사방 음성 실패
인생 전망 주민 일행 교직 의논 씨름 빨래 깜빡 강의 제일 수화기
유행 강원도 작품 대출 아나운서 가운데 병아리 허락 비둘기 검사 취직 의논
```

**Comment by gnujoow** [comment]
@junderw it looks good for korean as well :)

**Comment by wlzla000** [comment]
# _ㅎㅏㄴㄱㅡㄹ_, I mean, _한글_.

How should one treat un-normalized _Hangul_ inputs<sup>(e.g. `가격` (`U+AC00 U+ACA9`))</sup>?

Should one normalize them into [NFKD<sub>(Normalization Form: Compatibility Decomposition.)</sub>](https://en.wikipedia.org/wiki/Unicode_equivalence#Normal_forms)<sup>(e.g. `가격` (`U+1100 U+1161 U+1100 U+1167 U+11A8`))</sup> before processing, or refuse to accept them?

**Comment by junderw** [comment]
@wlzla000 

1. User enters string.
2. Your app NFKD normalizes the string.
3. Your app splits the string on ' ' space (0x20) into an array.
4. Your app checks if each word is contained within a single wordlist you support.
5. If so, your app converts the indices of each word into binary to reassemble the data and verifies the checksum. If the checksum fails, throw a failure. If checksum passes, run the NKFD normalized phrase from step 2 through the pbkdf2 rounds.
6. If not, Ask your user "We could not verify the validity of this phrase. Would you like to use it anyways?" and if they say no. Throw a failure. If they say yes, run the NFKD normalized string from step 2 through the pbkdf2 rounds.

Since you will NFKD normalize the user's input, 한글 will become ㅎㅏㄴㄱㅡㄹ automatically.

That's the whole point of NFKD normalization. You do it on the backend. The user only interacts with the frontend.

**Comment by iancoleman** [comment]
Should Korean mnemonics be displayed with ideographic spaces (as per Japanese) or ASCII spaces (as per Chinese)?

There is no mention of this in the [bip39 wordlists document](https://github.com/bitcoin/bips/blob/master/bip-0039/bip-0039-wordlists.md).

Any other Korean language considerations that should be added to that document?

**Comment by junderw** [comment]
> Should Korean mnemonics be displayed with ideographic spaces (as per Japanese) or ASCII spaces (as per Chinese)?

If nothing is specified, ASCII.

If you google any Korean website at all, they use ASCII spaces in their writing.

Japanese and Chinese don't use any spaces at all normally.

**Pull request merged**
