### PR TITLE
Reject BIP-0047 (no progress in three years)

### PR DESCRIPTION
**Pull request by ysangkok**
According to BIP-0002, if there has been no progress from Draft status in three years, anybody can request to have a BIP rejected.

### CODE REVIEW

**Comment by clarkmoody** [comment]
BIP47 has been in production and heavy use by Samourai Wallet for years. There are probably other wallets that support it as well that I'm not aware of. I'm not sure what bearing that has on the BIP, but being adopted by some industry participants doesn't sound like a "rejected" BIP to me.

**Comment by ysangkok** [comment]
Why hasn't @samouraiwallet submitted a PR for advancing the BIP to "Proposed" status?

**Comment by raymonddurk** [comment]
@SamouraiDev I thought you should be pinged as you have it pinned.

**Comment by SamouraiDev** [comment]
Samourai Wallet implemented BIP47 and has since developed extensions for Segwit compatibility (P2SH and P2WPKH). Our PayNym offering is very popular as evidenced by the 22,129 users who have opted-in to sharing their stealth address and pseudonym on our directory PayNym.is. BIP47 will continue to provide a foundation for the services we provide. Merge this PR or not. This particular bureaucratic process is of no interest to us.

**Comment by xinbenlv** [comment]
If a standard has good adoption, I think it's worth effort making into the BIP or it will be a loss for both the proposal and the Bitcoin community....

**Comment by luke-jr** [comment]
@justusranvier needs to ACK a change to Proposed status.

**Comment by justusranvier** [comment]
It would most likely improve the reputation of the payment code standard to not be associated with the repository in any way.

**Comment by luke-jr** [comment]
That makes no sense. Are you trolling?

Is this BIP still a draft, or can we move it to proposed (and maybe final)?

**Comment by SamouraiDev** [comment]
> It would most likely improve the reputation of the payment code standard to not be associated with the repository in any way.

Concept-ACK

**Comment by ysangkok** [comment]
@luke-jr Since the author doesn't want to work the BIP, and the implementing parties don't seem to want to take it either, what can be done about this? You said it can't be "Proposed" if the author doesn't ACK, but it seems he isn't going to. So does that mean it gets stuck in Draft status forever?

**Comment by justusranvier** [comment]
What does it mean for a protocol which can be freely implemented or not by any client without requiring permission from other participants in the network to be "Accepted" or "Rejected"?

The answer to that question is the difference between a real standardization process and a meaningless personal sandbox.

**Comment by luke-jr** [comment]
@justusranvier The question is whether this BIP is still a draft or not. If you intend to make further changes, then the implementations might then be incompatible, and the Final status void.

Perhaps it would make sense in some cases to say "too late, this BIP is in usage, so if you want to make changes, you'll need to make a new BIP for them" - but currently the BIP process doesn't authorise me (or anyone else) to simply make that call. We'd need to reassign the BIP to someone else first.

@ysangkok Anyone can volunteer to take over an abandoned BIP, it doesn't need to be an implementor.

**Comment by ysangkok** [comment]
@justusranvier The BIP process considers the consensus of the community. Since this BIP was deemed to be "Unanimously Discourage[d] for implementation" (see BIP header), it provides value to the community to mark it as "Rejected", it clarifies the result of the discussion. Of course nobody can prevent anybody from implementing something, and nobody is stopping you from making your own standardization efforts (see SLIP).

You imply that it is a "meaningless personal sandbox", but if that were the case, how can it be that all high quality proposals are reflected in BIPs? I guess judging consensus will always be subjective, and I trust that @luke-jr can judge fairly what there is consensus for. It doesn't seem like there is consensus for this, and the fact that is has been implemented shouldn't force the community to accept the proposal. 

I don't know how to counter your implication that this is not a "real standardization process", since that is so poorly defined. And I already explained to you why this isn't a "personal sandbox".

**Comment by justusranvier** [comment]
@ysangkok This BIP and several others were vandalized with biased the personal opinions of a few Blockstream employees.

Since that time this repository should not be considered a reliable source of information for any use.

**Comment by luke-jr** [comment]
@ysangkok This BIP doesn't require consensus. Adoption by 2 or more pieces of software indicates a Final status.

@justusranvier That's just slander.

**Comment by ysangkok** [comment]
Ok, so it seems like this can't be rejected, since it has prominent implementations. The headers says that it is "unanimously discouraged" for implementation, which is misleading since the people advocating the proposal have not commented. That is another issue, and I don't know if it can be fixed, but if it can, it would need an author's ACK, which seems unlikely. Since the only thing BIP-0002 rules allow me to do, is rejecting, and I can't do that, I will just close this, and it can be left in Draft status.

**Comment by justusranvier** [comment]
This PR should address all the concerns in this thread which can be addressed: https://github.com/bitcoin/bips/pull/1068

**Comment by luke-jr** [comment]
>Sparrow Wallet, Samourai Wallet and Stack Wallet adopted this BIP. Does that mean the status can be changed to Final?

Only with permission from the author, since it hasn't been formally proposed yet (still Draft).

>Also does it mean the "Unanimously Discourage for implementation" comment will be rescinded?

That's just a summary of comments left on the comment wiki page. It's entirely independent of status.

**Pull request closed without merging**
