### PR TITLE
BIP112: Update document to match implementation

### PR DESCRIPTION
**Pull request by btcdrak**
For https://github.com/bitcoin/bitcoin/pull/6564

### CODE REVIEW

**Comment by NicolasDorier** [comment]
Not good, remove:
```
Otherwise, script execution will continue as if a NOP had been executed.
```
This is not true, if one of those conditions are true, then script fail. If none of them are true, then processing will continue as defined in this BIP.

The only condition this is considered a NOP is if SCRIPT_VERIFY_CHECKSEQUENCEVERIFY flag is disabled. Which is not worth mentioning in the BIP.

**Comment by btcdrak** [comment]
@NicolasDorier This is the same language used in BIP65. If the script does not fail, script execution continues as if a NOP had been executed.

**Comment by NicolasDorier** [comment]
Ok I see. Well, it is strange to say "executed as a NOP" as opposed to "the stack is not affected".
"Executed as NOP" for me mean no verification for failure is even made.

It does not stop me from understanding just finding it weird. Not a stopper though, if nobody complains let's keep it like that.

**Comment by NicolasDorier** [comment]
ACK.

I would replace "Otherwise, script execution will continue as if a NOP had been executed." with "OP_CSV has no effect on the stack". But not worth complaining too much about if I am the only one to think so.

**Pull request merged**
