### PR TITLE
Properly format markdown so it renders properly on GitHub

### PR DESCRIPTION
**Pull request by blag**

### CODE REVIEW

**Comment by jonathancross** [comment]
LGTM

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by prusnak** [comment]
ACK

**Comment by prusnak** [comment]
offtopic: might be a good idea to setup travis to run markdownlint like we do in our [slips](https://github.com/satoshilabs/slips/blob/master/.travis.yml) repository

**Comment by luke-jr** [comment]
For better or worse, BIPs aren't markdown (they're mediawiki).

**Comment by prusnak** [comment]
Ah, sorry. I was confused, because the document in this PR was markdown. Nevermind :)

**Pull request merged**
