### PR TITLE
BIP 107: Dynamic block size proposal

### PR DESCRIPTION
**Pull request by drwasho**
+ 2 phase plan for increasing the block size
+ Will update with BIP number if/when assigned one

### CODE REVIEW

**Comment by luke-jr** [comment]
@drwasho Please tag @gmaxwell for a BIP number assignment.

**Comment by drwasho** [comment]
Thanks @luke-jr 

@gmaxwell could you please assign this with a BIP number? Thanks.

**Comment by andre-amorim** [comment]
x0

**Comment by hoffmabc** [comment]
What does x0 mean in this context @andre-amorim ?

**Comment by drwasho** [comment]
Thanks @luke-jr , thought this was forgotten :+1:

**Comment by andre-amorim** [comment]
@drwasho sorry, Clarification, actually when I read "Please tag @gmaxwell " triggered in my mind his gpg/pgp server lookup, and sometimes you need to add x0 'KeyID 0x%k' STDIN, nevermind, I'll to not be impulsive or let race condition in my mind, see like now I'm thinking about mutex lock/unlock = 100 ns

**Pull request merged**
