### PR TITLE
BIP 39: link BitcoinJS & blockchain.info implementation

### PR DESCRIPTION
**Pull request by Sjors**
BIP 39 mnemonics are featured quite prominently in the UI as well.

### CODE REVIEW

**Comment by dcousens** [comment]
Semi-duplicate of https://github.com/bitcoin/bips/pull/307

**Comment by Sjors** [comment]
I updated my PR to also make the other languages look prettier :-)

**Comment by Sjors** [comment]
By the way I specially mention the wallet, because it provides an indication of how many bitcoin users depend on a BIP. I also added a link to the source code which could help in assessing if a BIP is fully or only partly implemented. In this case, it shows that the blockchain wallet currently doesn't use the passphrase (though it could), only the mnemonic words.

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine

**Comment by slush0** [comment]
Sorry guys, missed this. ACK.

**Comment by voisine** [comment]
belated ACK.

**Comment by ebfull** [comment]
Also missed this, ACK.

**Pull request merged**
