### PR TITLE
Fix BIP 22 hash fragments links to BIP 23

### PR DESCRIPTION
**Pull request by shesek**

### CODE REVIEW

**Comment by 0xB10C** [comment]
ACK 2afcebc

**Comment by vincenzopalazzo** [comment]
ack https://github.com/bitcoin/bips/pull/1088/commits/2afcebcbeb58bb61edaf3d3b93ed16a801e022f5

**Comment by luke-jr** [comment]
The current format is correct. Looks like a bug in GitHub's rendering engine. Not sure where to open an issue on GitHub :/

**Comment by MarcoFalke** [comment]
It might be possible to explicitly name the "anchor" with an id, but I haven't tried this

**Comment by shesek** [comment]
Even if GitHub's markdown rendering is wrong about this, I still think it makes sense to adapt to it until this is fixed. Different markdown engines have different bugs/quirks that can end up being part of their de-facto spec.

**Pull request closed without merging**
