### PR TITLE
[trivial]: Correct spellings across bips

### PR DESCRIPTION
**Pull request by Varunram**

### CODE REVIEW

**Comment by practicalswift** [comment]
ACK 333a605d21c77002efb27aaf2fe352775f1bb3b0

**Comment by luke-jr** [comment]
BIP 35: @jgarzik
BIP 60: @genjix 
BIPs 11, 16, 61: @gavinandresen 
BIPs 80 & 81: @justusranvier @jimmysong 
BIPs 98, 116, 117: @maaku @kallewoof @btcdrak 
BIP 143: @jl2012 @sipa 
BIP 152: @TheBlueMatt 
BIP 157: @Roasbeef @aakselrod @jimpo 
BIP 158: @Roasbeef @aakselrod 
BIP 174: @achow101 
BIP 176: @jimmysong 

@practicalswift Why did you ACK this? You don't seem to be an author for any of the BIPs? O.o

**Comment by practicalswift** [comment]
@luke-jr I didn't know that only BIP authors were allowed to ACK spelling errors. Sorry about that!

**Comment by luke-jr** [comment]
Yes, it's kind of a nuisance. I opened #596 a while back, but got push-back on the mailing list. :(

**Comment by jimpo** [comment]
ACK BIP 157

**Comment by sipa** [comment]
ACK BIP 143

**Comment by kallewoof** [comment]
ACK BIP 98, 116, 117.

**Comment by gavinandresen** [comment]
Perpetual ACK for all trivial changes that do not change the meaning of BIPs I wrote.

**Comment by Varunram** [comment]
ping @luke-jr, can I edit the PR just to include the BIPs which have been ACKed?

**Comment by luke-jr** [comment]
Please don't. That would reset the ACKs. I'll manually merge the applicable ones when I get a chance.

**Comment by luke-jr** [comment]
Merged BIPs 11, 16, 61, 98, 116, 117, 143, 157 in c3e8379b611a53114544b0ed7af5307b022b8ac8

Leaving open for the remaining BIPs (please don't rebase)

**Comment by jgarzik** [comment]
ACK, for my small part

**Comment by murchandamus** [comment]
I made a mistake in resolving the merge conflict with BIP-0176 and had to revert the change in another commit to avoid force pushing. I squashed the remaining for typos into master.

**Pull request merged**
