### PR TITLE
Fix link bip-0039

### PR DESCRIPTION
**Pull request by petterhs**

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Review by murchandamus — COMMENTED** [review]
The link proposed in this PR leads to a 404. I’m closing this PR due to the long period of inactivity now. Please open another PR if you want to take another stab at fixing this broken link.

**Comment by katesalazar** [comment]
I suppose the contemporary file is [here][0]<sup>\[0\]</sup> right now,
but for a perfect fit the fix should address an 2014-ish-contemporary permalink,
instead of a current permalink such as \[[0]\].

Do you feel like attempting that @petterhs? Or wanna leave it up for grabs?

---

\[0\]: https://github.com/libbitcoin/libbitcoin-system/blob/9b573e1737b286a6d9499babb94f0270d7862007/include/bitcoin/system/wallet/mnemonics/mnemonic.hpp


[0]: https://github.com/libbitcoin/libbitcoin-system/blob/9b573e1737b286a6d9499babb94f0270d7862007/include/bitcoin/system/wallet/mnemonics/mnemonic.hpp

**Comment by murchandamus** [comment]
The "Other Implementations" section was removed from the BIP per #1576.

**Pull request closed without merging**
