### PR TITLE
Update bip-0039.mediawiki with Go lib

### PR DESCRIPTION
**Pull request by Xeoncross**
Add Go library

### CODE REVIEW

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

**Comment by prusnak** [comment]
ack

**Comment by montvid** [comment]
I wanted to ask why is bip-39 still worked on if it is "Unanimously Discourage for implementation"? As I understand it needs to be replaced with a better proposal why people are using it if it is discouraged? I see that I can't open an issue on this - where can I discuss this problem?

**Comment by luke-jr** [comment]
@montvid Anyone is free to implement or not implement whatever they like.

**Comment by Xeoncross** [comment]
@montvid I found this repo outside of bitcoin usage. However, when you say this is a "Unanimously Discourage for implementation" I assume you mean for bitcoin that having a global population save English words as a key is not a good idea.

**Comment by montvid** [comment]
@Xeoncross see here for comments made by bitcoin core and electrum developers discouraging this implementation. So far i know the electrum devs are writing a bip at the moment for a better implementation. https://github.com/bitcoin/bips/wiki/Comments:BIP-0039

**Pull request merged**
