### PR TITLE
Replace elixir bip39 implementation

### PR DESCRIPTION
**Pull request by aerosol**
Follow up to #883 

Advantages:

 - 100% test coverage + [CI](https://github.com/aerosol/mnemo/actions) set up
 - smaller tests that strictly address properties of the specs
 - documentation
 - [vectors.json](https://github.com/aerosol/mnemo/blob/master/priv/vectors.json) identical to [Trezor's](https://github.com/trezor/python-mnemonic/blob/master/vectors.json) + tests for seed verification with a passphrase
  - idiomatic code, no compilation warnings, no unnecessary conversions to strings containing binary numbers
  - flexible interface, e.g. works with raw binaries as well as hex-encoded
  - does not output 1.5M of text when running tests
  - does not confuse entropy with a private key
  - no commented out code
  - descriptive commit log

@prusnak let me know if you'd like me to squash the commits

### CODE REVIEW

**Comment by prusnak** [comment]
ACK if the commits are squashed

**Comment by aerosol** [comment]
@prusnak done, thanks

**Comment by aerosol** [comment]
@prusnak let me know if this looks good please. Cheers.

**Comment by prusnak** [comment]
ack

**Comment by aerosol** [comment]
Could you merge then? Thanks

**Comment by prusnak** [comment]
I can't. I am not owner of this repo

**Comment by aerosol** [comment]
@luke-jr please have a look, thank you

**Pull request merged**
