### PR TITLE
Update BIP 109 status Draft->Rejected

### PR DESCRIPTION
**Pull request by luke-jr**
All proponents of BIP 109 seem to agree it is dead

### CODE REVIEW

**Comment by thofmann** [comment]
For reference: https://www.reddit.com/r/btc/comments/5fswjx/bitcoin_classic_is_back/

>Bitcoin Classic has merged code that removes the universally agreed dead BIP109 and implements block-size market based equilibrium. Or in simple terms, its compatible with BU.

- Thomas Zander

**Comment by zander** [comment]
ACK

**Comment by luke-jr** [comment]
@gavinandresen

**Comment by gavinandresen** [comment]
ACK. The market-based approach taken in Bitcoin Unlimited is the right way to go.

**Pull request merged**
