### PR TITLE
BIP 91: Reduced threshold Segwit MASF

### PR DESCRIPTION
**Pull request by jameshilliard**
Mailing list discussion: https://lists.linuxfoundation.org/pipermail/bitcoin-dev/2017-May/014380.html

### CODE REVIEW

**Comment by luke-jr** [comment]
Title is way too long

**Comment by jameshilliard** [comment]
Any suggestions for what I should change it to?

**Comment by sipa** [comment]
"Expedited SegWit"

**Comment by luke-jr** [comment]
Perhaps "Reduced threshold Segwit MASF"?

**Pull request merged**
