### PR TITLE
Add BIP32 bitcoinjs implementation

### PR DESCRIPTION
**Pull request by dcousens**
Also formats the list for readability

### CODE REVIEW

**Comment by dcousens** [comment]
ping @sipa,  thoughts?

**Comment by sipa** [comment]
Per https://bitcoincore.org/en/meetings/2016/05/12/ please link to actual implementation code for BIP32, and not just applications that support it.

**Comment by dcousens** [comment]
@sipa not sure what you mean?  The link added was implementation code for BIP32?

This was the link added: [[https://github.com/bitcoinjs/bitcoinjs-lib/blob/v2.1.4/src/hdnode.js|BitcoinJS]]

**Comment by afk11** [comment]
I haven't seen commit hashes included much before, just a link to the implementation's file or repo. 

Re sipa's comment, probably refers to mentioning blockchain.info's use of the bitcoin-js implementation; that information is not typically included in BIP documents. https://github.com/bitcoin/bips/pull/310/commits/681c160239fcd7b9cdfb3dc391a39d78b9029529

There is also another PR (#293) which reformats the BIP32 implementation list, perhaps coordinate so there's only one large update?

**Comment by dcousens** [comment]
> Re sipa's comment, probably refers to mentioning blockchain.info's use of the bitcoin-js implementation; that information is not typically included in BIP documents. 681c160

Right! I totally forgot that those commits were included into this.
I'll re-submit a new PR that performs the implementation reference.

If #293 is just a formatting PR,  perfect.

**Pull request closed without merging**
