### PR TITLE
fixed typos

### PR DESCRIPTION
**Pull request by fametrano**

### CODE REVIEW

**Comment by michaelfolkson** [comment]
ACK

1 s/ommitted/omitted (Incorrect spelling of "omitted")

13 s/With/with (Unnecessary capitalization of "with")

**Comment by michaelfolkson** [comment]
There is a new commit added to the original typos where

> Case: PSBT with invalid bip32 typed key

is replaced with

> Case: PSBT with invalid pubkey in input BIP 32 derivation paths typed key

Can you update the title of the PR please @fametrano as it is no longer fixing typos? Also a description of why you've made the change would make it easier for reviewers. Ultimately though Andrew Chow will need to ACK if it is to get merged.

**Comment by luke-jr** [comment]
@achow101

**Comment by achow101** [comment]
ACK 456c8c50886bbddb7c6e3a36ccc6e8adf330aba1

**Pull request merged**
