### PR TITLE
Obsolete BIP-0064

### PR DESCRIPTION
**Pull request by ysangkok**
This BIP is <s>not implemented</s> obsolete and has expired according to BIP-0002.

### CODE REVIEW

**Comment by luke-jr** [comment]
It was implemented at one point. Perhaps "Obsolete" would be better?

**Comment by ysangkok** [comment]
Ok, I changed the PR description.

**Comment by luke-jr** [comment]
...but the commit still says Rejected

**Comment by ysangkok** [comment]
@luke-jr Oh, I didn't realize Obsolete was an actual BIP-0002 state. I have corrected the commit diff and its description. The branch name remains the same. If you like, you can cherry-pick it in, or I can send a new PR if you want. Thanks for your patience.

**Comment by vincenzopalazzo** [comment]
It was implemented in https://github.com/bitcoin/bitcoin/pull/4351 but I am not able to find the reason why it was removed?

CC @luke-jr

**Pull request merged**
