### PR TITLE
Add BIP150 (Peer Authentication)

### PR DESCRIPTION
**Pull request by jonasschnelli**

### CODE REVIEW

**Comment by rebroad** [comment]
I've currently been using ZeroTier One in order to authenticate peers and avoid MITM situations. Seems to work well so far with only about 30ms added to the ping time compared with a direct IPv4 connection.

**Comment by rebroad** [comment]
Thinking about this, I don't think a simple AUTH set of messages will prevent MITM unless the connection every message uses some form of PKI. It's not enough to just have a few messages exchanged to establish identity.

**Comment by luke-jr** [comment]
This is not the place to discuss proposals.

**Comment by rebroad** [comment]
@luke-jr Thanks for this info. Where is the place please?

**Comment by luke-jr** [comment]
https://lists.linuxfoundation.org/mailman/listinfo/bitcoin-dev

**Comment by jonasschnelli** [comment]
@rebroad: I'm interested to read your concerns on the mailinglist. Be aware of the conjunction with BIP151. A "simple set" of AUTH commands together with a preshared key (and on top of BIP151) can protect against MITM attacks.

**Pull request merged**
