### PR TITLE
BIP39: Add Hungarian wordlist

### PR DESCRIPTION
**Pull request by peterkisfaludi**
made a list of 2048 Hungarian words with following criteria:
1.  Words are 4-8 letters long.
2.  Words can be uniquely determined typing the first 4 letters.
3.  No words with accents or hyphens.
4.  No words with Levehnstein distance less than 2 (Minimum Levehnstein distance for the full set of words is 2).
5.  Words are sorted according to English alphabet
6.  No words containing "j" or "ly" (as they are pronounced the same way, written differently)
7.  No words already used in other language mnemonic sets.
8.  Obscenities and bad language removed as much as possible

### CODE REVIEW

**Comment by kallewoof** [comment]
The rebase went wrong here.

**Comment by peterkisfaludi** [comment]
@kallewoof you are right, rebased to master just now

**Comment by luke-jr** [comment]
@slush0 @prusnak @voisine @ebfull

@peterkisfaludi It may be more productive in the short run to look at submitting this to https://github.com/p2w34/wlips

**Comment by prusnak** [comment]
+1 for moving all wordlists to wlips repo

**Comment by luke-jr** [comment]
For now, [the author(s) of BIP 39 have decided not to accept any further word lists into BIP 39 itself, and encourage adding new ones to the WLIPs repo](https://github.com/bitcoin/bips/pull/1129#issuecomment-873258377) here: https://github.com/p2w34/wlips

**Pull request closed without merging**
