### PR TITLE
Reject BIP-0083 (three years inactivity)

### PR DESCRIPTION
**Pull request by ysangkok**
According to the expiration rules of BIP-0002, I am permitted to request this change even though I am not the author.

### CODE REVIEW

**Comment by luke-jr** [comment]
Do we know this hasn't been implemented?

@CodeShark ping

**Comment by ysangkok** [comment]
@CodeShark hi, would you have time to reply to luke's question?

**Comment by ysangkok** [comment]
@luke-jr wouldn't we have heard from someone yet if this had been implemented?

**Comment by luke-jr** [comment]
We can always revert this later if it turns out to be in error

**Pull request merged**
