### PR TITLE
Fix: japanese words

### PR DESCRIPTION
**Pull request by dongri**
Change Japanese word

like `だ` -> `だ`

```
irb(main):003:0> "だ".bytesize
=> 6
irb(main):004:0> "だ".bytesize
=> 3
irb(main):005:0> 
```

### CODE REVIEW

**Comment by dabura667** [comment]
Please read the BIP.

All wordlists must be unicode NFKD normalized.

NFKD正規化された状態で単語リストを保有しないとバグ出ますよ。お気をつけて下さい。

**Comment by dabura667** [comment]
NACK

**Comment by dongri** [comment]
@dabura667 Thank you

BIP39 Test vectors
https://github.com/bitcoin/bips/blob/master/bip-0039.mediawiki#test-vectors

https://github.com/bip32JP/bip32JP.github.io/blob/master/test_JP_BIP39.json

Is the test data incorrect?
Not unicode NFKD normalized

**Comment by dongri** [comment]
oh...
I misunderstood the specification.

**Pull request closed without merging**
