### PR TITLE
Replace raw byte in pushed script by op name

### PR DESCRIPTION
**Pull request by NicolasDorier**
This BIP has been difficult to understand for me because I misinterpreted byte's meaning.
I think using actual op name make this proposal clearer.

### CODE REVIEW

**Comment by NicolasDorier** [comment]
I fixed inconsistencies as well: Sometimes using OP_0 and sometimes 0

**Comment by luke-jr** [comment]
@jl2012 @codeshark @sipa

**Comment by afk11** [comment]
I just opened #275, the confusion this time being around using brackets for pushes. I'd prefer serialized scripts, or at worst, a standard notation for human readable scripts.

**Comment by jl2012** [comment]
already fixed. Please close

**Pull request closed without merging**
