### PR TITLE
Sigops are in witnessScript, not witness program

### PR DESCRIPTION
**Pull request by instagibbs**

### CODE REVIEW

**Comment by jl2012** [comment]
thanks. But that's tricky as there is no witnessScript for P2WPKH. Any idea?

**Comment by instagibbs** [comment]
Hmm, yes you're right. Perhaps just say 

"while the cost of a sigop triggered during witness evaluation is 1"

**Comment by jl2012** [comment]
oh, this conflicts with #365

**Comment by luke-jr** [comment]
@CodeShark @jl2012 @sipa

**Comment by CodeShark** [comment]
ACK

**Comment by luke-jr** [comment]
I'm actually not clear on how to merge this... :|

**Comment by sipa** [comment]
@jl2012 Is this still relevant after #365 ?

**Comment by jl2012** [comment]
This is fixed with #416

**Comment by jl2012** [comment]
@instagibbs @luke-jr This should be closed as fixed with #416

**Pull request closed without merging**
