### PR TITLE
BIP 345: Remove Anthony Towns as coauthor.

### PR DESCRIPTION
**Pull request by ajtowns**
I don't want the responsibility of championing this proposal (per BIP 2), so would prefer to be removed as co-author.

### CODE REVIEW

**Comment by ajtowns** [comment]
cc @jamesob @instagibbs

**Comment by instagibbs** [comment]
Causing me to actually read BIP2:

https://github.com/bitcoin/bips/blob/master/bip-0002.mediawiki#transferring-bip-ownership

Do we generally claim the first author is champion? What if all authors are no longer to champion?

**Comment by murchandamus** [comment]
> Do we generally claim the first author is champion? 

As far as I am aware, there is no formal meaning associated with the order of authors.

> What if all authors are no longer to champion?

When the last remaining author announces that they no longer pursue activation of a BIP, I would suggest labeling the BIP as withdrawn unless another champion steps up.

**Comment by instagibbs** [comment]
I am also no longer personally championing, for whatever that means for this process.

**Review by murchandamus — COMMENTED** [review]
ACK 65b312fe4aa498de484d9c352f04958cab1170cc

The way I understand BIP 2 (especially the Transferring BIP Ownership section), an author can withdraw from a BIP’s authors at their sole discretion. Gonna wait for a spell to see if I’m missing anything here, otherwise intending to merge soonish.

**Comment by murchandamus** [comment]
> I am also no longer personally championing, for whatever that means for this process.

If you also want to withdraw your authorship, please open another PR.

**Comment by instagibbs** [comment]
I'm fine being co-author, was just making sure of process, thanks

**Comment by jamesob** [comment]
ACK

**Comment by jonatack** [comment]
Thank everyone for weighing in.

**Pull request merged**
