### PR TITLE
Update bip-0079.mediawiki

### PR DESCRIPTION
**Pull request by PandaBread2**
I've updated a few minor errors:
- Capitalization of UTXO and SegWit
- Incorrect spelling of the word 'therefore'

### CODE REVIEW

**Comment by michaelfolkson** [comment]
Thanks for this @PandaBread2.

Personally I would leave the capitalizations. We don't have a style guide for the BIPs (as far as I know) and I think we should dissuade PRs for these types of changes. For example [Bitcoin Optech](https://github.com/bitcoinops/bitcoinops.github.io/blob/master/STYLE.md) doesn't capitalize segwit.

"Therefore" is spelt incorrectly and I'd happily ACK a PR only correcting the spelling of "Therefore". But as it is it is a NACK from me.

**Comment by PandaBread2** [comment]
Thanks @michaelfolkson, I've created a new PR and will delete this one shortly

**Comment by PandaBread2** [comment]
I still think it would be a good idea to replace 'utxo' with 'UTXO'

**Comment by michaelfolkson** [comment]
> I still think it would be a good idea to replace 'utxo' with 'UTXO'

Personally I wouldn't ACK it as I don't want to encouraging these types of PRs when there isn't an obvious inaccuracy. 

You can close this pull request rather than delete it. For the new PR make sure you fork the repository, set up a topic branch and then open the PR. I don't know what you did for this PR. It appears to becoming from an unknown repository.

**Comment by PandaBread2** [comment]
Alright, fair enough

Here's the new one: https://github.com/bitcoin/bips/pull/1035

Do let me know if I've done anything incorrectly since I'm new to GitHub. Thank you very much.

**Comment by michaelfolkson** [comment]
#1035 looks good. You can close this one by pressing the Close Pull Request button at the bottom.

**Comment by PandaBread2** [comment]
Appreciate the help

**Pull request closed without merging**
